-- questions_creative_de.sql
-- 400 creative German questions for AuditUs
-- Categories: humor, habilidades, futuro, atrevidas, hipoteticas, vinculos, eventos, ia_custom

-- humor: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Wer in der Gruppe lacht am wahrscheinlichsten über seinen eigenen Witz, bevor ihn jemand anderes versteht?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer würde eine Zombie-Apokalypse am längsten überleben, nur weil er sich im nächsten Biergarten versteckt hat?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer in der Gruppe würde am wahrscheinlichsten zu einem Potluck mit Chips aus dem Supermarkt kommen und sie als "handgemacht" bezeichnen?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer würde einen Dance-Off zwischen {member_A} und {member_B} gewinnen?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer ist der offizielle "Ich-antworte-später"-Sünder der Gruppe?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Mit wem aus der Gruppe wäre es am schlimmsten, 24 Stunden lang in einem Aufzug festzustecken?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer würde am wahrscheinlichsten einen Podcast über seinen täglichen Arbeitsweg starten?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer würde eine Debatte darüber verlieren, ob eine Currywurst ein Sandwich ist?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Welches Gruppenmitglied hat den chaotischsten Spotify Wrapped?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer würde am wahrscheinlichsten auf einer Hochzeit aus den falschen Gründen viral gehen?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer würde als Erster bei einem Spieleabend rausfliegen?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer schickt die meisten "lol"-Nachrichten, ohne wirklich zu lachen?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer ist der Champion im Aufschieben (Prokrastination) in der Gruppe?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer würde eine Begegnung mit einer "Karen" ohne Tränen überstehen?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer würde versuchen, einen Kaffee mit einem High-Five zu bezahlen?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer in der Gruppe würde sich am wahrscheinlichsten versehentlich einer Sekte anschließen, während er einen Yogakurs sucht?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer würde sich als Erster ein Tattoo eines Memes stechen lassen, das zwei Tage später out ist?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer würde am wahrscheinlichsten mit einem Kassenautomaten streiten, weil er sagt "Unerwarteter Artikel im Verpackungsbereich"?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer in der Gruppe würde am wahrscheinlichsten in einer Kinderschaukel stecken bleiben?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer würde als Erster eine "Antwort an alle"-E-Mail schicken, die eigentlich nur für eine Person bestimmt war?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer würde am wahrscheinlichsten versuchen, ein wildes Tier zu streicheln, das ihn eindeutig beißen will?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer würde eine Auszeichnung erhalten für "Am wahrscheinlichsten vergessen, warum er einen Raum betreten hat"?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer in der Gruppe würde am wahrscheinlichsten ein Feuer verursachen, während er versucht, Wasser zu kochen?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wenn die Gruppe eine Bankräuber-Crew wäre, wer würde versehentlich den Fluchtschlüssel im Auto einschließen?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer würde am wahrscheinlichsten im Hintergrund eines Nachrichtenberichts bei etwas Peinlichem gesehen werden?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer würde als Erster ein Laufband kaufen und es dann als Kleiderständer benutzen?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer in der Gruppe würde am wahrscheinlichsten einen Fremden für einen Promi halten und nach einem Selfie fragen?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer würde am wahrscheinlichsten bei einer Beerdigung lachen und dann versuchen, es mit einem vorgetäuschten Husten zu vertuschen?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer in der Gruppe hat das höchste Risiko, eine "Mystery Box" von einer dubiosen Website zu kaufen?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer würde versuchen, durch eine Tür mit der Aufschrift "Ziehen" zu gehen, indem er mindestens 10 Sekunden lang drückt?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer in der Gruppe würde sich am wahrscheinlichsten ein Tattoo mit einem Rechtschreibfehler stechen lassen?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer würde als Erster versuchen, mit einem Kundenservice-KI-Bot zu flirten?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer würde am wahrscheinlichsten zu einem viralen Meme werden, ohne zu wissen, was ein Meme ist?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer würde auf einer einsamen Insel überleben, aber nur, wenn er seine Hautpflege-Routine dabei hätte?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer würde am wahrscheinlichsten vor 2030 einen Roboter heiraten?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wen würdest du anrufen, um dich aus dem Gefängnis zu holen, aber er würde am Ende auch verhaftet werden?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer aus der Gruppe hat die harmlosesten, aber seltsamsten Geheimnisse?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer wäre der beste Sektenführer für eine Gruppe, die Pizza Hawaii verehrt?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer hat das ansteckendste und lauteste Lachen in der Gruppe?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer würde am wahrscheinlichsten über eine Stunde lang vergessen, wo er sein Auto geparkt hat?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer ist die größte "Drama Queen" bei einer einfachen Erkältung?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer würde als Erster bei einer "24 Stunden kein Handy"-Challenge aufgeben?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer würde mitten in einem lauten Club einschlafen?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer würde am Ende wegen einer Instagram-Anzeige Land auf dem Mond kaufen?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer würde den Geburtstag seiner Mutter vergessen, sich aber an den eines zufälligen Anime-Charakters erinnern?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer würde weinen, weil er sich einen Nagel abgebrochen oder einen neuen Sneaker schmutzig gemacht hat?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer würde versuchen, in einem Luxus-Designerladen nach einem Rabatt zu fragen?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer würde Socken in Sandalen tragen und ernsthaft denken, es sei ein modisches Statement?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer würde etwas so Zufälliges wie Kaugummi-Papier sammeln?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true),
('Wer würde als Erster auf einen aufgezeichneten Scherzanruf hereinfallen?', 'poll', 'humor', NULL, false, 2, 'de', ARRAY['😂']::text[], true);

-- (Adding other 7 categories below...)

-- habilidades: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Wer in der Gruppe kann IKEA-Möbel zusammenbauen, ohne dass eine einzige Schraube übrig bleibt?', 'poll', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Wer hat den besten Orientierungssinn und braucht nie Google Maps?', 'poll', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Wer wäre der beste Verhandler auf einem Flohmarkt?', 'poll', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Wer in der Gruppe würde im Wald nur mit einem Schweizer Taschenmesser am besten überleben?', 'poll', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Wer tippt am schnellsten Nachrichten auf dem Handy, ohne hinzusehen?', 'poll', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Wer in der Gruppe hat eine silberne Zunge und könnte jeden von allem überzeugen?', 'poll', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Wer wäre der beste Drohnenpilot in der Gruppe?', 'poll', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Wer in der Gruppe ist ein heimliches Mathe-Genie, tut aber so, als wüsste er von nichts?', 'poll', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Wer hat die meiste Geduld, um ein Wirrwarr aus Kopfhörerkabeln zu entwirren?', 'poll', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Wer wäre der beste improvisierte Koch mit dem, was gerade im Kühlschrank ist?', 'poll', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Wer in der Gruppe würde einen Buchstabierwettbewerb für rückwärts buchstabierte Wörter gewinnen?', 'poll', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Wer kann einen TikTok-Tanz in weniger als 5 Minuten lernen?', 'poll', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Wer in der Gruppe wäre der beste Privatdetektiv (oder professioneller Stalker)?', 'poll', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Wer hat das beste Händchen dafür, einen Computer zu reparieren, der nicht startet?', 'poll', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Wer in der Gruppe würde eine Schachpartie gegen einen Profi gewinnen?', 'poll', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Wer hat die ruhigste Hand beim Jenga-Spielen nach zwei Drinks?', 'poll', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Wer in der Gruppe wäre aufgrund seiner körperlichen Fitness der beste Überlebende in einer Zombie-Apokalypse?', 'poll', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Wer kann einen Akzent aus einem anderen Land perfekt imitieren?', 'poll', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Wer in der Gruppe hat das beste Auge für Instagram-Fotos?', 'poll', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Wer wäre der Beste bei einer geheimen Talentshow?', 'poll', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Welche Note würdest du {member_A}s Fähigkeit geben, Geld zu sparen? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Von 1 bis 10, wie gut ist {member_A}s Treffsicherheit?', 'scale', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Wie gut erzählt {member_A} Witze? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Wie technikaffin ist {member_A}? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Von 1 bis 10, wie viel Disziplin hat {member_A} bei seiner Ernährung?', 'scale', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Wie schnell glaubst du, könnte {member_A} Gitarre spielen lernen? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Welche Note würdest du {member_A} für das Fahren im Berufsverkehr geben? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Von 1 bis 10, wie gut lügt {member_A}, wenn er erwischt wird?', 'scale', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Wie gut würde {member_A} ein Grillfest organisieren? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Welches Level als "Heimwerker" hat {member_A}, um Dinge zu Hause zu reparieren? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Wer würde eine politische Debatte gewinnen: {member_A} oder {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Wer würde länger in einer Wüste durchhalten: {member_A} oder {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Wer ist eher ein Profi bei Strategiespielen: {member_A} oder {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Wer hat die schönere Handschrift: {member_A} oder {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Wer würde eine Runde Trivia gewinnen: {member_A} oder {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Wer ist kreativer beim Gestalten von Dingen: {member_A} oder {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Wer hat mehr Stil beim Anziehen: {member_A} oder {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Wer löst ein Sudoku schneller: {member_A} oder {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Wer wäre ein besserer Geheimagent: {member_A} oder {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Wer hat ein besseres musikalisches Gehör: {member_A} oder {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'de', ARRAY['💪']::text[], true),
('Ordne die Gruppe danach, wer am wahrscheinlichsten eine Talent-Reality-Show gewinnen würde.', 'ranking', 'habilidades', NULL, false, 3, 'de', ARRAY['💪']::text[], true),
('Klassifiziere die Gruppe vom besten zum schlechtesten Koch.', 'ranking', 'habilidades', NULL, false, 3, 'de', ARRAY['💪']::text[], true),
('Ordne danach, wer die meiste Fähigkeit hat, sich zu konzentrieren, wenn es viel Lärm gibt.', 'ranking', 'habilidades', NULL, false, 3, 'de', ARRAY['💪']::text[], true),
('Klassifiziere die Gruppe danach, wer einen LKW auf der Autobahn besser fahren würde.', 'ranking', 'habilidades', NULL, false, 3, 'de', ARRAY['💪']::text[], true),
('Ordne danach, wer handwerklich geschickter ist (Holzarbeiten, Basteln usw.).', 'ranking', 'habilidades', NULL, false, 3, 'de', ARRAY['💪']::text[], true),
('Klassifiziere die Gruppe danach, wer sich Gesichter besser merken kann.', 'ranking', 'habilidades', NULL, false, 3, 'de', ARRAY['💪']::text[], true),
('Ordne danach, wer am schnellsten eine Extremsportart erlernen würde.', 'ranking', 'habilidades', NULL, false, 3, 'de', ARRAY['💪']::text[], true),
('Klassifiziere die Gruppe danach, wer mehr Talent für Fremdsprachen hat.', 'ranking', 'habilidades', NULL, false, 3, 'de', ARRAY['💪']::text[], true),
('Ordne danach, wer unter großem Druck besser mit Zeit umgehen kann.', 'ranking', 'habilidades', NULL, false, 3, 'de', ARRAY['💪']::text[], true),
('Klassifiziere die Gruppe danach, wer der beste Pokerspieler wäre.', 'ranking', 'habilidades', NULL, false, 3, 'de', ARRAY['💪']::text[], true);

-- futuro: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Wer in der Gruppe wird als Erster für die Arbeit auf einen anderen Kontinent ziehen?', 'poll', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Wer wird als Erster Großeltern werden und in der Gruppe damit prahlen?', 'poll', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Nach wem in der Gruppe wird eines Tages eine Straße benannt?', 'poll', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Wer wird als Erster Millionär, geht aber trotzdem noch im lokalen Imbiss essen?', 'poll', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Wer in der Gruppe wird ein Buch schreiben, das verfilmt wird?', 'poll', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Wer wird als Erster in einer geheimen Zeremonie heiraten, ohne es jemandem zu sagen?', 'poll', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Wer in der Gruppe wird am Ende bei einem super erfolgreichen Tech-Startup arbeiten?', 'poll', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Wer wird als Erster vor dem Alter von 45 Jahren in Rente gehen?', 'poll', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Wer in der Gruppe wird einen bedeutenden Preis in seinem Fachgebiet gewinnen?', 'poll', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Wer wird als Erster ein Haus mit Pool kaufen?', 'poll', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Wer in der Gruppe wird eine sehr große Familie haben?', 'poll', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Wer wird als Erster all seine sozialen Medien endgültig löschen?', 'poll', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Wer in der Gruppe wird zu einem super exklusiven Event in Hollywood eingeladen?', 'poll', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Wer wird als Erster in einem super trendigen Viertel der Stadt wohnen?', 'poll', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Wer in der Gruppe wird am Ende ein super einflussreicher Vordenker sein?', 'poll', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Wer wird als Erster eine Rucksackreise durch Asien machen?', 'poll', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Wer in der Gruppe wird seine eigene Tequila- oder Weinmarke haben?', 'poll', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Wer wird als Erster super fit werden und nie wieder Junkfood essen?', 'poll', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Wer in der Gruppe wird für seine großen Beiträge zur Gemeinschaft in Erinnerung bleiben?', 'poll', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Wer wird als Erster einen Haufen Katzen adoptieren?', 'poll', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Wie wahrscheinlich ist es, dass {member_A} in 3 Jahren ein berühmter Influencer sein wird? (0-100%)', 'scale', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Von 1 bis 10, wie sehr wird sich {member_A}s Leben dieses Jahr deiner Meinung nach verändern?', 'scale', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Welches Erfolgslevel wird {member_A} deiner Meinung nach in seinem Geschäft erreichen? (1-10)', 'scale', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Von 1 bis 10, wie sehr wird {member_A} seine Ziele dieses Jahr deiner Meinung nach erreichen?', 'scale', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Wie wahrscheinlich ist es, dass {member_A} bald ein digitaler Nomade wird? (1-10)', 'scale', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Welche Note würdest du der zukünftigen Stabilität von {member_A}s Beziehung geben? (1-10)', 'scale', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Von 1 bis 10, wie sehr wird {member_A} deiner Meinung nach das Leben anderer beeinflussen?', 'scale', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Wie wahrscheinlich ist es, dass {member_A} eines Tages im Lotto gewinnt? (1-10)', 'scale', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Welches Maß an Seelenfrieden wird {member_A} deiner Meinung nach im Alter haben? (1-10)', 'scale', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Von 1 bis 10, wie sehr wird {member_A} es deiner Meinung nach bereuen, heute etwas nicht getan zu haben?', 'scale', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Wer wird in 15 Jahren ein cooleres Haus haben: {member_A} oder {member_B}?', 'vs', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Wer wird glücklicher sein, wenn er in Rente geht: {member_A} oder {member_B}?', 'vs', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Wer wird eine höhere Position im Job haben: {member_A} oder {member_B}?', 'vs', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Wer wird in dem, was er tut, mehr respektiert werden: {member_A} oder {member_B}?', 'vs', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Wer wird mehr Länder besuchen: {member_A} oder {member_B}?', 'vs', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Wer wird in Zukunft mehr Kontakt zur Gruppe halten: {member_A} oder {member_B}?', 'vs', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Wer wird mit dem Alter weiser werden: {member_A} oder {member_B}?', 'vs', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Wer wird die Technologie der Zukunft besser verstehen: {member_A} oder {member_B}?', 'vs', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Wer wird mehr Enkelkinder haben: {member_A} oder {member_B}?', 'vs', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Wer wird an einem ruhigeren Ort leben: {member_A} oder {member_B}?', 'vs', 'futuro', NULL, false, 2, 'de', ARRAY['🔮']::text[], true),
('Ordne die Gruppe danach, wer den größten Erfolg in seiner Karriere haben wird.', 'ranking', 'futuro', NULL, false, 3, 'de', ARRAY['🔮']::text[], true),
('Klassifiziere die Gruppe danach, wer seine Träume zuerst verwirklichen wird.', 'ranking', 'futuro', NULL, false, 3, 'de', ARRAY['🔮']::text[], true),
('Ordne danach, wer einen größeren Eindruck in der Welt hinterlassen wird.', 'ranking', 'futuro', NULL, false, 3, 'de', ARRAY['🔮']::text[], true),
('Klassifiziere die Gruppe danach, wer mit der Zeit jünger aussehen wird.', 'ranking', 'futuro', NULL, false, 3, 'de', ARRAY['🔮']::text[], true),
('Ordne danach, wer in den nächsten 20 Jahren exotischere Reisen unternehmen wird.', 'ranking', 'futuro', NULL, false, 3, 'de', ARRAY['🔮']::text[], true),
('Klassifiziere die Gruppe danach, wer ein entspannteres Leben haben wird.', 'ranking', 'futuro', NULL, false, 3, 'de', ARRAY['🔮']::text[], true),
('Ordne danach, wer zuerst heiraten wird (oder wieder).', 'ranking', 'futuro', NULL, false, 3, 'de', ARRAY['🔮']::text[], true),
('Klassifiziere die Gruppe danach, wer mehr für die Gesellschaft tun wird.', 'ranking', 'futuro', NULL, false, 3, 'de', ARRAY['🔮']::text[], true),
('Ordne danach, wer mehr über zukünftige Trends auf dem Laufenden sein wird.', 'ranking', 'futuro', NULL, false, 3, 'de', ARRAY['🔮']::text[], true),
('Klassifiziere die Gruppe danach, wer ein längeres und erfüllteres Leben führen wird.', 'ranking', 'futuro', NULL, false, 3, 'de', ARRAY['🔮']::text[], true);

-- (Adding the remaining 5 categories for de...)

-- atrevidas: 50 questions (anonymous)
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Was ist die größte Lüge, die du je erzählt hast, um nicht mit jemandem auszugehen?', 'free', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Wer in der Gruppe hat deiner Meinung nach den "seltsamsten" Geschmack im Bett?', 'poll', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Hast du jemals so getan, als würdest du jemanden mögen, nur aus Interesse?', 'free', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Wem in dieser Gruppe würdest du einen Kuss geben, wenn wir Flaschendrehen spielen würden?', 'poll', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Was ist der verrückteste Ort, an dem du je Action hattest?', 'free', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Hast du schon mal von jemandem aus dieser Gruppe geträumt?', 'free', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Was ist deine "dunkelste" Fantasie, von der niemand weiß?', 'free', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Hast du jemals jemanden "geghostet", den du eigentlich mochtest?', 'free', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Wer in der Gruppe ist deiner Meinung nach von Natur aus ein "Player"?', 'poll', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Was ist das Gewagteste, was du je für jemanden getan hast, in den du verrückt warst?', 'free', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Hast du jemals ein "Nacktfoto" geschickt und danach schreckliche Angst davor gehabt?', 'free', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Wer in der Gruppe flirtet deiner Meinung nach am meisten über Apps wie Tinder oder Bumble?', 'poll', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Warst du jemals mit zwei Personen gleichzeitig zusammen?', 'free', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Wen aus dieser Gruppe würdest du in eine Hütte mitnehmen, nur um zu "reden"?', 'poll', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Was ist die expliziteste Nachricht, die du je an die falsche Person geschickt hast?', 'free', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Hat dir jemals der Partner von jemandem aus der Gruppe gefallen?', 'free', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Wer in der Gruppe hat deiner Meinung nach die intensivsten Fetische?', 'poll', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Was war dein schlimmstes Erlebnis beim ersten Mal?', 'free', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Wurdest du jemals "auf frischer Tat" ertappt?', 'free', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Wer in der Gruppe ist deiner Meinung nach privat eher "wild"?', 'poll', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Hast du jemals Spielzeug benutzt und was ist dein Favorit?', 'free', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Wer in der Gruppe hatte deiner Meinung nach die meisten Sexualpartner?', 'poll', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Was ist die größte Lüge, die du erzählt hast, damit jemand mit dir ins Bett geht?', 'free', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Wem in dieser Gruppe würdest du dein entsperrtes Handy anvertrauen?', 'poll', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Hattest du jemals einen Dreier oder willst du unbedingt einen?', 'free', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Wer in der Gruppe ist deiner Meinung nach am wahrscheinlichsten für einen One-Night-Stand zu haben?', 'poll', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Welches tiefe Geheimnis hast du über einen Ex-Partner?', 'free', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Warst du jemals mit jemandem zusammen, der viel älter war als du?', 'free', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Wer in der Gruppe gibt deiner Meinung nach mehr an, als er tatsächlich tut?', 'poll', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Was ist das "seltsamste" Ding, nach dem du im Inkognito-Modus gegoogelt hast?', 'free', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Hast du dich jemals zu jemandem des gleichen Geschlechts hingezogen gefühlt (wenn du hetero bist)?', 'free', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Wer in der Gruppe hat deiner Meinung nach ein geheimes Profil auf einer Dating-App?', 'poll', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Was war der peinlichste Moment, den du je ohne Kleidung hattest?', 'free', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Hattest du schon mal Telefonsex oder heftiges Sexting?', 'free', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Wer in der Gruppe ist deiner Meinung nach im Bett am "konservativsten"?', 'poll', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Welcher Teil deines Körpers ist dein geheimer "Knopf"?', 'free', 'atrevidas', NULL, true, 2, 'de', ARRAY['Graphic']::text[], true),
('Hast du jemals für Sex bezahlt oder wurde dir Geld dafür angeboten?', 'free', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Wer in der Gruppe würde einen Seitensprung deiner Meinung nach am schnellsten verzeihen?', 'poll', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Welcher Fetisch ist dir am peinlichsten zuzugeben?', 'free', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Hast du jemals ein intimes Video aufgenommen?', 'free', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Wer in der Gruppe ist deiner Meinung nach am "neugierigsten", neue Dinge auszuprobieren?', 'poll', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('An welchem öffentlichen Ort würdest du am liebsten mal Action haben?', 'free', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Hattest du jemals ein Techtelmechtel mit jemandem von der Arbeit?', 'free', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Wer in der Gruppe ist deiner Meinung nach der Heißeste / die Heißeste?', 'poll', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Was war das Verrückteste, was du je getan hast, während du betrunken warst?', 'free', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Hast du dich jemals mit einem Ex getroffen, während du mit jemand anderem zusammen warst?', 'free', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Wer in der Gruppe ist deiner Meinung nach ein heimlicher Romantiker?', 'poll', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Was ist die verrückteste Fantasie, die du dir schon erfüllt hast?', 'free', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Warst du jemals in einer offenen Beziehung?', 'free', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true),
('Wen in dieser Gruppe würdest du zu einem Dreier einladen, wenn er/sie ja sagen würde?', 'poll', 'atrevidas', NULL, true, 2, 'de', ARRAY['🌶️']::text[], true);

-- hipoteticas: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Wenn du eine Superkraft haben könntest, aber nur einmal alle 6 Monate, welche wäre das?', 'mc', 'hipoteticas', ARRAY['Unsichtbarkeit 12h', 'Zeitreise in Vergangenheit 30 min', 'Gedanken lesen 1h', 'Fliegen 2h'], false, 2, 'de', ARRAY['🧠']::text[], true),
('Wenn die Gruppe auf einer einsamen Insel strandet, wer würde zuerst das Feuer entfachen?', 'poll', 'hipoteticas', NULL, false, 2, 'de', ARRAY['🧠']::text[], true),
('Wenn du eine Woche lang in einem Film leben könntest, welchen würdest du wählen?', 'mc', 'hipoteticas', ARRAY['Harry Potter', 'Avengers', 'Der Wolf von Wall Street', 'Der Schuh des Manitu'], false, 2, 'de', ARRAY['🧠']::text[], true),
('Wenn du jemanden aus der Gruppe wählen müsstest, der dich in einem Rechtsstreit verteidigt, wer wäre das?', 'poll', 'hipoteticas', NULL, false, 2, 'de', ARRAY['🧠']::text[], true),
('Wenn du 5 Millionen Euro bekommen würdest, um nie wieder Pizza zu essen, würdest du es tun?', 'mc', 'hipoteticas', ARRAY['Ja, klar', 'Niemals', 'Nur wenn ich Burger essen darf', 'Ich würde lange drüber nachdenken'], false, 2, 'de', ARRAY['🧠']::text[], true),
('Wenn die Gruppe eine Fußballmannschaft wäre, wer wäre der Kapitän?', 'poll', 'hipoteticas', NULL, false, 2, 'de', ARRAY['🧠']::text[], true),
('Wenn du genau wüsstest, an welchem Tag du sterben würdest, würdest du es wissen wollen?', 'mc', 'hipoteticas', ARRAY['Ja, um alles auszugeben', 'Nein, wie gruselig', 'Nur wenn ich es ändern kann', 'Ich bevorzuge die Überraschung'], false, 2, 'de', ARRAY['🧠']::text[], true),
('Wenn du jemanden aus der Gruppe wählen müsstest, der dich pflegt, wenn du richtig krank bist, wer wäre das?', 'poll', 'hipoteticas', NULL, false, 2, 'de', ARRAY['🧠']::text[], true),
('Wenn du jetzt sofort jede Sprache fließend sprechen könntest, welche würdest du wählen?', 'mc', 'hipoteticas', ARRAY['Japanisch', 'Französisch', 'Spanisch', 'Russisch'], false, 2, 'de', ARRAY['🧠']::text[], true),
('Wenn die Gruppe in einer Zombie-Apokalypse wäre, wer würde sich als Erster für die anderen opfern?', 'poll', 'hipoteticas', NULL, false, 2, 'de', ARRAY['🧠']::text[], true),
('Wenn du dich jetzt sofort an einen beliebigen Ort teleportieren könntest, wohin würdest du gehen?', 'mc', 'hipoteticas', ARRAY['An einen Strand auf den Malediven', 'Nach New York zum Shoppen', 'Auf die Spitze des Eiffelturms', 'In mein Bett zum Schlafen'], false, 2, 'de', ARRAY['🧠']::text[], true),
('Wenn du jemandem in der Gruppe deine PIN anvertrauen müsstest, wer wäre das?', 'poll', 'hipoteticas', NULL, false, 2, 'de', ARRAY['🧠']::text[], true),
('Wenn du eine berühmte Person wiederbeleben könntest, um etwas zu trinken, wer wäre das?', 'mc', 'hipoteticas', ARRAY['Freddie Mercury', 'Frida Kahlo', 'Steve Jobs', 'Goethe'], false, 2, 'de', ARRAY['🧠']::text[], true),
('Wenn die Gruppe eine Reality-Show wäre, wer würde gewinnen, weil er am "echtesten" ist?', 'poll', 'hipoteticas', NULL, false, 2, 'de', ARRAY['🧠']::text[], true),
('Wenn du einen Fehler aus deiner Vergangenheit löschen könntest, welchen würdest du wählen?', 'free', 'hipoteticas', NULL, false, 2, 'de', ARRAY['🧠']::text[], true),
('Wenn du jemanden aus der Gruppe wählen müsstest, um Beweise zu verstecken (nur zum Spaß), wer wäre das?', 'poll', 'hipoteticas', NULL, false, 2, 'de', ARRAY['🧠']::text[], true),
('Wenn du unsterblich sein könntest, würdest du es akzeptieren?', 'mc', 'hipoteticas', ARRAY['Ja, auf jeden Fall', 'Nein, wie langweilig', 'Nur wenn ich nicht altere', 'Nur wenn meine Freunde es auch sind'], false, 2, 'de', ARRAY['🧠']::text[], true),
('Wenn die Gruppe ein Geschäft gründen würde, wer würde das Geld verwalten?', 'poll', 'hipoteticas', NULL, false, 2, 'de', ARRAY['🧠']::text[], true),
('Wenn du eine traurige Erinnerung aus deinem Kopf löschen könntest, würdest du es tun?', 'free', 'hipoteticas', NULL, false, 2, 'de', ARRAY['🧠']::text[], true),
('Wenn du ein Jahr lang mit jemandem aus der Gruppe in einer Wohngemeinschaft leben müsstest, wer wäre das?', 'poll', 'hipoteticas', NULL, false, 2, 'de', ARRAY['🧠']::text[], true),
('Wie hoch ist die Wahrscheinlichkeit, dass uns bald Außerirdische besuchen? (0-10)', 'scale', 'hipoteticas', NULL, false, 2, 'de', ARRAY['🧠']::text[], true),
('Von 1 bis 10, wie sehr glaubst du, dass Maschinen rebellieren werden?', 'scale', 'hipoteticas', NULL, false, 2, 'de', ARRAY['🧠']::text[], true),
('Wie glücklich wären wir in einer Welt ohne Internet? (1-10)', 'scale', 'hipoteticas', NULL, false, 2, 'de', ARRAY['🧠']::text[], true),
('Von 1 bis 10, wie sehr glaubst du an Geister?', 'scale', 'hipoteticas', NULL, false, 2, 'de', ARRAY['🧠']::text[], true),
('Wie wahrscheinlich hältst du es, dass wir in einer Simulation leben? (1-10)', 'scale', 'hipoteticas', NULL, false, 2, 'de', ARRAY['🧠']::text[], true),
('Von 1 bis 10, wie viel würdest du geben, um den Planeten zu retten?', 'scale', 'hipoteticas', NULL, false, 2, 'de', ARRAY['🧠']::text[], true),
('Wie wichtig findest du es, andere Planeten zu besiedeln? (1-10)', 'scale', 'hipoteticas', NULL, false, 2, 'de', ARRAY['🧠']::text[], true),
('Von 1 bis 10, wie sehr glaubst du, dass die Zukunft bereits geschrieben steht?', 'scale', 'hipoteticas', NULL, false, 2, 'de', ARRAY['🧠']::text[], true),
('Wie möglich hältst du Zeitreisen eines Tages? (1-10)', 'scale', 'hipoteticas', NULL, false, 2, 'de', ARRAY['🧠']::text[], true),
('Von 1 bis 10, wie sehr machen dir intelligente Roboter Angst?', 'scale', 'hipoteticas', NULL, false, 2, 'de', ARRAY['🧠']::text[], true),
('Wer wäre ein besserer Anführer in einer Krise: {member_A} oder {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'de', ARRAY['🧠']::text[], true),
('Wer würde besser im 18. Jahrhundert überleben: {member_A} oder {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'de', ARRAY['🧠']::text[], true),
('Wer würde sich zuerst mit einem Alien anfreunden: {member_A} oder {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'de', ARRAY['🧠']::text[], true),
('Wer würde sich entscheiden, die Matrix zu verlassen: {member_A} oder {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'de', ARRAY['🧠']::text[], true),
('Wer wäre ein besserer Astronaut: {member_A} oder {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'de', ARRAY['🧠']::text[], true),
('Wer würde sich bei einem Problem für die Gruppe einsetzen: {member_A} oder {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'de', ARRAY['🧠']::text[], true),
('Wer wäre der beste Vertreter der Erde: {member_A} oder {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'de', ARRAY['🧠']::text[], true),
('Wer würde sich besser an das Leben unter Wasser anpassen: {member_A} oder {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'de', ARRAY['🧠']::text[], true),
('Wer würde bei einem Beleidigungsduell mit einem Piraten gewinnen: {member_A} oder {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'de', ARRAY['🧠']::text[], true),
('Wer würde zuerst glauben, dass das alles ein Traum ist: {member_A} oder {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'de', ARRAY['🧠']::text[], true),
('Ordne die Gruppe danach, wer in einem Horrorfilm am längsten überleben würde.', 'ranking', 'hipoteticas', NULL, false, 3, 'de', ARRAY['🧠']::text[], true),
('Klassifiziere die Gruppe von mehr bis weniger verdächtig, ein Spion zu sein.', 'ranking', 'hipoteticas', NULL, false, 3, 'de', ARRAY['🧠']::text[], true),
('Ordne danach, wer der beste Stratege in einem Kriegsspiel wäre.', 'ranking', 'hipoteticas', NULL, false, 3, 'de', ARRAY['🧠']::text[], true),
('Klassifiziere die Gruppe danach, wer am nützlichsten wäre, wenn die Welt untergeht.', 'ranking', 'hipoteticas', NULL, false, 3, 'de', ARRAY['🧠']::text[], true),
('Ordne danach, wer sich zuerst freiwillig melden würde, um zum Mars zu fliegen.', 'ranking', 'hipoteticas', NULL, false, 3, 'de', ARRAY['🧠']::text[], true),
('Klassifiziere die Gruppe danach, wer das Heilmittel für eine Krankheit erfinden würde.', 'ranking', 'hipoteticas', NULL, false, 3, 'de', ARRAY['🧠']::text[], true),
('Ordne danach, wer der beste Unterhändler mit einer außerirdischen Rasse wäre.', 'ranking', 'hipoteticas', NULL, false, 3, 'de', ARRAY['🧠']::text[], true),
('Klassifiziere die Gruppe danach, wer bei einem Erdbeben am ruhigsten bleiben würde.', 'ranking', 'hipoteticas', NULL, false, 3, 'de', ARRAY['🧠']::text[], true),
('Ordne danach, wer am kreativsten neue Gesellschaftsregeln erfinden würde.', 'ranking', 'hipoteticas', NULL, false, 3, 'de', ARRAY['🧠']::text[], true),
('Klassifiziere die Gruppe danach, wer der beste Führer in einer postapokalyptischen Welt wäre.', 'ranking', 'hipoteticas', NULL, false, 3, 'de', ARRAY['🧠']::text[], true);

-- vinculos: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Wer in der Gruppe ist derjenige, der immer die Ausflüge organisiert?', 'poll', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Wer in der Gruppe hat dir den besten Rat gegeben, als du dich schlecht gefühlt hast?', 'poll', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Wer ist die loyalste Person, die du in dieser Gruppe kennst?', 'poll', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Wer in der Gruppe ist immer da, wenn man sich mal aussprechen muss?', 'poll', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Wem in dieser Gruppe würdest du deine Hausschlüssel anvertrauen?', 'poll', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Wer hat sich als Person am meisten weiterentwickelt, seit du ihn kennst?', 'poll', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Wer in der Gruppe hat das edelste Herz von allen?', 'poll', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Mit wem in dieser Gruppe lachst du, bis dein Bauch wehtut?', 'poll', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Wen in dieser Gruppe würdest du anrufen, wenn du einen echten Notfall hättest?', 'poll', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Wer in der Gruppe kann am besten zuhören, ohne zu urteilen?', 'poll', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Wer hält die WhatsApp-Gruppe zusammen?', 'poll', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Wen in dieser Gruppe bewunderst du am meisten für seine Art, das Leben zu sehen?', 'poll', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Wer in der Gruppe ist am ehrlichsten, auch wenn es wehtut, was er sagt?', 'poll', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Wer ist die coolste Person, um eine ruhige Zeit beim Reden zu verbringen?', 'poll', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Bei wem in dieser Gruppe würdest du dich zuerst entschuldigen, wenn ihr Reibungen hättet?', 'poll', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Wer in der Gruppe kümmert sich am meisten um alle?', 'poll', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Wer ist die Person, die dich am meisten motiviert, in dieser Gruppe besser zu sein?', 'poll', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Wem in dieser Gruppe würdest du etwas erzählen, das dir sehr peinlich ist?', 'poll', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Wer in der Gruppe achtet am meisten auf Geburtstage?', 'poll', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Wer ist die Person, die die meiste gute Energie in dein Leben bringt?', 'poll', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Von 1 bis 10, wie sehr vertraust du {member_A}?', 'scale', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Wie gut ist die Verbindung, die du zu {member_A} hast? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Welchen Platz nimmt {member_A} in deiner Liste der Lieblingsmenschen ein? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Von 1 bis 10, wie sehr glaubst du, dass {member_A} dich wirklich versteht?', 'scale', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Welche Note würdest du der Loyalität von {member_A} gegenüber der Gruppe geben? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Wie gut unterstützt {member_A} andere? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Von 1 bis 10, wie sehr genießt du es, mit {member_A} über ernste Dinge zu sprechen?', 'scale', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Wie wichtig ist es dir, für immer mit {member_A} befreundet zu bleiben? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Welches Maß an Ehrlichkeit hat {member_A} deiner Meinung nach dir gegenüber? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Von 1 bis 10, wie sehr würde sich die Gruppe deiner Meinung nach verändern, wenn {member_A} nicht da wäre?', 'scale', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Wer kümmert sich mehr um seine Freunde: {member_A} oder {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Mit wem sprichst du lieber über deine Probleme: {member_A} oder {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Wer hat mehr Geduld mit der Gruppe: {member_A} oder {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Wer ist aufmerksamer gegenüber seinen Freundschaften: {member_A} oder {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Wen würdest du anrufen, um ein bisschen zu weinen: {member_A} oder {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Wer kennt dich besser, wenn du schlechte Laune hast: {member_A} oder {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Wer ist ehrlicher, wenn er Dinge anspricht: {member_A} oder {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Bei wem fühlst du dich ohne Filter mehr "du": {member_A} oder {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Wer würde einen Fehler leichter verzeihen: {member_A} oder {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Wer ist großzügiger mit seiner Zeit: {member_A} oder {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'de', ARRAY['💛']::text[], true),
('Ordne die Gruppe danach, wer am besten Geheimnisse bewahren kann.', 'ranking', 'vinculos', NULL, false, 3, 'de', ARRAY['💛']::text[], true),
('Klassifiziere die Gruppe nach ihrem Maß an Empathie gegenüber anderen.', 'ranking', 'vinculos', NULL, false, 3, 'de', ARRAY['💛']::text[], true),
('Ordne danach, wer dir zuerst ungefragt aus einer Patsche helfen würde.', 'ranking', 'vinculos', NULL, false, 3, 'de', ARRAY['💛']::text[], true),
('Klassifiziere die Gruppe danach, wer seinen Freundschaften am treuesten ist.', 'ranking', 'vinculos', NULL, false, 3, 'de', ARRAY['💛']::text[], true),
('Ordne danach, wer in seinen Ratschlägen am aufrichtigsten ist (auch wenn es wehtut).', 'ranking', 'vinculos', NULL, false, 3, 'de', ARRAY['💛']::text[], true),
('Klassifiziere die Gruppe danach, wer sich am meisten darum sorgt, wie es allen geht.', 'ranking', 'vinculos', NULL, false, 3, 'de', ARRAY['💛']::text[], true),
('Ordne danach, wer am lustigsten für eine Reise ist.', 'ranking', 'vinculos', NULL, false, 3, 'de', ARRAY['💛']::text[], true),
('Klassifiziere die Gruppe danach, wer sich am leichtesten versöhnen kann.', 'ranking', 'vinculos', NULL, false, 3, 'de', ARRAY['💛']::text[], true),
('Ordne danach, wer mehr Frieden und Ruhe in die Gruppe bringt.', 'ranking', 'vinculos', NULL, false, 3, 'de', ARRAY['💛']::text[], true),
('Klassifiziere die Gruppe danach, wer die beste Freundschafts-Entdeckung war.', 'ranking', 'vinculos', NULL, false, 3, 'de', ARRAY['💛']::text[], true);

-- eventos: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Wer in der Gruppe ist derjenige, der immer die Weihnachtsfeier organisiert?', 'poll', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Wer vergisst am wahrscheinlichsten, dass wir heute verabredet waren?', 'poll', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Wem in dieser Gruppe würdest du die Planung deiner Geburtstagsparty anvertrauen?', 'poll', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Wer in der Gruppe sagt als Erster "Lass uns eine Reise machen" ans andere Ende der Welt?', 'poll', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Wer kommt immer zu spät, bringt aber die Getränke mit?', 'poll', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Wer in der Gruppe ist der größte Partylöwe und will nie schlafen gehen?', 'poll', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Wer bereitet bei Treffen die besten Drinks zu?', 'poll', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Wen aus der Gruppe würdest du als DJ für deine Party wählen?', 'poll', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Wer in der Gruppe macht bei jedem Ausflug die meisten Fotos?', 'poll', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Wer kümmert sich immer darum, alles für das Grillfest zu kaufen?', 'poll', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Wer in der Gruppe landet am wahrscheinlichsten beim Tanzen auf einem Stuhl?', 'poll', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Wen in dieser Gruppe würdest du bitten, das ganze Wochenende mit zu einem Musikfestival zu kommen?', 'poll', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Wer in der Gruppe findet immer die günstigsten Flüge?', 'poll', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Wer ist die "alte Seele" der Gruppe und will früh nach Hause?', 'poll', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Wem in dieser Gruppe würdest du vertrauen, das Airbnb für alle zu reservieren?', 'poll', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Wer in der Gruppe ist am lustigsten für ein Wochenende in einer gemütlichen Hütte?', 'poll', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Wer schlägt immer vor, in Museen oder ähnliche Dinge zu gehen?', 'poll', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Wen in dieser Gruppe würdest du wählen, um auf den Jahrmarkt zu gehen und auf die verrücktesten Fahrgeschäfte zu steigen?', 'poll', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Wer in der Gruppe verläuft sich am wahrscheinlichsten auf einem Konzert?', 'poll', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Wer organisiert die besten Überraschungen für andere?', 'poll', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Von 1 bis 10, wie sehr magst du spontane Pläne?', 'scale', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Wie "hyped" würdest du unsere Gruppenausflüge bewerten? (1-10)', 'scale', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Wie wichtig ist es dir, uns persönlich zu treffen? (1-10)', 'scale', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Von 1 bis 10, wie gut glaubst du, hätten wir Spaß bei einem Ausflug an den Strand?', 'scale', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Wie würdest du die Pünktlichkeit der Gruppe bei Verabredungen bewerten? (1-10)', 'scale', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Wie sehr freust du dich auf das nächste Treffen? (1-10)', 'scale', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Von 1 bis 10, wie sehr magst du es, selbst Pläne zu organisieren?', 'scale', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Wie schwierig ist es für die Gruppe, sich auf einen Plan zu einigen? (1-10)', 'scale', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Wie wichtig ist es dir, jeden Geburtstag zu feiern? (1-10)', 'scale', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Von 1 bis 10, wie sehr vermisst du die Gruppe, wenn wir uns lange nicht sehen?', 'scale', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Wer kann besser organisieren: {member_A} oder {member_B}?', 'vs', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Mit wem verreist du lieber: {member_A} oder {member_B}?', 'vs', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Wer hält länger auf einer Party durch: {member_A} oder {member_B}?', 'vs', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Wer schlägt die verrücktesten Pläne vor: {member_A} oder {member_B}?', 'vs', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Wer hat einen besseren Geschmack für Restaurants: {member_A} oder {member_B}?', 'vs', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Wer ist pünktlicher: {member_A} oder {member_B}?', 'vs', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Wem würdest du das Geld für die Reise anvertrauen: {member_A} oder {member_B}?', 'vs', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Wer macht mehr Spaß beim Karaoke: {member_A} oder {member_B}?', 'vs', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Wer macht bessere Erinnerungsfotos: {member_A} oder {member_B}?', 'vs', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Wer schläft am wahrscheinlichsten auf dem Rückweg von der Party ein: {member_A} oder {member_B}?', 'vs', 'eventos', NULL, false, 2, 'de', ARRAY['🎉']::text[], true),
('Ordne die Gruppe danach, wer am meisten Stimmung macht.', 'ranking', 'eventos', NULL, false, 3, 'de', ARRAY['🎉']::text[], true),
('Klassifiziere die Gruppe danach, wer am meisten Lust hat, draußen zu sein.', 'ranking', 'eventos', NULL, false, 3, 'de', ARRAY['🎉']::text[], true),
('Ordne danach, wer am wahrscheinlichsten alles auf einer Reise regelt.', 'ranking', 'eventos', NULL, false, 3, 'de', ARRAY['🎉']::text[], true),
('Klassifiziere die Gruppe danach, wer der Pünktlichste von allen ist.', 'ranking', 'eventos', NULL, false, 3, 'de', ARRAY['🎉']::text[], true),
('Ordne danach, wer die beste Musik auflegt, wenn wir zusammen sind.', 'ranking', 'eventos', NULL, false, 3, 'de', ARRAY['🎉']::text[], true),
('Klassifiziere die Gruppe danach, wer überall am schnellsten Freunde findet.', 'ranking', 'eventos', NULL, false, 3, 'de', ARRAY['🎉']::text[], true),
('Ordne danach, wer alles am meisten auf Video festhält.', 'ranking', 'eventos', NULL, false, 3, 'de', ARRAY['🎉']::text[], true),
('Klassifiziere die Gruppe danach, wer eher Überraschungen macht.', 'ranking', 'eventos', NULL, false, 3, 'de', ARRAY['🎉']::text[], true),
('Ordne danach, wer entspannter ist, wenn wir zusammen verreisen.', 'ranking', 'eventos', NULL, false, 3, 'de', ARRAY['🎉']::text[], true),
('Klassifiziere die Gruppe danach, wer bisher den besten Gruppenplan gemacht hat.', 'ranking', 'eventos', NULL, false, 3, 'de', ARRAY['🎉']::text[], true);

-- ia_custom: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Wer in der Gruppe benutzt als Erster ChatGPT, um in der Gruppe zu antworten?', 'poll', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Wer wird in Zukunft am wahrscheinlichsten mit einer KI ausgehen?', 'poll', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Wem in dieser Gruppe würdest du vertrauen, dass eine von ihm/ihr programmierte KI dein Geld verwaltet?', 'poll', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Wer in der Gruppe hat am meisten Angst davor, dass Roboter uns beherrschen?', 'poll', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Wer weiß immer Bescheid, was es für neue KI-Apps gibt?', 'poll', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Wer in der Gruppe würde sich als Erster einen Chip einpflanzen lassen, um klüger zu sein?', 'poll', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Wer nutzt KI am besten aus, um nicht so viel arbeiten zu müssen?', 'poll', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Wen würdest du wählen, um der erste Mensch auf dem Mars zu sein, der von Robotern unterstützt wird?', 'poll', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Wer in der Gruppe hasst KI in der Kunst oder Musik am meisten?', 'poll', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Wer denkt immer, dass alles, was er im Internet sieht, wegen KI gefälscht ist?', 'poll', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Wer in der Gruppe hätte als Erster einen digitalen Klon?', 'poll', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Wen würdest du um Hilfe bitten, um deine eigene personalisierte KI zu erstellen?', 'poll', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Wer in der Gruppe ist am optimistischsten, was die Zukunft der Roboter angeht?', 'poll', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Wer behandelt Alexa oder Google bereits so, als wären sie echte Menschen?', 'poll', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Wem in dieser Gruppe würdest du deine persönlichen Daten gegenüber Algorithmen anvertrauen?', 'poll', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Wer in der Gruppe glaubt, dass eine KI ihm bald den Job wegnehmen wird?', 'poll', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Wer benutzt immer KI-Filter, um auf seinen Fotos anders auszusehen?', 'poll', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Wen würdest du wählen, um den menschlichen Widerstand gegen die Maschinen anzuführen?', 'poll', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Wer in der Gruppe lernt am wahrscheinlichsten Programmieren, nur um seine eigene KI zu erstellen?', 'poll', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Wer weiß schon gar nicht mehr, ob eine Nachricht von einem Menschen oder einer Maschine geschrieben wurde?', 'poll', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Von 1 bis 10, wie sehr vertraust du dem, was ChatGPT dir sagt?', 'scale', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Wie sehr hat KI dein tägliches Leben bisher verändert? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Wie wichtig findest du es, dass KI ethische Regeln hat? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Von 1 bis 10, für wie möglich hältst du es, dass wir die Kontrolle über die Maschinen verlieren?', 'scale', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Welche Note würdest du deinem Wissen darüber geben, wie KI funktioniert? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Wie sehr wünschst du dir einen Roboter, der zu Hause alles für dich erledigt? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Von 1 bis 10, wie sehr glaubst du, dass KI hilft, Krankheiten zu heilen?', 'scale', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Wie viel Angst hast du, dass KI alle Jobs übernimmt? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Wie wichtig findest du es, dass die Regierung die KI kontrolliert? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Von 1 bis 10, wie sehr glaubst du, dass Maschinen eines Tages etwas fühlen können?', 'scale', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Wer ist eher ein KI-Fan: {member_A} oder {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Wer hat mehr Angst vor der Zukunft der Technologie: {member_A} oder {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Wer nutzt in seinem Alltag mehr KI: {member_A} oder {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Wer würde sich zuerst mit einem Roboter anfreunden: {member_A} oder {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Wer ist kritischer gegenüber der ganzen KI-Sache: {member_A} oder {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Wer würde besser überleben, wenn es gar keine Technologie gäbe: {member_A} oder {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Wer würde eher darauf vertrauen, dass ein Roboter ihn operiert: {member_A} oder {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Wer wäre besser darin, einen Bot zu überlisten: {member_A} oder {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Wer würde zuerst vermuten, dass die Gruppe eine KI-Simulation ist: {member_A} oder {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Wer denkt, dass KI das Beste ist, was uns passiert ist: {member_A} oder {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'de', ARRAY['🤖']::text[], true),
('Ordne die Gruppe danach, wer am meisten an seinem Handy klebt.', 'ranking', 'ia_custom', NULL, false, 3, 'de', ARRAY['🤖']::text[], true),
('Klassifiziere die Gruppe nach ihrem Grad an KI-Optimismus.', 'ranking', 'ia_custom', NULL, false, 3, 'de', ARRAY['🤖']::text[], true),
('Ordne danach, wer KI zuerst zum Flirten benutzen würde.', 'ranking', 'ia_custom', NULL, false, 3, 'de', ARRAY['🤖']::text[], true),
('Klassifiziere die Gruppe danach, wer online am meisten auf seine Daten achtet.', 'ranking', 'ia_custom', NULL, false, 3, 'de', ARRAY['🤖']::text[], true),
('Ordne danach, wer zuerst ein fliegendes Auto kaufen würde.', 'ranking', 'ia_custom', NULL, false, 3, 'de', ARRAY['🤖']::text[], true),
('Klassifiziere die Gruppe danach, wer mehr Neugier auf die Zukunft hat.', 'ranking', 'ia_custom', NULL, false, 3, 'de', ARRAY['🤖']::text[], true),
('Ordne danach, wer denkt, dass KI die Welt in Ordnung bringen wird.', 'ranking', 'ia_custom', NULL, false, 3, 'de', ARRAY['🤖']::text[], true),
('Klassifiziere die Gruppe danach, wer sich am wahrscheinlichsten bei Alexa bedanken würde.', 'ranking', 'ia_custom', NULL, false, 3, 'de', ARRAY['🤖']::text[], true),
('Ordne danach, wer denkt, dass Roboter eine echte Gefahr sind.', 'ranking', 'ia_custom', NULL, false, 3, 'de', ARRAY['🤖']::text[], true),
('Klassifiziere die Gruppe danach, wer KI für das verrückteste Ding benutzt hat.', 'ranking', 'ia_custom', NULL, false, 3, 'de', ARRAY['🤖']::text[], true);
