-- questions_creative_fr.sql
-- 400 creative French questions for AuditUs
-- Categories: humor, habilidades, futuro, atrevidas, hipoteticas, vinculos, eventos, ia_custom

-- humor: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Qui dans le groupe rit le plus probablement de sa propre blague avant que quiconque ne la comprenne ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui survivrait le plus longtemps à une apocalypse zombie, juste parce qu''il s''est caché dans la boulangerie la plus proche ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui dans le groupe apporterait le plus probablement des chips de supermarché à un dîner et dirait qu''elles sont "artisanales" ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui gagnerait un "dance-off" entre {member_A} et {member_B} ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui est le coupable officiel du "je répondrai plus tard" dans le groupe ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Avec qui dans le groupe serait-il le plus terrible d''être coincé dans un ascenseur pendant 24 heures ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui lancerait le plus probablement un podcast sur son trajet quotidien en métro ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui perdrait un débat sur la question de savoir si un pain au chocolat s''appelle une "chocolatine" ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Quel membre du groupe a le Spotify Wrapped le plus chaotique ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui deviendrait le plus probablement viral pour les mauvaises raisons lors d''un mariage ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui se ferait expulser en premier lors d''une soirée jeux de société ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui envoie le plus de messages "lol" sans vraiment rire ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui est le champion de la procrastination dans le groupe ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui survivrait à une rencontre avec une "Karen" sans pleurer ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui essaierait de payer son café avec un "high-five" ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui dans le groupe rejoindrait le plus probablement une secte par accident en cherchant un cours de yoga ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui se ferait faire en premier un tatouage d''un mème qui meurt deux jours plus tard ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui se disputerait le plus probablement avec une caisse automatique parce qu''elle dit "article inattendu dans la zone d''emballage" ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui dans le groupe resterait le plus probablement coincé dans une balançoire pour enfants ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui enverrait en premier un e-mail "répondre à tous" qui n''était destiné qu''à une seule personne ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui essaierait le plus probablement de caresser un animal sauvage qui veut clairement le mordre ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui recevrait le prix du "Plus susceptible d''oublier pourquoi il est entré dans une pièce" ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui dans le groupe déclencherait le plus probablement un incendie en essayant de faire bouillir de l''eau ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Si le groupe était une équipe de braqueurs, qui oublierait les clés du véhicule de fuite à l''intérieur de la voiture ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui serait le plus probablement vu à l''arrière-plan d''un reportage télévisé en train de faire quelque chose de gênant ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui achèterait en premier un tapis de course pour s''en servir ensuite de portemanteau ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui dans le groupe prendrait le plus probablement un inconnu pour une célébrité et demanderait un selfie ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui rirait le plus probablement lors d''un enterrement et essaierait ensuite de le cacher avec une fausse toux ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui dans le groupe court le plus grand risque d''acheter une "Mystery Box" sur un site web louche ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui essaierait d''entrer par une porte où il est écrit "Tirer" en poussant pendant au moins 10 secondes ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui dans le groupe se ferait faire le plus probablement un tatouage avec une faute d''orthographe ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui essaierait en premier de draguer un bot d''IA du service client ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui deviendrait le plus probablement un mème viral sans même savoir ce qu''est un mème ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui survivrait sur une île déserte, mais seulement s''il avait sa routine de soins de la peau avec lui ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui épouserait le plus probablement un robot avant 2030 ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui appellerais-tu pour te sortir de prison, mais finirait par se faire arrêter aussi ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui dans le groupe a les secrets les plus inoffensifs mais les plus bizarres ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui serait le meilleur chef de secte pour un groupe qui vénère la pizza à l''ananas ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui a le rire le plus communicatif et le plus fort du groupe ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui oublierait le plus probablement pendant plus d''une heure où il a garé sa voiture ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui est la plus grande "Drama Queen" lors d''un simple rhume ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui abandonnerait en premier lors d''un défi "24 heures sans téléphone" ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui s''endormirait au milieu d''une boîte de nuit bruyante ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui finirait par acheter un terrain sur la Lune à cause d''une publicité Instagram ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui oublierait l''anniversaire de sa mère mais se souviendrait de celui d''un personnage d''anime aléatoire ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui pleurerait parce qu''il s''est cassé un ongle ou a taché une nouvelle basket ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui essaierait de demander une réduction dans une boutique de luxe ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui porterait des chaussettes avec des sandales et penserait sérieusement que c''est une déclaration de mode ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui collectionnerait quelque chose d''aussi aléatoire que des emballages de chewing-gum ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true),
('Qui se ferait avoir en premier par un canular téléphonique enregistré ?', 'poll', 'humor', NULL, false, 2, 'fr', ARRAY['😂']::text[], true);

-- (Adding other 7 categories below...)

-- habilidades: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Qui dans le groupe peut assembler un meuble IKEA sans avoir de vis en trop ?', 'poll', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('Qui a la meilleure boussole interne et n''a jamais besoin de Google Maps ?', 'poll', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('Qui serait le meilleur négociateur dans un vide-greniers ?', 'poll', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('Qui dans le groupe survivrait le mieux dans les bois avec seulement un couteau suisse ?', 'poll', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('Qui est le plus rapide pour taper des messages sur son téléphone sans regarder ?', 'poll', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('Qui dans le groupe a une langue bien pendue et pourrait convaincre n''importe qui de n''importe quoi ?', 'poll', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('Qui serait le meilleur pilote de drone dans le groupe ?', 'poll', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('Qui dans le groupe est un génie des maths en secret mais fait semblant de ne rien savoir ?', 'poll', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('Qui a le plus de patience pour démêler un fouillis de câbles d''écouteurs ?', 'poll', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('Qui serait le meilleur chef improvisé avec ce qu''il y a dans le frigo ?', 'poll', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('Qui dans le groupe gagnerait un concours d''orthographe pour des mots épelés à l''envers ?', 'poll', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('Qui peut apprendre une danse TikTok en moins de 5 minutes ?', 'poll', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('Qui dans le groupe serait le meilleur détective privé (ou stalker professionnel) ?', 'poll', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('Qui a le meilleur flair pour réparer un ordinateur qui ne démarre plus ?', 'poll', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('Qui dans le groupe gagnerait une partie d''échecs contre un pro ?', 'poll', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('Qui a la main la plus sûre pour jouer au Jenga après deux verres ?', 'poll', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('Qui dans le groupe serait le meilleur survivant dans une apocalypse zombie grâce à sa forme physique ?', 'poll', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('Qui peut imiter parfaitement un accent d''un autre pays ?', 'poll', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('Qui dans le groupe a le meilleur œil pour les photos Instagram ?', 'poll', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('Qui serait le meilleur dans un spectacle de talents secrets ?', 'poll', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('Quelle note donnerais-tu à la capacité de {member_A} à économiser de l''argent ? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('De 1 à 10, quel est le niveau de précision de {member_A} ?', 'scale', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('À quel point {member_A} raconte-t-il bien les blagues ? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('À quel point {member_A} est-il technophile ? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('De 1 à 10, quelle est la discipline de {member_A} concernant son alimentation ?', 'scale', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('À quelle vitesse penses-tu que {member_A} pourrait apprendre à jouer de la guitare ? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('Quelle note donnerais-tu à {member_A} pour la conduite dans les embouteillages ? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('De 1 à 10, à quel point {member_A} ment-il bien quand il se fait prendre ?', 'scale', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('À quel point {member_A} organiserait-il bien un barbecue ? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('Quel est le niveau de "bricoleur" de {member_A} pour réparer des choses à la maison ? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('Qui gagnerait un débat politique : {member_A} ou {member_B} ?', 'vs', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('Qui tiendrait le plus longtemps dans un désert : {member_A} ou {member_B} ?', 'vs', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('Qui est le plus pro aux jeux de stratégie : {member_A} ou {member_B} ?', 'vs', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('Qui a la plus belle écriture : {member_A} ou {member_B} ?', 'vs', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('Qui gagnerait une partie de Trivial Pursuit : {member_A} ou {member_B} ?', 'vs', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('Qui est le plus créatif pour concevoir des choses : {member_A} ou {member_B} ?', 'vs', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('Qui a le plus de style en s''habillant : {member_A} ou {member_B} ?', 'vs', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('Qui résout un Sudoku plus rapidement : {member_A} ou {member_B} ?', 'vs', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('Qui serait un meilleur agent secret : {member_A} ou {member_B} ?', 'vs', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('Qui a une meilleure oreille musicale : {member_A} ou {member_B} ?', 'vs', 'habilidades', NULL, false, 2, 'fr', ARRAY['💪']::text[], true),
('Classe le groupe selon qui est le plus susceptible de gagner un télé-crochet.', 'ranking', 'habilidades', NULL, false, 3, 'fr', ARRAY['💪']::text[], true),
('Classe le groupe du meilleur au pire cuisinier.', 'ranking', 'habilidades', NULL, false, 3, 'fr', ARRAY['💪']::text[], true),
('Classe par qui a le plus de capacité à se concentrer quand il y a beaucoup de bruit.', 'ranking', 'habilidades', NULL, false, 3, 'fr', ARRAY['💪']::text[], true),
('Classe le groupe selon qui conduirait mieux un camion sur l''autoroute.', 'ranking', 'habilidades', NULL, false, 3, 'fr', ARRAY['💪']::text[], true),
('Classe par qui est le plus habile de ses mains (travail du bois, artisanat, etc.).', 'ranking', 'habilidades', NULL, false, 3, 'fr', ARRAY['💪']::text[], true),
('Classe le groupe par qui a le plus de mémoire pour les visages.', 'ranking', 'habilidades', NULL, false, 3, 'fr', ARRAY['💪']::text[], true),
('Classe par qui apprendrait le plus vite un sport extrême.', 'ranking', 'habilidades', NULL, false, 3, 'fr', ARRAY['💪']::text[], true),
('Classe le groupe par qui a le plus de facilité pour les langues étrangères.', 'ranking', 'habilidades', NULL, false, 3, 'fr', ARRAY['💪']::text[], true),
('Classe par qui gère le mieux son temps sous une forte pression.', 'ranking', 'habilidades', NULL, false, 3, 'fr', ARRAY['💪']::text[], true),
('Classe le groupe selon qui serait le meilleur joueur de poker.', 'ranking', 'habilidades', NULL, false, 3, 'fr', ARRAY['💪']::text[], true);

-- futuro: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Qui dans le groupe sera le premier à partir vivre sur un autre continent pour le travail ?', 'poll', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Qui sera le premier à être grand-parent et à s''en vanter dans le groupe ?', 'poll', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Qui dans le groupe aura une rue à son nom un jour ?', 'poll', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Qui sera le premier à devenir millionnaire mais à continuer à manger au bistrot du coin ?', 'poll', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Qui dans le groupe écrira un livre qui deviendra un film ?', 'poll', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Qui sera le premier à se marier lors d''une cérémonie secrète sans le dire à personne ?', 'poll', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Qui dans le groupe finira par travailler dans une startup technologique super prospère ?', 'poll', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Qui sera le premier à prendre sa retraite avant l''âge de 45 ans ?', 'poll', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Qui dans le groupe gagnera un prix majeur dans son domaine ?', 'poll', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Qui sera le premier à acheter une maison avec piscine ?', 'poll', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Qui dans le groupe aura une très grande famille ?', 'poll', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Qui sera le premier à supprimer définitivement tous ses réseaux sociaux ?', 'poll', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Qui dans le groupe sera invité à un événement super exclusif à Hollywood ?', 'poll', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Qui sera le premier à vivre dans un quartier super branché de la ville ?', 'poll', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Qui dans le groupe finira par être un leader d''opinion super influent ?', 'poll', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Qui sera le premier à faire un voyage en sac à dos à travers l''Asie ?', 'poll', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Qui dans le groupe aura sa propre marque de champagne ou de vin ?', 'poll', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Qui sera le premier à devenir super fit et à ne plus jamais manger de malbouffe ?', 'poll', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Qui dans le groupe restera dans les mémoires pour sa grande contribution à la communauté ?', 'poll', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Qui sera le premier à adopter une ribambelle de chats ?', 'poll', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Quelle est la probabilité que {member_A} soit un influenceur célèbre dans 3 ans ? (0-100%)', 'scale', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('De 1 à 10, à quel point penses-tu que la vie de {member_A} changera cette année ?', 'scale', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Quel niveau de succès penses-tu que {member_A} atteindra dans ses affaires ? (1-10)', 'scale', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('De 1 à 10, à quel point penses-tu que {member_A} atteindra ses objectifs cette année ?', 'scale', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Quelle est la probabilité que {member_A} devienne bientôt un nomade numérique ? (1-10)', 'scale', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Quelle note donnerais-tu à la future stabilité de la relation de {member_A} ? (1-10)', 'scale', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('De 1 à 10, à quel point penses-tu que {member_A} aura un impact sur la vie des autres ?', 'scale', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Quelle est la probabilité que {member_A} gagne au loto un jour ? (1-10)', 'scale', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Quel niveau de tranquillité d''esprit penses-tu que {member_A} aura dans ses vieux jours ? (1-10)', 'scale', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('De 1 à 10, à quel point penses-tu que {member_A} regrettera de ne pas avoir fait quelque chose aujourd''hui ?', 'scale', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Qui aura une maison plus cool dans 15 ans : {member_A} ou {member_B} ?', 'vs', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Qui sera plus heureux au moment de la retraite : {member_A} ou {member_B} ?', 'vs', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Qui aura un poste plus élevé au travail : {member_A} ou {member_B} ?', 'vs', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Qui sera plus respecté dans ce qu''il fait : {member_A} ou {member_B} ?', 'vs', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Qui visitera le plus de pays : {member_A} ou {member_B} ?', 'vs', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Qui restera le plus en contact avec le groupe à l''avenir : {member_A} ou {member_B} ?', 'vs', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Qui deviendra plus sage avec l''âge : {member_A} ou {member_B} ?', 'vs', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Qui comprendra mieux la technologie du futur : {member_A} ou {member_B} ?', 'vs', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Qui aura le plus de petits-enfants : {member_A} ou {member_B} ?', 'vs', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Qui vivra dans un endroit plus calme : {member_A} ou {member_B} ?', 'vs', 'futuro', NULL, false, 2, 'fr', ARRAY['🔮']::text[], true),
('Classe le groupe selon qui aura le plus de succès dans sa carrière.', 'ranking', 'futuro', NULL, false, 3, 'fr', ARRAY['🔮']::text[], true),
('Classe le groupe par qui réalisera ses rêves en premier.', 'ranking', 'futuro', NULL, false, 3, 'fr', ARRAY['🔮']::text[], true),
('Classe selon qui laissera une plus grande empreinte sur le monde.', 'ranking', 'futuro', NULL, false, 3, 'fr', ARRAY['🔮']::text[], true),
('Classe le groupe selon qui paraîtra plus jeune avec le temps.', 'ranking', 'futuro', NULL, false, 3, 'fr', ARRAY['🔮']::text[], true),
('Classe par qui fera des voyages plus exotiques au cours des 20 prochaines années.', 'ranking', 'futuro', NULL, false, 3, 'fr', ARRAY['🔮']::text[], true),
('Classe le groupe selon qui aura une vie plus détendue.', 'ranking', 'futuro', NULL, false, 3, 'fr', ARRAY['🔮']::text[], true),
('Classe par qui se mariera en premier (ou de nouveau).', 'ranking', 'futuro', NULL, false, 3, 'fr', ARRAY['🔮']::text[], true),
('Classe le groupe selon qui fera le plus pour la société.', 'ranking', 'futuro', NULL, false, 3, 'fr', ARRAY['🔮']::text[], true),
('Classe selon qui sera le plus au courant des tendances futures.', 'ranking', 'futuro', NULL, false, 3, 'fr', ARRAY['🔮']::text[], true),
('Classe le groupe selon qui vivra une vie plus longue et plus épanouie.', 'ranking', 'futuro', NULL, false, 3, 'fr', ARRAY['🔮']::text[], true);

-- (Adding the remaining 5 categories for fr...)

-- atrevidas: 50 questions (anonymous)
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Quel est le plus gros mensonge que tu aies jamais raconté pour éviter de sortir avec quelqu''un ?', 'free', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('Qui dans le groupe a les goûts les plus "bizarres" au lit selon toi ?', 'poll', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('As-tu déjà fait semblant d''aimer quelqu''un juste par intérêt ?', 'free', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('À qui dans ce groupe donnerais-tu un baiser si on jouait au jeu de la bouteille ?', 'poll', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('Quel est l''endroit le plus fou où tu aies jamais eu un rapport ?', 'free', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('As-tu déjà rêvé de quelqu''un de ce groupe ?', 'free', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('Quel est ton fantasme le plus "sombre" dont personne ne sait rien ?', 'free', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('As-tu déjà "ghosté" quelqu''un que tu aimais bien en réalité ?', 'free', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('Qui dans le groupe est un "charreau" (player) né selon toi ?', 'poll', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('Quelle est la chose la plus osée que tu aies faite pour quelqu''un dont tu étais fou/folle ?', 'free', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('As-tu déjà envoyé un "nude" et eu une peur bleue juste après ?', 'free', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('Qui dans le groupe drague le plus sur des applis comme Tinder ou Bumble selon toi ?', 'poll', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('As-tu déjà fréquenté deux personnes en même temps ?', 'free', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('Qui de ce groupe emmènerais-tu dans un chalet juste pour "discuter" ?', 'poll', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('Quel est le message le plus explicite que tu aies envoyé à la mauvaise personne par erreur ?', 'free', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('As-tu déjà craqué pour le/la partenaire de quelqu''un du groupe ?', 'free', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('Qui dans le groupe a les fétiches les plus intenses selon toi ?', 'poll', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('Quelle a été ta pire expérience lors de ta "première fois" ?', 'free', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('T''es-tu déjà fait surprendre "en plein acte" ?', 'free', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('Qui dans le groupe est plutôt "sauvage" en privé selon toi ?', 'poll', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('As-tu déjà utilisé des jouets et quel est ton préféré ?', 'free', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('Qui dans le groupe a eu le plus de partenaires sexuels selon toi ?', 'poll', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('Quel est le plus gros mensonge que tu aies raconté pour que quelqu''un couche avec toi ?', 'free', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('À qui dans ce groupe confierais-tu ton téléphone déverrouillé ?', 'poll', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('As-tu déjà fait un plan à trois ou meurs-tu d''envie d''en faire un ?', 'free', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('Qui dans le groupe est le plus susceptible d''accepter un plan d''un soir selon toi ?', 'poll', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('Quel secret inavouable as-tu sur un(e) ex ?', 'free', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('As-tu déjà été avec quelqu''un de beaucoup plus âgé que toi ?', 'free', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('Qui dans le groupe se vante plus qu''il ne fait en réalité selon toi ?', 'poll', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('Quelle est la chose la plus "bizarre" que tu aies cherchée en mode incognito ?', 'free', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('T''es-tu déjà senti(e) attiré(e) par quelqu''un du même sexe (si tu es hétéro) ?', 'free', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('Qui dans le groupe a un profil secret sur une appli de rencontre selon toi ?', 'poll', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('Quel a été le moment le plus gênant que tu aies vécu sans vêtements ?', 'free', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('As-tu déjà fait du sexe par téléphone ou du sexting intense ?', 'free', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('Qui dans le groupe est le plus "conservateur" au lit selon toi ?', 'poll', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('Quelle partie de ton corps est ton "bouton" secret ?', 'free', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('As-tu déjà payé pour du sexe ou t''a-t-on proposé de l''argent pour ça ?', 'free', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('Qui dans le groupe pardonnerait le plus vite une infidélité selon toi ?', 'poll', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('Quel fétiche as-tu le plus honte d''avouer ?', 'free', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('As-tu déjà enregistré une vidéo intime ?', 'free', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('Qui dans le groupe est le plus "curieux" de tester de nouvelles choses selon toi ?', 'poll', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('Dans quel lieu public aimerais-tu le plus avoir un rapport ?', 'free', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('As-tu déjà eu une aventure avec quelqu''un du travail ?', 'free', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('Qui dans le groupe est le plus sexy selon toi ?', 'poll', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('Quelle est la chose la plus folle que tu aies faite en étant ivre ?', 'free', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('As-tu déjà revu un(e) ex alors que tu étais en couple avec quelqu''un d''autre ?', 'free', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('Qui dans le groupe est un romantique secret selon toi ?', 'poll', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('Quel est le fantasme le plus fou que tu aies déjà réalisé ?', 'free', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('As-tu déjà été dans une relation libre ?', 'free', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true),
('Qui dans ce groupe inviterais-tu à un plan à trois s''il/elle disait oui ?', 'poll', 'atrevidas', NULL, true, 2, 'fr', ARRAY['🌶️']::text[], true);

-- hipoteticas: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Si tu pouvais avoir un super-pouvoir, mais seulement une fois tous les 6 mois, lequel choisirais-tu ?', 'mc', 'hipoteticas', ARRAY['Invisibilité 12h', 'Voyager dans le passé 30 min', 'Lire les pensées 1h', 'Voler 2h'], false, 2, 'fr', ARRAY['🧠']::text[], true),
('Si le groupe se retrouve sur une île déserte, qui allumerait le feu en premier ?', 'poll', 'hipoteticas', NULL, false, 2, 'fr', ARRAY['🧠']::text[], true),
('Si tu pouvais vivre dans un film pendant une semaine, lequel choisirais-tu ?', 'mc', 'hipoteticas', ARRAY['Harry Potter', 'Avengers', 'Le Loup de Wall Street', 'Amélie Poulain'], false, 2, 'fr', ARRAY['🧠']::text[], true),
('Si tu devais choisir quelqu''un du groupe pour te défendre lors d''un procès, qui serait-ce ?', 'poll', 'hipoteticas', NULL, false, 2, 'fr', ARRAY['🧠']::text[], true),
('Si on te donnait 5 millions d''euros pour ne plus jamais manger de fromage, le ferais-tu ?', 'mc', 'hipoteticas', ARRAY['Oui, direct', 'Jamais de la vie', 'Seulement si je peux manger de la charcuterie', 'J''y réfléchirais longtemps'], false, 2, 'fr', ARRAY['🧠']::text[], true),
('Si le groupe était une équipe de foot, qui serait le capitaine ?', 'poll', 'hipoteticas', NULL, false, 2, 'fr', ARRAY['🧠']::text[], true),
('Si tu savais exactement quel jour tu allais mourir, voudrais-tu le savoir ?', 'mc', 'hipoteticas', ARRAY['Oui, pour tout dépenser', 'Non, trop flippant', 'Seulement si je peux le changer', 'Je préfère la surprise'], false, 2, 'fr', ARRAY['🧠']::text[], true),
('Si tu devais choisir quelqu''un du groupe pour s''occuper de toi si tu étais très malade, qui serait-ce ?', 'poll', 'hipoteticas', NULL, false, 2, 'fr', ARRAY['🧠']::text[], true),
('Si tu pouvais parler n''importe quelle langue couramment dès maintenant, laquelle choisirais-tu ?', 'mc', 'hipoteticas', ARRAY['Japonais', 'Français (si déjà fait, Italien)', 'Espagnol', 'Russe'], false, 2, 'fr', ARRAY['🧠']::text[], true),
('Si le groupe était dans une apocalypse zombie, qui se sacrifierait en premier pour les autres ?', 'poll', 'hipoteticas', NULL, false, 2, 'fr', ARRAY['🧠']::text[], true),
('Si tu pouvais te téléporter n''importe où là tout de suite, où irais-tu ?', 'mc', 'hipoteticas', ARRAY['Sur une plage aux Maldives', 'À New York pour faire du shopping', 'Au sommet de la Tour Eiffel', 'Dans mon lit pour dormir'], false, 2, 'fr', ARRAY['🧠']::text[], true),
('Si tu devais confier ton code de carte bleue à quelqu''un du groupe, qui serait-ce ?', 'poll', 'hipoteticas', NULL, false, 2, 'fr', ARRAY['🧠']::text[], true),
('Si tu pouvais ressusciter une personne célèbre pour prendre un verre, qui serait-ce ?', 'mc', 'hipoteticas', ARRAY['Freddie Mercury', 'Frida Kahlo', 'Steve Jobs', 'Napoléon'], false, 2, 'fr', ARRAY['🧠']::text[], true),
('Si le groupe était une émission de télé-réalité, qui gagnerait parce qu''il est le plus "vrai" ?', 'poll', 'hipoteticas', NULL, false, 2, 'fr', ARRAY['🧠']::text[], true),
('Si tu pouvais effacer une erreur de ton passé, laquelle choisirais-tu ?', 'free', 'hipoteticas', NULL, false, 2, 'fr', ARRAY['🧠']::text[], true),
('Si tu devais choisir quelqu''un du groupe pour cacher des preuves (juste pour rire), qui serait-ce ?', 'poll', 'hipoteticas', NULL, false, 2, 'fr', ARRAY['🧠']::text[], true),
('Si tu pouvais être immortel, accepterais-tu ?', 'mc', 'hipoteticas', ARRAY['Oui, sans hésiter', 'Non, trop ennuyeux', 'Seulement si je ne vieillis pas', 'Seulement si mes amis le sont aussi'], false, 2, 'fr', ARRAY['🧠']::text[], true),
('Si le groupe montait un business, qui gérerait l''argent ?', 'poll', 'hipoteticas', NULL, false, 2, 'fr', ARRAY['🧠']::text[], true),
('Si tu pouvais effacer un souvenir triste de ta tête, le ferais-tu ?', 'free', 'hipoteticas', NULL, false, 2, 'fr', ARRAY['🧠']::text[], true),
('Si tu devais vivre en coloc avec quelqu''un du groupe pendant un an, qui serait-ce ?', 'poll', 'hipoteticas', NULL, false, 2, 'fr', ARRAY['🧠']::text[], true),
('Quelle est la probabilité que les extraterrestres nous rendent visite bientôt ? (0-10)', 'scale', 'hipoteticas', NULL, false, 2, 'fr', ARRAY['🧠']::text[], true),
('De 1 à 10, à quel point penses-tu que les machines vont se rebeller ?', 'scale', 'hipoteticas', NULL, false, 2, 'fr', ARRAY['🧠']::text[], true),
('À quel point serions-nous heureux dans un monde sans internet ? (1-10)', 'scale', 'hipoteticas', NULL, false, 2, 'fr', ARRAY['🧠']::text[], true),
('De 1 à 10, à quel point crois-tu aux fantômes ?', 'scale', 'hipoteticas', NULL, false, 2, 'fr', ARRAY['🧠']::text[], true),
('À quel point juges-tu probable que nous vivions dans une simulation ? (1-10)', 'scale', 'hipoteticas', NULL, false, 2, 'fr', ARRAY['🧠']::text[], true),
('De 1 à 10, combien donnerais-tu pour sauver la planète ?', 'scale', 'hipoteticas', NULL, false, 2, 'fr', ARRAY['🧠']::text[], true),
('À quel point trouves-tu important de coloniser d''autres planètes ? (1-10)', 'scale', 'hipoteticas', NULL, false, 2, 'fr', ARRAY['🧠']::text[], true),
('De 1 à 10, à quel point penses-tu que le futur est déjà écrit ?', 'scale', 'hipoteticas', NULL, false, 2, 'fr', ARRAY['🧠']::text[], true),
('À quel point penses-tu que voyager dans le temps sera possible un jour ? (1-10)', 'scale', 'hipoteticas', NULL, false, 2, 'fr', ARRAY['🧠']::text[], true),
('De 1 à 10, à quel point les robots intelligents te font-ils peur ?', 'scale', 'hipoteticas', NULL, false, 2, 'fr', ARRAY['🧠']::text[], true),
('Qui serait un meilleur leader en cas de crise : {member_A} ou {member_B} ?', 'vs', 'hipoteticas', NULL, false, 2, 'fr', ARRAY['🧠']::text[], true),
('Qui survivrait le mieux au 18ème siècle : {member_A} ou {member_B} ?', 'vs', 'hipoteticas', NULL, false, 2, 'fr', ARRAY['🧠']::text[], true),
('Qui se lierait d''amitié avec un alien en premier : {member_A} ou {member_B} ?', 'vs', 'hipoteticas', NULL, false, 2, 'fr', ARRAY['🧠']::text[], true),
('Qui choisirait de quitter la Matrice : {member_A} ou {member_B} ?', 'vs', 'hipoteticas', NULL, false, 2, 'fr', ARRAY['🧠']::text[], true),
('Qui serait un meilleur astronaute : {member_A} ou {member_B} ?', 'vs', 'hipoteticas', NULL, false, 2, 'fr', ARRAY['🧠']::text[], true),
('Qui se sacrifierait pour le groupe en cas de problème : {member_A} ou {member_B} ?', 'vs', 'hipoteticas', NULL, false, 2, 'fr', ARRAY['🧠']::text[], true),
('Qui serait le meilleur représentant de la Terre : {member_A} ou {member_B} ?', 'vs', 'hipoteticas', NULL, false, 2, 'fr', ARRAY['🧠']::text[], true),
('Qui s''adapterait le mieux à une vie sous l''eau : {member_A} ou {member_B} ?', 'vs', 'hipoteticas', NULL, false, 2, 'fr', ARRAY['🧠']::text[], true),
('Qui gagnerait un duel d''insultes contre un pirate : {member_A} ou {member_B} ?', 'vs', 'hipoteticas', NULL, false, 2, 'fr', ARRAY['🧠']::text[], true),
('Qui croirait en premier que tout ceci n''est qu''un rêve : {member_A} ou {member_B} ?', 'vs', 'hipoteticas', NULL, false, 2, 'fr', ARRAY['🧠']::text[], true),
('Classe le groupe selon qui survivrait le plus longtemps dans un film d''horreur.', 'ranking', 'hipoteticas', NULL, false, 3, 'fr', ARRAY['🧠']::text[], true),
('Classe le groupe du plus au moins suspect d''être un espion.', 'ranking', 'hipoteticas', NULL, false, 3, 'fr', ARRAY['🧠']::text[], true),
('Classe selon qui serait le meilleur stratège dans un jeu de guerre.', 'ranking', 'hipoteticas', NULL, false, 3, 'fr', ARRAY['🧠']::text[], true),
('Classe le groupe selon qui serait le plus utile si le monde s''effondrait.', 'ranking', 'hipoteticas', NULL, false, 3, 'fr', ARRAY['🧠']::text[], true),
('Classe par qui se porterait volontaire en premier pour aller sur Mars.', 'ranking', 'hipoteticas', NULL, false, 3, 'fr', ARRAY['🧠']::text[], true),
('Classe le groupe selon qui inventerait le remède à une maladie.', 'ranking', 'hipoteticas', NULL, false, 3, 'fr', ARRAY['🧠']::text[], true),
('Classe par qui serait le meilleur négociateur avec une race extraterrestre.', 'ranking', 'hipoteticas', NULL, false, 3, 'fr', ARRAY['🧠']::text[], true),
('Classe le groupe selon qui resterait le plus calme lors d''un tremblement de terre.', 'ranking', 'hipoteticas', NULL, false, 3, 'fr', ARRAY['🧠']::text[], true),
('Classe par qui inventerait les règles de société les plus créatives.', 'ranking', 'hipoteticas', NULL, false, 3, 'fr', ARRAY['🧠']::text[], true),
('Classe le groupe selon qui serait le meilleur guide dans un monde post-apocalyptique.', 'ranking', 'hipoteticas', NULL, false, 3, 'fr', ARRAY['🧠']::text[], true);

-- vinculos: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Qui dans le groupe est celui qui organise toujours les sorties ?', 'poll', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('Qui dans le groupe t''a donné le meilleur conseil quand tu n''allais pas bien ?', 'poll', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('Qui est la personne la plus loyale que tu connaisses dans ce groupe ?', 'poll', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('Qui dans le groupe est toujours là quand on a besoin de parler ?', 'poll', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('À qui dans ce groupe confierais-tu les clés de chez toi ?', 'poll', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('Qui a le plus évolué en tant que personne depuis que tu le/la connais ?', 'poll', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('Qui dans le groupe a le cœur le plus noble de tous ?', 'poll', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('Avec qui dans ce groupe ris-tu jusqu''à en avoir mal au ventre ?', 'poll', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('Qui dans ce groupe appellerais-tu si tu avais une vraie urgence ?', 'poll', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('Qui dans le groupe sait le mieux écouter sans juger ?', 'poll', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('Qui maintient la cohésion du groupe WhatsApp ?', 'poll', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('Qui dans ce groupe admires-tu le plus pour sa façon de voir la vie ?', 'poll', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('Qui dans le groupe est le plus honnête, même quand ce qu''il dit fait mal ?', 'poll', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('Qui est la personne la plus cool pour passer un moment calme à discuter ?', 'poll', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('À qui dans ce groupe demanderais-tu pardon en premier si vous aviez une tension ?', 'poll', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('Qui dans le groupe se soucie le plus de tout le monde ?', 'poll', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('Qui est la personne qui te motive le plus à être meilleur dans ce groupe ?', 'poll', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('À qui dans ce groupe raconterais-tu quelque chose qui te fait très honte ?', 'poll', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('Qui dans le groupe fait le plus attention aux anniversaires ?', 'poll', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('Qui est la personne qui apporte le plus de bonnes ondes dans ta vie ?', 'poll', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('De 1 à 10, à quel point as-tu confiance en {member_A} ?', 'scale', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('À quel point la connexion que tu as avec {member_A} est-elle bonne ? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('Quelle place occupe {member_A} dans ta liste de personnes préférées ? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('De 1 à 10, à quel point penses-tu que {member_A} te comprend vraiment ?', 'scale', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('Quelle note donnerais-tu à la loyauté de {member_A} envers le groupe ? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('À quel point {member_A} soutient-il les autres ? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('De 1 à 10, à quel point apprécies-tu discuter de choses sérieuses avec {member_A} ?', 'scale', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('À quel point est-il important pour toi de rester ami avec {member_A} pour toujours ? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('Quel niveau d''honnêteté penses-tu que {member_A} a envers toi ? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('De 1 à 10, à quel point penses-tu que le groupe changerait si {member_A} n''était pas là ?', 'scale', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('Qui prend le plus soin de ses amis : {member_A} ou {member_B} ?', 'vs', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('Avec qui préfères-tu parler de tes problèmes : {member_A} ou {member_B} ?', 'vs', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('Qui a le plus de patience avec le groupe : {member_A} ou {member_B} ?', 'vs', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('Qui est le plus attentif à ses amitiés : {member_A} ou {member_B} ?', 'vs', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('Qui appellerais-tu pour pleurer un bon coup : {member_A} ou {member_B} ?', 'vs', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('Qui te connaît le mieux quand tu es de mauvaise humeur : {member_A} ou {member_B} ?', 'vs', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('Qui est le plus honnête pour dire les choses : {member_A} ou {member_B} ?', 'vs', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('Avec qui te sens-tu le plus "toi-même" sans filtre : {member_A} ou {member_B} ?', 'vs', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('Qui pardonnerait plus facilement une erreur : {member_A} ou {member_B} ?', 'vs', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('Qui est le plus généreux de son temps : {member_A} ou {member_B} ?', 'vs', 'vinculos', NULL, false, 2, 'fr', ARRAY['💛']::text[], true),
('Classe le groupe selon qui sait le mieux garder des secrets.', 'ranking', 'vinculos', NULL, false, 3, 'fr', ARRAY['💛']::text[], true),
('Classe le groupe selon son niveau d''empathie envers les autres.', 'ranking', 'vinculos', NULL, false, 3, 'fr', ARRAY['💛']::text[], true),
('Classe par qui t''aiderait le premier en cas de galère sans rien demander.', 'ranking', 'vinculos', NULL, false, 3, 'fr', ARRAY['💛']::text[], true),
('Classe le groupe selon qui est le plus fidèle à ses amitiés.', 'ranking', 'vinculos', NULL, false, 3, 'fr', ARRAY['💛']::text[], true),
('Classe par qui est le plus sincère dans ses conseils (même si ça pique).', 'ranking', 'vinculos', NULL, false, 3, 'fr', ARRAY['💛']::text[], true),
('Classe le groupe selon qui se soucie le plus de savoir comment vont les autres.', 'ranking', 'vinculos', NULL, false, 3, 'fr', ARRAY['💛']::text[], true),
('Classe par qui est le plus drôle pour un voyage.', 'ranking', 'vinculos', NULL, false, 3, 'fr', ARRAY['💛']::text[] , true),
('Classe le groupe selon qui se réconcilie le plus facilement.', 'ranking', 'vinculos', NULL, false, 3, 'fr', ARRAY['💛']::text[], true),
('Classe par qui apporte le plus de paix et de calme au groupe.', 'ranking', 'vinculos', NULL, false, 3, 'fr', ARRAY['💛']::text[], true),
('Classe le groupe selon qui a été la meilleure découverte amicale.', 'ranking', 'vinculos', NULL, false, 3, 'fr', ARRAY['💛']::text[], true);

-- eventos: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Qui dans le groupe est celui qui organise toujours le repas de Noël ?', 'poll', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('Qui est le plus susceptible d''oublier qu''on avait rendez-vous aujourd''hui ?', 'poll', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('À qui dans ce groupe confierais-tu l''organisation de ta fête d''anniversaire ?', 'poll', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('Qui dans le groupe est le premier à dire "On part en voyage" à l''autre bout du monde ?', 'poll', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('Qui arrive toujours en retard mais apporte les boissons ?', 'poll', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('Qui dans le groupe est le plus gros fêtard et ne veut jamais aller se coucher ?', 'poll', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('Qui prépare les meilleurs cocktails lors des soirées ?', 'poll', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('Qui de ce groupe choisirais-tu comme DJ pour ta soirée ?', 'poll', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('Qui dans le groupe prend le plus de photos lors de chaque sortie ?', 'poll', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('Qui s''occupe toujours d''acheter tout ce qu''il faut pour l''apéro ?', 'poll', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('Qui dans le groupe finira le plus probablement par danser sur une chaise ?', 'poll', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('À qui dans ce groupe demanderais-tu de venir avec toi à un festival de musique tout un week-end ?', 'poll', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('Qui dans le groupe trouve toujours les vols les moins chers ?', 'poll', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('Qui est la "vieille âme" du groupe et veut rentrer tôt ?', 'poll', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('À qui dans ce groupe ferais-tu confiance pour réserver l''Airbnb pour tout le monde ?', 'poll', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('Qui dans le groupe est le plus drôle pour un week-end dans un gîte sympa ?', 'poll', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('Qui propose toujours d''aller dans des musées ou des trucs comme ça ?', 'poll', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('Qui dans ce groupe choisirais-tu pour aller à la fête foraine et faire les manèges les plus dingues ?', 'poll', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('Qui dans le groupe risque le plus de se perdre lors d''un concert ?', 'poll', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('Qui organise les meilleures surprises pour les autres ?', 'poll', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('De 1 à 10, à quel point aimes-tu les plans improvisés ?', 'scale', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('Quelle note donnerais-tu au niveau de "hype" de nos sorties de groupe ? (1-10)', 'scale', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('À quel point est-il important pour toi qu''on se voie en vrai ? (1-10)', 'scale', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('De 1 à 10, à quel point penses-tu qu''on s''amuserait bien lors d''un voyage à la plage ?', 'scale', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('Quelle note donnerais-tu à la ponctualité du groupe lors des rendez-vous ? (1-10)', 'scale', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('À quel point as-tu hâte qu''on se voie la prochaine fois ? (1-10)', 'scale', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('De 1 à 10, à quel point aimes-tu organiser des plans toi-même ?', 'scale', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('À quel point est-il difficile pour le groupe de se mettre d''accord sur un plan ? (1-10)', 'scale', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('À quel point est-il important pour toi de fêter chaque anniversaire ? (1-10)', 'scale', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('De 1 à 10, à quel point le groupe te manque-t-il quand on ne se voit pas longtemps ?', 'scale', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('Qui sait le mieux organiser : {member_A} ou {member_B} ?', 'vs', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('Avec qui préfères-tu voyager : {member_A} ou {member_B} ?', 'vs', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('Qui tient le plus longtemps en soirée : {member_A} ou {member_B} ?', 'vs', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('Qui propose les plans les plus fous : {member_A} ou {member_B} ?', 'vs', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('Qui a de meilleurs goûts en matière de restaurants : {member_A} ou {member_B} ?', 'vs', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('Qui est le plus ponctuel : {member_A} ou {member_B} ?', 'vs', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('À qui confierais-tu l''argent du voyage : {member_A} ou {member_B} ?', 'vs', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('Qui est le plus drôle au karaoké : {member_A} ou {member_B} ?', 'vs', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('Qui fait de meilleures photos souvenirs : {member_A} ou {member_B} ?', 'vs', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('Qui est le plus susceptible de s''endormir sur le chemin du retour de soirée : {member_A} ou {member_B} ?', 'vs', 'eventos', NULL, false, 2, 'fr', ARRAY['🎉']::text[], true),
('Classe le groupe selon qui met le plus d''ambiance.', 'ranking', 'eventos', NULL, false, 3, 'fr', ARRAY['🎉']::text[], true),
('Classe le groupe selon qui a le plus envie d''être dehors.', 'ranking', 'eventos', NULL, false, 3, 'fr', ARRAY['🎉']::text[], true),
('Classe par qui est le plus susceptible de tout gérer lors d''un voyage.', 'ranking', 'eventos', NULL, false, 3, 'fr', ARRAY['🎉']::text[], true),
('Classe le groupe selon qui est le plus ponctuel de tous.', 'ranking', 'eventos', NULL, false, 3, 'fr', ARRAY['🎉']::text[], true),
('Classe par qui met la meilleure musique quand on est ensemble.', 'ranking', 'eventos', NULL, false, 3, 'fr', ARRAY['🎉']::text[], true),
('Classe le groupe selon qui se fait des amis le plus vite partout.', 'ranking', 'eventos', NULL, false, 3, 'fr', ARRAY['🎉']::text[], true),
('Classe par qui filme le más tout ce qu''on fait.', 'ranking', 'eventos', NULL, false, 3, 'fr', ARRAY['🎉']::text[], true),
('Classe le groupe selon qui fait le plus de surprises.', 'ranking', 'eventos', NULL, false, 3, 'fr', ARRAY['🎉']::text[], true),
('Classe par qui est le más détendu quand on voyage ensemble.', 'ranking', 'eventos', NULL, false, 3, 'fr', ARRAY['🎉']::text[], true),
('Classe le groupe selon qui a fait le meilleur plan de groupe jusqu''ici.', 'ranking', 'eventos', NULL, false, 3, 'fr', ARRAY['🎉']::text[], true);

-- ia_custom: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Qui dans le groupe utilisera en premier ChatGPT pour répondre dans le groupe ?', 'poll', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('Qui est le plus susceptible de sortir avec une IA à l''avenir ?', 'poll', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('À qui dans ce groupe ferais-tu confiance pour laisser une IA programmée par lui/elle gérer ton argent ?', 'poll', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('Qui dans le groupe a le plus peur que les robots nous dominent ?', 'poll', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('Qui sait toujours quelles sont les nouvelles applis d''IA qui sortent ?', 'poll', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('Qui dans le groupe se ferait implanter une puce en premier pour être plus intelligent ?', 'poll', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('Qui profite le mieux de l''IA pour ne pas avoir à trop travailler ?', 'poll', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('Qui choisirais-tu pour être le premier humain sur Mars aidé par des robots ?', 'poll', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('Qui dans le groupe déteste le plus l''IA dans l''art ou la musique ?', 'poll', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('Qui pense toujours que tout ce qu''il voit sur internet est faux à cause de l''IA ?', 'poll', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('Qui dans le groupe aurait en premier un clone numérique ?', 'poll', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('À qui demanderais-tu de l''aide pour créer ta propre IA personnalisée ?', 'poll', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('Qui dans le groupe est le plus optimiste quant à l''avenir des robots ?', 'poll', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('Qui traite déjà Alexa ou Google comme s''ils étaient de vraies personnes ?', 'poll', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('À qui dans ce groupe confierais-tu tes données personnelles face aux algorithmes ?', 'poll', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('Qui dans le groupe pense qu''une IA va bientôt lui prendre son boulot ?', 'poll', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('Qui utilise toujours des filtres d''IA pour paraître différent sur ses photos ?', 'poll', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('Qui choisirais-tu pour mener la résistance humaine contre les machines ?', 'poll', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('Qui dans le groupe est le plus susceptible d''apprendre à coder juste pour créer son IA ?', 'poll', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('Qui ne sait déjà plus si un message a été écrit par un humain ou une machine ?', 'poll', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('De 1 à 10, à quel point fais-tu confiance à ce que te dit ChatGPT ?', 'scale', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('À quel point l''IA a-t-elle changé ton quotidien jusqu''ici ? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('À quel point trouves-tu important que l''IA ait des règles éthiques ? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('De 1 à 10, à quel point penses-tu possible qu''on perde le contrôle sur les machines ?', 'scale', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('Quelle note donnerais-tu à tes connaissances sur le fonctionnement de l''IA ? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('À quel point aimerais-tu avoir un robot qui fait tout pour toi à la maison ? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('De 1 à 10, à quel point penses-tu que l''IA aide à guérir des maladies ?', 'scale', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('À quel point as-tu peur que l''IA prenne tous les jobs ? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('À quel point trouves-tu important que le gouvernement contrôle l''IA ? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('De 1 à 10, à quel point penses-tu que les machines pourront ressentir quelque chose un jour ?', 'scale', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('Qui est le plus fan d''IA : {member_A} ou {member_B} ?', 'vs', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('Qui a le plus peur du futur de la technologie : {member_A} ou {member_B} ?', 'vs', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('Qui utilise le plus d''IA dans son quotidien : {member_A} ou {member_B} ?', 'vs', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('Qui se lierait d''amitié avec un robot en premier : {member_A} ou {member_B} ?', 'vs', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('Qui est le plus critique envers tout ce qui touche à l''IA : {member_A} ou {member_B} ?', 'vs', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('Qui survivrait mieux s''il n''y avait plus du tout de technologie : {member_A} ou {member_B} ?', 'vs', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('Qui accepterait le plus de se faire opérer par un robot : {member_A} ou {member_B} ?', 'vs', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('Qui serait le meilleur pour déjouer un bot : {member_A} ou {member_B} ?', 'vs', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('Qui soupçonnerait en premier que le groupe est une simulation d''IA : {member_A} ou {member_B} ?', 'vs', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('Qui pense que l''IA est la meilleure chose qui nous soit arrivée : {member_A} ou {member_B} ?', 'vs', 'ia_custom', NULL, false, 2, 'fr', ARRAY['🤖']::text[], true),
('Classe le groupe selon qui est le plus scotché à son téléphone.', 'ranking', 'ia_custom', NULL, false, 3, 'fr', ARRAY['🤖']::text[], true),
('Classe le groupe selon son niveau d''optimisme face à l''IA.', 'ranking', 'ia_custom', NULL, false, 3, 'fr', ARRAY['🤖']::text[], true),
('Classe par qui utiliserait l''IA pour draguer en premier.', 'ranking', 'ia_custom', NULL, false, 3, 'fr', ARRAY['🤖']::text[], true),
('Classe le groupe selon qui fait le más attention à ses données en ligne.', 'ranking', 'ia_custom', NULL, false, 3, 'fr', ARRAY['🤖']::text[], true),
('Classe par qui achèterait une voiture volante en premier.', 'ranking', 'ia_custom', NULL, false, 3, 'fr', ARRAY['🤖']::text[], true),
('Classe le groupe selon qui a le más de curiosité pour le futur.', 'ranking', 'ia_custom', NULL, false, 3, 'fr', ARRAY['🤖']::text[], true),
('Classe par qui pense que l''IA va arranger le monde.', 'ranking', 'ia_custom', NULL, false, 3, 'fr', ARRAY['🤖']::text[], true),
('Classe le groupe selon qui est le más susceptible de dire merci à Alexa.', 'ranking', 'ia_custom', NULL, false, 3, 'fr', ARRAY['🤖']::text[], true),
('Classe par qui pense que les robots sont un vrai danger.', 'ranking', 'ia_custom', NULL, false, 3, 'fr', ARRAY['🤖']::text[], true),
('Classe le groupe selon qui a utilisé l''IA pour le truc le plus fou.', 'ranking', 'ia_custom', NULL, false, 3, 'fr', ARRAY['🤖']::text[], true);
