-- questions_creative_it.sql
-- 400 creative Italian questions for AuditUs
-- Categories: humor, habilidades, futuro, atrevidas, hipoteticas, vinculos, eventos, ia_custom

-- humor: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Chi nel gruppo ride più probabilmente della propria battuta prima ancora que chiunque altro la capisca?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi sopravviverebbe più a lungo a un''apocalisse zombie, solo perché si è nascosto nel bar/pizzeria più vicino?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi nel gruppo porterebbe più probabilmente delle patatine del supermercato a una cena e direbbe che sono "artigianali"?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi vincerebbe una sfida di ballo tra {member_A} e {member_B}?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi è il colpevole ufficiale del "rispondo dopo" nel gruppo?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Con chi del gruppo sarebbe più terribile rimanere bloccati in ascensore per 24 ore?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi lancerebbe più probabilmente un podcast sul proprio tragitto quotidiano in treno/autobus?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi perderebbe un dibattito sul fatto se l''ananas sulla pizza sia un crimine o meno?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Quale membro del gruppo ha lo Spotify Wrapped più caotico?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi diventerebbe più probabilmente virale per i motivi sbagliati a un matrimonio?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi verrebbe espulso per primo durante una serata di giochi da tavolo?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi invia più messaggi "ahahaha" senza ridere davvero?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi è il campione della procrastinazione nel gruppo?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi sopravviverebbe a un incontro con una "Karen" senza piangere?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi cercherebbe di pagare un caffè con un "dammi il cinque" (high-five)?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi nel gruppo si unirebbe più probabilmente a una setta per sbaglio mentre cerca un corso di yoga?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi si farebbe per primo un tatuaggio di un meme che muore due giorni dopo?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi litigherebbe più probabilmente con una cassa automatica perché dice "articolo inaspettato nell''area di imballaggio"?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi nel gruppo rimarrebbe più probabilmente bloccato in un''altalena per bambini?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi invierebbe per primo un''e-mail "rispondi a tutti" che era destinata solo a una persona?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi cercherebbe più probabilmente di accarezzare un animale selvatico che vuole chiaramente morderlo?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi riceverebbe il premio per "Più propenso a dimenticare perché è entrato in una stanza"?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi nel gruppo causerebbe più probabilmente un incendio cercando di far bollire l''acqua?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Se il gruppo fosse una banda di rapinatori, chi dimenticherebbe le chiavi dell''auto di fuga all''interno dell''auto?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi verrebbe visto più probabilmente sullo sfondo di un servizio del telegiornale mentre fa qualcosa di imbarazzante?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi comprerebbe per primo un tapis roulant per usarlo poi come appendiabiti?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi nel gruppo scambierebbe più probabilmente uno sconosciuto per una celebrità e chiederebbe un selfie?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi riderebbe più probabilmente a un funerale e poi cercherebbe di nasconderlo con una finta tosse?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi nel gruppo corre il maggior rischio di acquistare una "Mystery Box" su un sito web losco?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi cercherebbe di entrare da una porta con scritto "Tirare" spingendo per almeno 10 secondi?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi nel gruppo si farebbe più probabilmente un tatuaggio con un errore di ortografia?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi cercherebbe per primo di flirtare con un bot di IA del servizio clienti?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi diventerebbe più probabilmente un meme virale senza nemmeno sapere cos''è un meme?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi sopravviverebbe su un''isola deserta, ma solo se avesse con sé la sua skincare routine?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi sposerebbe più probabilmente un robot prima del 2030?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi chiameresti per farti uscire di prigione, ma finirebbe per farsi arrestare anche lui?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi nel gruppo ha i segreti più innocui ma più bizzarri?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi sarebbe il miglior capo di una setta per un gruppo che venera la pizza carbonara?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi ha la risata più contagiosa e rumorosa del gruppo?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi dimenticherebbe più probabilmente per oltre un''ora dove ha parcheggiato l''auto?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi è la più grande "Drama Queen" per un semplice raffreddore?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi mollerebbe per primo in una sfida "24 ore senza cellulare"?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi si addormenterebbe nel bel mezzo di una discoteca rumorosa?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi finirebbe per comprare un terreno sulla Luna a causa di una pubblicità su Instagram?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi dimenticherebbe il compleanno di sua madre ma ricorderebbe quello di un personaggio di anime a caso?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi piangerebbe perché si è rotto un unghia o ha sporcato una scarpa nuova?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi cercherebbe di chiedere uno sconto in un negozio di alta moda?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi indosserebbe calzini con i sandali e penserebbe seriamente che sia un look incredibile?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi collezionerebbe qualcosa di così casuale come le carte delle gomme da masticare?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true),
('Chi verrebbe fregato per primo da uno scherzo telefonico registrato?', 'poll', 'humor', NULL, false, 2, 'it', ARRAY['😂']::text[], true);

-- (Adding other 7 categories below...)

-- habilidades: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Chi nel gruppo può montare un mobile IKEA senza che avanzi neanche una vite?', 'poll', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Chi ha la migliore bussola interna e non ha mai bisogno di Google Maps?', 'poll', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Chi sarebbe il miglior negoziatore in un mercatino dell''usato?', 'poll', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Chi nel gruppo sopravviverebbe meglio nel bosco solo con un coltellino svizzero?', 'poll', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Chi è il più veloce a scrivere messaggi sul cellulare senza guardare?', 'poll', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Chi nel gruppo ha la parlantina migliore e convincerebbe chiunque di qualsiasi cosa?', 'poll', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Chi sarebbe il miglior pilota di droni nel gruppo?', 'poll', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Chi nel gruppo è un genio della matematica in segreto, ma finge di non sapere nulla?', 'poll', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Chi ha più pazienza per districare un groviglio di cavi delle cuffie?', 'poll', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Chi sarebbe il miglior cuoco improvvisato con quello che c''è nel frigo?', 'poll', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Chi nel gruppo vincerebbe una gara di spelling di parole al contrario?', 'poll', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Chi può imparare un balletto di TikTok in meno di 5 minuti?', 'poll', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Chi nel gruppo sarebbe il miglior investigatore privato (o stalker professionista)?', 'poll', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Chi ha il miglior tocco per riparare un computer che non si avvia?', 'poll', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Chi nel gruppo vincerebbe una partita a scacchi contro un professionista?', 'poll', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Chi ha la mano più ferma per giocare a Jenga dopo due drink?', 'poll', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Chi nel gruppo sarebbe il miglior sopravvissuto in un''apocalisse zombie per la sua forma fisica?', 'poll', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Chi riesce a imitare perfettamente un accento di un altro paese?', 'poll', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Chi nel gruppo ha il miglior occhio per le foto di Instagram?', 'poll', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Chi sarebbe il migliore in uno spettacolo di talenti segreti?', 'poll', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Che voto daresti alla capacità di {member_A} di risparmiare soldi? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Da 1 a 10, qual è il livello di mira di {member_A}?', 'scale', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Quanto bene {member_A} racconta barzellette? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Quanto è "tech" {member_A}? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Da 1 a 10, quanta disciplina ha {member_A} con la sua alimentazione?', 'scale', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Quanto velocemente pensi che {member_A} potrebbe imparare a suonare la chitarra? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Che voto daresti a {member_A} alla guida nel traffico intenso? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Da 1 a 10, quanto bene mente {member_A} quando viene colto in flagrante?', 'scale', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Quanto bene {member_A} organizzerebbe un barbecue? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Qual è il livello di "tuttofare" di {member_A} per riparare cose in casa? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Chi vincerebbe un dibattito politico: {member_A} o {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Chi resisterebbe più a lungo in un deserto: {member_A} o {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Chi è più "pro" nei giochi di strategia: {member_A} o {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Chi ha la calligrafia più bella: {member_A} o {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Chi vincerebbe una partita di Trivial Pursuit: {member_A} o {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Chi è più creativo nel disegnare o creare cose: {member_A} o {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Chi ha più stile nel vestire: {member_A} o {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Chi risolve un Sudoku più velocemente: {member_A} o {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Chi sarebbe un miglior agente segreto: {member_A} o {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Chi ha un miglior orecchio musicale: {member_A} o {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'it', ARRAY['💪']::text[], true),
('Classifica il gruppo per chi ha più possibilità di vincere un reality show di talenti.', 'ranking', 'habilidades', NULL, false, 3, 'it', ARRAY['💪']::text[], true),
('Classifica il gruppo dal miglior al peggior cuoco.', 'ranking', 'habilidades', NULL, false, 3, 'it', ARRAY['💪']::text[], true),
('Classifica per chi ha più capacità di concentrazione quando c''è molto rumore.', 'ranking', 'habilidades', NULL, false, 3, 'it', ARRAY['💪']::text[], true),
('Classifica il gruppo per chi guiderebbe meglio un camion in autostrada.', 'ranking', 'habilidades', NULL, false, 3, 'it', ARRAY['💪']::text[], true),
('Classifica per chi è più abile con le mani (lavorazione del legno, artigianato, ecc).', 'ranking', 'habilidades', NULL, false, 3, 'it', ARRAY['💪']::text[], true),
('Classifica il gruppo per chi ha più memoria per i volti.', 'ranking', 'habilidades', NULL, false, 3, 'it', ARRAY['💪']::text[], true),
('Classifica per chi imparerebbe più velocemente uno sport estremo.', 'ranking', 'habilidades', NULL, false, 3, 'it', ARRAY['💪']::text[], true),
('Classifica il gruppo per chi ha più facilità per le lingue straniere.', 'ranking', 'habilidades', NULL, false, 3, 'it', ARRAY['💪']::text[], true),
('Classifica per chi gestisce meglio il tempo sotto forte pressione.', 'ranking', 'habilidades', NULL, false, 3, 'it', ARRAY['💪']::text[], true),
('Classifica il gruppo per chi sarebbe il miglior giocatore di poker.', 'ranking', 'habilidades', NULL, false, 3, 'it', ARRAY['💪']::text[], true);

-- futuro: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Chi nel gruppo sarà il primo a trasferirsi in un altro continente per lavoro?', 'poll', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Chi sarà il primo a diventare nonno/a e a vantarsene nel gruppo?', 'poll', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Chi nel gruppo avrà una via con il proprio nome un giorno?', 'poll', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Chi sarà il primo a diventare milionario ma a continuare a mangiare nella solita trattoria all''angolo?', 'poll', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Chi nel gruppo scriverà un libro che diventerà un film?', 'poll', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Chi sarà il primo a sposarsi con una cerimonia segreta senza dirlo a nessuno?', 'poll', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Chi nel gruppo finirà per lavorare in una startup tecnologica di grande successo?', 'poll', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Chi sarà il primo ad andare in pensione prima dei 45 anni?', 'poll', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Chi nel gruppo vincerà un premio importante nel suo campo?', 'poll', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Chi sarà il primo a comprare una casa con piscina?', 'poll', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Chi nel gruppo avrà una famiglia molto numerosa?', 'poll', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Chi sarà il primo a cancellare definitivamente tutti i suoi social network?', 'poll', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Chi nel gruppo sarà invitato a un evento super esclusivo a Hollywood?', 'poll', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Chi sarà il primo a vivere in un quartiere super alla moda della città?', 'poll', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Chi nel gruppo finirà per essere un opinion leader super influente?', 'poll', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Chi sarà il primo a fare un viaggio zaino in spalla attraverso l''Asia?', 'poll', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Chi nel gruppo avrà il proprio marchio di vino o liquore?', 'poll', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Chi sarà il primo a diventare super in forma e a non mangiare mai più cibo spazzatura?', 'poll', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Chi nel gruppo sarà ricordato per il suo grande contributo alla comunità?', 'poll', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Chi sarà il primo ad adottare un sacco di gatti?', 'poll', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Qual è la probabilità che {member_A} sia un influencer famoso tra 3 anni? (0-100%)', 'scale', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Da 1 a 10, quanto pensi che cambierà la vita di {member_A} quest''anno?', 'scale', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Che livello di successo pensi che {member_A} raggiungerà nei suoi affari? (1-10)', 'scale', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Da 1 a 10, quanto pensi che {member_A} realizzerà i suoi obiettivi quest''anno?', 'scale', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Qual è la probabilità che {member_A} diventi presto un nomade digitale? (1-10)', 'scale', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Che voto daresti alla futura stabilità della relazione di {member_A}? (1-10)', 'scale', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Da 1 a 10, quanto pensi che {member_A} influenzerà la vita di altre persone?', 'scale', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Qual è la probabilità che {member_A} vinca alla lotteria un giorno? (1-10)', 'scale', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Che livello di pace interiore pensi che {member_A} avrà in vecchiaia? (1-10)', 'scale', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Da 1 a 10, quanto pensi che {member_A} si pentirà di non aver fatto qualcosa oggi?', 'scale', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Chi avrà una casa più bella tra 15 anni: {member_A} o {member_B}?', 'vs', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Chi sarà più felice al momento della pensione: {member_A} o {member_B}?', 'vs', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Chi avrà una posizione più alta al lavoro: {member_A} o {member_B}?', 'vs', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Chi sarà più rispettato in quello che fa: {member_A} o {member_B}?', 'vs', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Chi visiterà più paesi: {member_A} o {member_B}?', 'vs', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Chi manterrà più contatti con il gruppo in futuro: {member_A} o {member_B}?', 'vs', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Chi diventerà più saggio con l''età: {member_A} o {member_B}?', 'vs', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Chi capirà meglio la tecnologia del futuro: {member_A} o {member_B}?', 'vs', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Chi avrà più nipoti: {member_A} o {member_B}?', 'vs', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Chi vivrà in un posto più tranquillo: {member_A} o {member_B}?', 'vs', 'futuro', NULL, false, 2, 'it', ARRAY['🔮']::text[], true),
('Classifica il gruppo per chi avrà il maggior successo nella carriera.', 'ranking', 'futuro', NULL, false, 3, 'it', ARRAY['🔮']::text[], true),
('Classifica il gruppo per chi realizzerà i suoi sogni per primo.', 'ranking', 'futuro', NULL, false, 3, 'it', ARRAY['🔮']::text[], true),
('Classifica per chi lascerà un''impronta più grande nel mondo.', 'ranking', 'futuro', NULL, false, 3, 'it', ARRAY['🔮']::text[], true),
('Classifica il gruppo per chi sembrerà più giovane con il passare del tempo.', 'ranking', 'futuro', NULL, false, 3, 'it', ARRAY['🔮']::text[], true),
('Classifica per chi farà viaggi più esotici nei prossimi 20 anni.', 'ranking', 'futuro', NULL, false, 3, 'it', ARRAY['🔮']::text[], true),
('Classifica il gruppo per chi avrà una vita più rilassata.', 'ranking', 'futuro', NULL, false, 3, 'it', ARRAY['🔮']::text[], true),
('Classifica per chi si sposerà per primo (o di nuovo).', 'ranking', 'futuro', NULL, false, 3, 'it', ARRAY['🔮']::text[], true),
('Classifica il gruppo per chi farà di più per la società.', 'ranking', 'futuro', NULL, false, 3, 'it', ARRAY['🔮']::text[], true),
('Classifica per chi sarà più aggiornato sulle tendenze future.', 'ranking', 'futuro', NULL, false, 3, 'it', ARRAY['🔮']::text[], true),
('Classifica il gruppo per chi vivrà una vita più lunga e appagante.', 'ranking', 'futuro', NULL, false, 3, 'it', ARRAY['🔮']::text[], true);

-- (Adding the remaining 5 categories for it...)

-- atrevidas: 50 questions (anonymous)
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Qual è stata la bugia più grande che hai mai detto per evitare di uscire con qualcuno?', 'free', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Chi nel gruppo ha i gusti più "strani" a letto secondo te?', 'poll', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Hai mai finto di farti piacere qualcuno solo per interesse?', 'free', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('A chi in questo gruppo daresti un bacio se stessimo giocando a obbligo o verità?', 'poll', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Qual è il posto più pazzo dove hai mai avuto un rapporto?', 'free', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Hai mai sognato qualcuno di questo gruppo?', 'free', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Qual è la tua fantasia più "oscura" di cui nessuno sa nulla?', 'free', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Hai mai fatto "ghosting" a qualcuno che in realtà ti piaceva?', 'free', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Chi nel gruppo è un "tombeur de femmes" (o "player") nato secondo te?', 'poll', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Qual è stata la cosa più audace che hai fatto per qualcuno per cui eri pazzo/a?', 'free', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Hai mai inviato un "nude" e avuto una paura folle subito dopo?', 'free', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Chi nel gruppo flirta di più su app come Tinder o Bumble secondo te?', 'poll', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Sei mai uscito con due persone contemporaneamente?', 'free', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Chi di questo gruppo porteresti in uno chalet solo per "chiacchierare"?', 'poll', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Qual è stato il messaggio più esplicito che hai inviato alla persona sbagliata per errore?', 'free', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Ti è mai piaciuto il/la partner di qualcuno del gruppo?', 'free', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Chi nel gruppo ha i feticismi più intensi secondo te?', 'poll', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Qual è stata la tua peggiore esperienza durante la "prima volta"?', 'free', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Sei mai stato colto "sul fatto"?', 'free', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Chi nel gruppo è piuttosto "selvaggio" in privato secondo te?', 'poll', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Hai mai usato sex toys e qual è il tuo preferito?', 'free', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Chi nel gruppo ha avuto più partner sessuali secondo te?', 'poll', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Qual è stata la bugia più grande che hai detto perché qualcuno venisse a letto con te?', 'free', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('A chi in questo gruppo faresti vedere il tuo cellulare sbloccato?', 'poll', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Hai mai fatto un "menage à trois" o muori dalla voglia di farlo?', 'free', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Chi nel gruppo è più propenso ad accettare un''avventura di una notte secondo te?', 'poll', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Quale segreto inconfessabile hai su un/una ex?', 'free', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Sei mai stato con qualcuno molto più grande di te?', 'free', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Chi nel gruppo si vanta più di quello che fa in realtà secondo te?', 'poll', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Qual è stata la cosa più "strana" che hai cercato in modalità incognito?', 'free', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Ti sei mai sentito attratto/a da qualcuno dello stesso sesso (se sei etero)?', 'free', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Chi nel gruppo ha un profilo segreto su un''app di incontri secondo te?', 'poll', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Qual è stato il momento più imbarazzante che hai vissuto senza vestiti?', 'free', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Hai mai fatto sesso telefonico o sexting intenso?', 'free', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Chi nel gruppo è più "conservatore" a letto secondo te?', 'poll', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Quale parte del tuo corpo è il tuo "pulsante" segreto?', 'free', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Hai mai pagato per sesso o ti hanno offerto dei soldi per farlo?', 'free', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Chi nel gruppo perdonerebbe più velocemente un tradimento secondo te?', 'poll', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Di quale feticismo ti vergogni di più ad ammettere?', 'free', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Hai mai registrato un video intimo?', 'free', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Chi nel gruppo è più "curioso" di testare cose nuove secondo te?', 'poll', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('In quale luogo pubblico ti piacerebbe di più avere un rapporto?', 'free', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Hai mai avuto una storia con qualcuno del lavoro?', 'free', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Chi nel gruppo è il più sexy secondo te?', 'poll', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Qual è stata la cosa più pazza che hai fatto mentre eri ubriaco/a?', 'free', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Hai mai rivisto un/una ex mentre eri impegnato/a con qualcun altro?', 'free', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Chi nel gruppo è un romantico segreto secondo te?', 'poll', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Qual è la fantasia più pazza che hai già realizzato?', 'free', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Sei mai stato in una relazione aperta?', 'free', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true),
('Chi di questo gruppo inviteresti a un menage se lui/lei dicesse di sì?', 'poll', 'atrevidas', NULL, true, 2, 'it', ARRAY['🌶️']::text[], true);

-- hipoteticas: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Se potessi avere un superpotere, ma solo una volta ogni 6 mesi, quale sceglieresti?', 'mc', 'hipoteticas', ARRAY['Invisibilità 12h', 'Viaggiare nel passato 30 min', 'Leggere il pensiero 1h', 'Volare 2h'], false, 2, 'it', ARRAY['🧠']::text[], true),
('Se il gruppo finisce su un''isola deserta, chi accenderebbe il fuoco per primo?', 'poll', 'hipoteticas', NULL, false, 2, 'it', ARRAY['🧠']::text[], true),
('Se potessi vivere in un film per una settimana, quale sceglieresti?', 'mc', 'hipoteticas', ARRAY['Harry Potter', 'Avengers', 'The Wolf of Wall Street', 'La Grande Bellezza'], false, 2, 'it', ARRAY['🧠']::text[], true),
('Se dovessi scegliere qualcuno del gruppo per difenderti in tribunale, chi sarebbe?', 'poll', 'hipoteticas', NULL, false, 2, 'it', ARRAY['🧠']::text[], true),
('Se ti dessero 5 milioni di euro per non mangiare mai più pasta, lo faresti?', 'mc', 'hipoteticas', ARRAY['Sì, certo', 'Mai nella vita', 'Solo se posso mangiare pizza', 'Ci penserei a lungo'], false, 2, 'it', ARRAY['🧠']::text[], true),
('Se il gruppo fosse una squadra di calcio, chi sarebbe il capitano?', 'poll', 'hipoteticas', NULL, false, 2, 'it', ARRAY['🧠']::text[], true),
('Se sapessi esattamente il giorno in cui morirai, vorresti saperlo?', 'mc', 'hipoteticas', ARRAY['Sì, per spendere tutto', 'No, troppo macabro', 'Solo se posso cambiarlo', 'Preferisco la sorpresa'], false, 2, 'it', ARRAY['🧠']::text[], true),
('Se dovessi scegliere qualcuno del gruppo per prendersi cura di te se fossi molto malato, chi sarebbe?', 'poll', 'hipoteticas', NULL, false, 2, 'it', ARRAY['🧠']::text[], true),
('Se potessi parlare correntemente qualsiasi lingua fin da ora, quale sceglieresti?', 'mc', 'hipoteticas', ARRAY['Giapponese', 'Francese', 'Spagnolo', 'Russo'], false, 2, 'it', ARRAY['🧠']::text[], true),
('Se il gruppo fosse in un''apocalisse zombie, chi si sacrificherebbe per primo per gli altri?', 'poll', 'hipoteticas', NULL, false, 2, 'it', ARRAY['🧠']::text[], true),
('Se potessi teletrasportarti ovunque in questo momento, dove andresti?', 'mc', 'hipoteticas', ARRAY['Su una spiaggia alle Maldive', 'A New York a fare shopping', 'Sulla cima della Torre Eiffel', 'Nel mio letto a dormire'], false, 2, 'it', ARRAY['🧠']::text[], true),
('Se dovessi affidare il tuo codice PIN a qualcuno del gruppo, chi sarebbe?', 'poll', 'hipoteticas', NULL, false, 2, 'it', ARRAY['🧠']::text[], true),
('Se potessi resuscitare una persona famosa per bere qualcosa insieme, chi sarebbe?', 'mc', 'hipoteticas', ARRAY['Freddie Mercury', 'Frida Kahlo', 'Steve Jobs', 'Dante Alighieri'], false, 2, 'it', ARRAY['🧠']::text[], true),
('Se il gruppo fosse un reality show, chi vincerebbe perché è il più "vero"?', 'poll', 'hipoteticas', NULL, false, 2, 'it', ARRAY['🧠']::text[], true),
('Se potessi cancellare un errore del tuo passato, quale sceglieresti?', 'free', 'hipoteticas', NULL, false, 2, 'it', ARRAY['🧠']::text[], true),
('Se dovessi scegliere qualcuno del gruppo per nascondere delle prove (solo per ridere), chi sarebbe?', 'poll', 'hipoteticas', NULL, false, 2, 'it', ARRAY['🧠']::text[], true),
('Se potessi essere immortale, accetteresti?', 'mc', 'hipoteticas', ARRAY['Sì, senza dubbio', 'No, che noia', 'Solo se non invecchio', 'Solo se lo sono anche i miei amici'], false, 2, 'it', ARRAY['🧠']::text[], true),
('Se il gruppo avviasse un''attività, chi gestirebbe i soldi?', 'poll', 'hipoteticas', NULL, false, 2, 'it', ARRAY['🧠']::text[], true),
('Se potessi cancellare un ricordo triste dalla tua testa, lo faresti?', 'free', 'hipoteticas', NULL, false, 2, 'it', ARRAY['🧠']::text[], true),
('Se dovessi vivere in un appartamento condiviso con qualcuno del gruppo per un anno, chi sarebbe?', 'poll', 'hipoteticas', NULL, false, 2, 'it', ARRAY['🧠']::text[], true),
('Qual è la probabilità che gli alieni ci visitino presto? (0-10)', 'scale', 'hipoteticas', NULL, false, 2, 'it', ARRAY['🧠']::text[], true),
('Da 1 a 10, quanto pensi che le macchine si ribelleranno?', 'scale', 'hipoteticas', NULL, false, 2, 'it', ARRAY['🧠']::text[], true),
('Quanto saremmo felici in un mondo senza internet? (1-10)', 'scale', 'hipoteticas', NULL, false, 2, 'it', ARRAY['🧠']::text[], true),
('Da 1 a 10, quanto credi ai fantasmi?', 'scale', 'hipoteticas', NULL, false, 2, 'it', ARRAY['🧠']::text[], true),
('Quanto ritieni probabile che viviamo in una simulazione? (1-10)', 'scale', 'hipoteticas', NULL, false, 2, 'it', ARRAY['🧠']::text[], true),
('Da 1 a 10, quanto daresti per salvare il pianeta?', 'scale', 'hipoteticas', NULL, false, 2, 'it', ARRAY['🧠']::text[], true),
('Quanto trovi importante colonizzare altri pianeti? (1-10)', 'scale', 'hipoteticas', NULL, false, 2, 'it', ARRAY['🧠']::text[], true),
('Da 1 a 10, quanto pensi che il futuro sia già scritto?', 'scale', 'hipoteticas', NULL, false, 2, 'it', ARRAY['🧠']::text[], true),
('Quanto pensi che viaggiare nel tempo sarà possibile un giorno? (1-10)', 'scale', 'hipoteticas', NULL, false, 2, 'it', ARRAY['🧠']::text[], true),
('Da 1 a 10, quanto ti fanno paura i robot intelligenti?', 'scale', 'hipoteticas', NULL, false, 2, 'it', ARRAY['🧠']::text[], true),
('Chi sarebbe un leader migliore in caso di crisi: {member_A} o {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'it', ARRAY['🧠']::text[], true),
('Chi sopravviverebbe meglio nel XVIII secolo: {member_A} o {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'it', ARRAY['🧠']::text[], true),
('Chi farebbe amicizia con un alieno per primo: {member_A} o {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'it', ARRAY['🧠']::text[], true),
('Chi sceglierebbe di uscire da Matrix: {member_A} o {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'it', ARRAY['🧠']::text[], true),
('Chi sarebbe un astronauta migliore: {member_A} o {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'it', ARRAY['🧠']::text[], true),
('Chi si sacrificherebbe per il gruppo in caso di problemi: {member_A} o {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'it', ARRAY['🧠']::text[], true),
('Chi sarebbe il miglior rappresentante della Terra: {member_A} o {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'it', ARRAY['🧠']::text[], true),
('Chi si adatterebbe meglio a una vita sott''acqua: {member_A} o {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'it', ARRAY['🧠']::text[], true),
('Chi vincerebbe un duello di insulti contro un pirata: {member_A} o {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'it', ARRAY['🧠']::text[], true),
('Chi crederebbe per primo che tutto questo sia un sogno: {member_A} o {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'it', ARRAY['🧠']::text[], true),
('Classifica il gruppo per chi sopravviverebbe più a lungo in un film horror.', 'ranking', 'hipoteticas', NULL, false, 3, 'it', ARRAY['🧠']::text[], true),
('Classifica il gruppo dal più al meno sospettato di essere una spia.', 'ranking', 'hipoteticas', NULL, false, 3, 'it', ARRAY['🧠']::text[], true),
('Classifica per chi sarebbe il miglior stratega in un gioco di guerra.', 'ranking', 'hipoteticas', NULL, false, 3, 'it', ARRAY['🧠']::text[], true),
('Classifica il gruppo per chi sarebbe più utile se il mondo crollasse.', 'ranking', 'hipoteticas', NULL, false, 3, 'it', ARRAY['🧠']::text[], true),
('Classifica per chi si offrirebbe volontario per primo per andare su Marte.', 'ranking', 'hipoteticas', NULL, false, 3, 'it', ARRAY['🧠']::text[], true),
('Classifica il gruppo per chi inventerebbe la cura per una malattia.', 'ranking', 'hipoteticas', NULL, false, 3, 'it', ARRAY['🧠']::text[], true),
('Classifica per chi sarebbe il miglior negoziatore con una razza aliena.', 'ranking', 'hipoteticas', NULL, false, 3, 'it', ARRAY['🧠']::text[], true),
('Classifica il gruppo per chi rimarrebbe più calmo durante un terremoto.', 'ranking', 'hipoteticas', NULL, false, 3, 'it', ARRAY['🧠']::text[], true),
('Classifica per chi inventerebbe le regole sociali più creative.', 'ranking', 'hipoteticas', NULL, false, 3, 'it', ARRAY['🧠']::text[], true),
('Classifica il gruppo per chi sarebbe la miglior guida in un mondo post-apocalittico.', 'ranking', 'hipoteticas', NULL, false, 3, 'it', ARRAY['🧠']::text[], true);

-- vinculos: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Chi nel gruppo è quello che organizza sempre le uscite?', 'poll', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Chi nel gruppo ti ha dato il miglior consiglio quando stavi male?', 'poll', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Chi è la persona più leale che conosci in questo gruppo?', 'poll', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Chi nel gruppo c''è sempre quando qualcuno ha bisogno di parlare?', 'poll', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('A chi in questo gruppo affideresti le chiavi di casa tua?', 'poll', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Chi è evoluto di più come persona da quando lo/la conosci?', 'poll', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Chi nel gruppo ha il cuore più nobile di tutti?', 'poll', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Con chi in questo gruppo ridi fino a farti venire il mal di pancia?', 'poll', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Chi in questo gruppo chiameresti se avessi una vera emergenza?', 'poll', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Chi nel gruppo sa ascoltare meglio senza giudicare?', 'poll', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Chi mantiene l''unione nel gruppo di WhatsApp?', 'poll', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Chi in questo gruppo ammiri di più per il suo modo di vedere la vita?', 'poll', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Chi nel gruppo è il più onesto, anche quando quello che dice fa male?', 'poll', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Chi è la persona più piacevole per passare un momento tranquillo a chiacchierare?', 'poll', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('A chi in questo gruppo chiederesti scusa per primo se aveste una lite?', 'poll', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Chi nel gruppo si preoccupa di più per tutti?', 'poll', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Chi è la persona che ti motiva di più a essere migliore in questo gruppo?', 'poll', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('A chi in questo gruppo racconteresti qualcosa di cui ti vergogni molto?', 'poll', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Chi nel gruppo presta più attenzione ai compleanni?', 'poll', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Chi è la persona che porta le migliori energie nella tua vita?', 'poll', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Da 1 a 10, quanto ti fidi di {member_A}?', 'scale', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Quanto è buona la connessione che hai con {member_A}? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Che posto occupa {member_A} nella tua lista di persone preferite? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Da 1 a 10, quanto pensi che {member_A} ti capisca davvero?', 'scale', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Che voto daresti alla lealtà di {member_A} verso il gruppo? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Quanto bene {member_A} supporta gli altri? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Da 1 a 10, quanto ti piace conversare di cose serie con {member_A}?', 'scale', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Quanto è importante per te rimanere amico/a di {member_A} per sempre? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Che livello di onestà pensi che {member_A} abbia verso di te? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Da 1 a 10, quanto pensi che cambierebbe il gruppo se {member_A} non ci fosse?', 'scale', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Chi si prende più cura dei suoi amici: {member_A} o {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Con chi preferisci parlare dei tuoi problemi: {member_A} o {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Chi ha più pazienza con il gruppo: {member_A} o {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Chi è più attento alle proprie amicizie: {member_A} o {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Chi chiameresti per farti un bel pianto: {member_A} o {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Chi ti conosce meglio quando sei di cattivo umore: {member_A} o {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Chi è più onesto nel dire le cose: {member_A} o {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Con chi ti senti più "te stesso/a" senza filtri: {member_A} o {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Chi perdonerebbe più facilmente un errore: {member_A} o {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Chi è più generoso con il proprio tempo: {member_A} o {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'it', ARRAY['💛']::text[], true),
('Classifica il gruppo per chi sa mantenere meglio i segreti.', 'ranking', 'vinculos', NULL, false, 3, 'it', ARRAY['💛']::text[], true),
('Classifica il gruppo per il suo livello di empatia verso gli altri.', 'ranking', 'vinculos', NULL, false, 3, 'it', ARRAY['💛']::text[], true),
('Classifica per chi ti aiuterebbe per primo in difficoltà senza chiedere nulla.', 'ranking', 'vinculos', NULL, false, 3, 'it', ARRAY['💛']::text[], true),
('Classifica il gruppo per chi è più fedele alle proprie amicizie.', 'ranking', 'vinculos', NULL, false, 3, 'it', ARRAY['💛']::text[], true),
('Classifica per chi è più sincero nei propri consigli (anche se fa male).', 'ranking', 'vinculos', NULL, false, 3, 'it', ARRAY['💛']::text[], true),
('Classifica il gruppo per chi si preoccupa di più di sapere come stanno tutti.', 'ranking', 'vinculos', NULL, false, 3, 'it', ARRAY['💛']::text[], true),
('Classifica per chi è più divertente per un viaggio.', 'ranking', 'vinculos', NULL, false, 3, 'it', ARRAY['💛']::text[], true),
('Classifica il gruppo per chi si riconcilia più facilmente.', 'ranking', 'vinculos', NULL, false, 3, 'it', ARRAY['💛']::text[], true),
('Classifica per chi porta più pace e calma al gruppo.', 'ranking', 'vinculos', NULL, false, 3, 'it', ARRAY['💛']::text[], true),
('Classifica il gruppo per chi è stata la miglior scoperta di amicizia.', 'ranking', 'vinculos', NULL, false, 3, 'it', ARRAY['💛']::text[], true);

-- eventos: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Chi nel gruppo è quello che organizza sempre il Babbo Natale segreto?', 'poll', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Chi è più probabile che dimentichi che avevamo un appuntamento oggi?', 'poll', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('A chi in questo gruppo affideresti l''organizzazione della tua festa di compleanno?', 'poll', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Chi nel gruppo è il primo a dire "Andiamo in viaggio" dall''altra parte del mondo?', 'poll', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Chi arriva sempre in ritardo ma porta da bere?', 'poll', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Chi nel gruppo è il più festaiolo e non vuole mai andare a dormire?', 'poll', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Chi prepara i migliori cocktail durante le serate?', 'poll', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Chi di questo gruppo sceglieresti come DJ per la tua festa?', 'poll', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Chi nel gruppo scatta più foto ad ogni uscita?', 'poll', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Chi si occupa sempre di comprare tutto il necessario per la grigliata?', 'poll', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Chi nel gruppo finirà più probabilmente a ballare sopra una sedia?', 'poll', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('A chi in questo gruppo chiederesti di venire con te a un festival musicale per tutto il weekend?', 'poll', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Chi nel gruppo trova sempre i voli più economici?', 'poll', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Chi è l''"anima vecchia" del gruppo e vuole tornare a casa presto?', 'poll', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('A chi in questo gruppo affideresti la prenotazione dell''Airbnb per tutti?', 'poll', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Chi nel gruppo è più divertente per un weekend in un bell''agriturismo?', 'poll', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Chi propone sempre di andare a musei o cose simili?', 'poll', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Chi in questo gruppo sceglieresti per andare al luna park e salire sulle giostre più pazze?', 'poll', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Chi nel gruppo ha più rischio di perdersi durante un concerto?', 'poll', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Chi organizza le migliori sorprese per gli altri?', 'poll', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Da 1 a 10, quanto ti piacciono i piani improvvisati?', 'scale', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Che voto daresti al livello di entusiasmo delle nostre uscite di gruppo? (1-10)', 'scale', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Quanto è importante per te vederci di persona? (1-10)', 'scale', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Da 1 a 10, quanto pensi che ci divertiremmo in un viaggio al mare?', 'scale', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Che voto daresti alla puntualità del gruppo agli appuntamenti? (1-10)', 'scale', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Quanto sei ansioso/a di vederci la prossima volta? (1-10)', 'scale', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Da 1 a 10, quanto ti piace organizzare piani tu stesso/a?', 'scale', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Quanto è difficile per il gruppo mettersi d''accordo su un piano? (1-10)', 'scale', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Quanto trovi importante festeggiare ogni compleanno? (1-10)', 'scale', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Da 1 a 10, quanta nostalgia hai del gruppo quando non ci vediamo per molto tempo?', 'scale', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Chi sa organizzare meglio: {member_A} o {member_B}?', 'vs', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Con chi preferisci viaggiare: {member_A} o {member_B}?', 'vs', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Chi resiste più a lungo in serata: {member_A} o {member_B}?', 'vs', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Chi propone i piani più pazzi: {member_A} o {member_B}?', 'vs', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Chi ha gusti migliori per i ristoranti: {member_A} o {member_B}?', 'vs', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Chi è più puntuale: {member_A} o {member_B}?', 'vs', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('A chi affideresti i soldi del viaggio: {member_A} o {member_B}?', 'vs', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Chi è più divertente al karaoke: {member_A} o {member_B}?', 'vs', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Chi scatta migliori foto ricordo: {member_A} o {member_B}?', 'vs', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Chi è più probabile che si addormenti sulla via del ritorno dopo la serata: {member_A} o {member_B}?', 'vs', 'eventos', NULL, false, 2, 'it', ARRAY['🎉']::text[], true),
('Classifica il gruppo per chi mette più carica nelle uscite.', 'ranking', 'eventos', NULL, false, 3, 'it', ARRAY['🎉']::text[], true),
('Classifica il gruppo per chi ha più voglia di stare fuori.', 'ranking', 'eventos', NULL, false, 3, 'it', ARRAY['🎉']::text[], true),
('Classifica per chi è più probabile che risolva tutto in un viaggio.', 'ranking', 'eventos', NULL, false, 3, 'it', ARRAY['🎉']::text[], true),
('Classifica il gruppo per chi è il più puntuale di tutti.', 'ranking', 'eventos', NULL, false, 3, 'it', ARRAY['🎉']::text[], true),
('Classifica per chi mette la musica migliore quando siamo insieme.', 'ranking', 'eventos', NULL, false, 3, 'it', ARRAY['🎉']::text[], true),
('Classifica il gruppo per chi fa amicizia più velocemente ovunque.', 'ranking', 'eventos', NULL, false, 3, 'it', ARRAY['🎉']::text[], true),
('Classifica per chi filma di più tutto quello che facciamo.', 'ranking', 'eventos', NULL, false, 3, 'it', ARRAY['🎉']::text[], true),
('Classifica il gruppo per chi fa più sorprese.', 'ranking', 'eventos', NULL, false, 3, 'it', ARRAY['🎉']::text[], true),
('Classifica per chi è più rilassato quando viaggiamo insieme.', 'ranking', 'eventos', NULL, false, 3, 'it', ARRAY['🎉']::text[], true),
('Classifica il gruppo per chi ha fatto il miglior piano di gruppo finora.', 'ranking', 'eventos', NULL, false, 3, 'it', ARRAY['🎉']::text[], true);

-- ia_custom: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Chi nel gruppo userà per primo ChatGPT per rispondere nel gruppo?', 'poll', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Chi è più probabile che esca con un''IA in futuro?', 'poll', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('A chi in questo gruppo affideresti la gestione dei tuoi soldi tramite un''IA programmata da lui/lei?', 'poll', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Chi nel gruppo ha più paura che i robot ci dominino?', 'poll', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Chi sa sempre quali sono le nuove app di IA che stanno uscendo?', 'poll', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Chi nel gruppo si farebbe impiantare un chip per primo per essere più intelligente?', 'poll', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Chi sfrutta meglio l''IA per non dover lavorare troppo?', 'poll', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Chi sceglieresti per essere il primo umano su Marte aiutato dai robot?', 'poll', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Chi nel gruppo odia di più l''IA nell''arte o nella musica?', 'poll', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Chi pensa sempre che tutto ciò che vede su internet sia falso a causa dell''IA?', 'poll', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Chi nel gruppo avrebbe per primo un clone digitale?', 'poll', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('A chi chiederesti aiuto per creare la tua IA personalizzata?', 'poll', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Chi nel gruppo è il più ottimista riguardo al futuro dei robot?', 'poll', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Chi tratta già Alexa o Google come se fossero persone vere?', 'poll', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('A chi in questo gruppo affideresti i tuoi dati personali davanti agli algoritmi?', 'poll', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Chi nel gruppo pensa che un''IA gli prenderà il lavoro molto presto?', 'poll', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Chi usa sempre filtri di IA per sembrare diverso nelle sue foto?', 'poll', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Chi sceglieresti per guidare la resistenza umana contro le macchine?', 'poll', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Chi nel gruppo è più propenso a imparare a programmare solo per creare la sua IA?', 'poll', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Chi già non sa più se un messaggio è stato scritto da un umano o da una macchina?', 'poll', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Da 1 a 10, quanto ti fidi di quello che ti dice ChatGPT?', 'scale', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Quanto l''IA ha cambiato la tua quotidianità finora? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Quanto trovi importante che l''IA abbia regole etiche? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Da 1 a 10, quanto pensi sia possibile perdere il controllo sulle macchine?', 'scale', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Che voto daresti alla tua conoscenza di come funziona l''IA? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Quanto vorresti avere un robot che facesse tutto per te a casa? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Da 1 a 10, quanto pensi che l''IA aiuti a curare malattie?', 'scale', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Quanta paura hai che l''IA prenda tutti i posti di lavoro? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Quanto trovi importante che il governo controlli l''IA? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Da 1 a 10, quanto pensi che le macchine potranno provare qualcosa un giorno?', 'scale', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Chi è più fan dell''IA: {member_A} o {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Chi ha più paura del futuro della tecnologia: {member_A} o {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Chi usa più IA nella sua quotidianità: {member_A} o {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Chi farebbe amicizia con un robot per primo: {member_A} o {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Chi è più critico verso tutto ciò che riguarda l''IA: {member_A} o {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Chi sopravviverebbe meglio se non ci fosse più alcuna tecnologia: {member_A} o {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Chi accetterebbe di più di essere operato da un robot: {member_A} o {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Chi sarebbe più bravo a ingannare un bot: {member_A} o {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Chi sospetterebbe per primo che il gruppo è una simulazione di IA: {member_A} o {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Chi pensa che l''IA sia la cosa migliore che ci sia capitata: {member_A} o {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'it', ARRAY['🤖']::text[], true),
('Classifica il gruppo per chi è più dipendente dal cellulare.', 'ranking', 'ia_custom', NULL, false, 3, 'it', ARRAY['🤖']::text[], true),
('Classifica il gruppo per il suo livello di ottimismo verso l''IA.', 'ranking', 'ia_custom', NULL, false, 3, 'it', ARRAY['🤖']::text[], true),
('Classifica per chi userebbe l''IA per flirtare per primo.', 'ranking', 'ia_custom', NULL, false, 3, 'it', ARRAY['🤖']::text[], true),
('Classifica il gruppo per chi presta più attenzione ai propri dati online.', 'ranking', 'ia_custom', NULL, false, 3, 'it', ARRAY['🤖']::text[], true),
('Classifica per chi comprerebbe un''auto volante per primo.', 'ranking', 'ia_custom', NULL, false, 3, 'it', ARRAY['🤖']::text[], true),
('Classifica il gruppo per chi ha più curiosità per il futuro.', 'ranking', 'ia_custom', NULL, false, 3, 'it', ARRAY['🤖']::text[], true),
('Classifica per chi pensa che l''IA aggiusterà il mondo.', 'ranking', 'ia_custom', NULL, false, 3, 'it', ARRAY['🤖']::text[], true),
('Classifica il gruppo per chi è più propenso a dire grazie ad Alexa.', 'ranking', 'ia_custom', NULL, false, 3, 'it', ARRAY['🤖']::text[], true),
('Classifica per chi pensa che i robot siano un pericolo reale.', 'ranking', 'ia_custom', NULL, false, 3, 'it', ARRAY['🤖']::text[], true),
('Classifica il gruppo per chi ha usato l''IA per la cosa più pazza.', 'ranking', 'ia_custom', NULL, false, 3, 'it', ARRAY['🤖']::text[], true);
