-- questions_creative_es.sql
-- 400 creative Spanish (Spain) questions for AuditUs
-- Categories: humor, habilidades, futuro, atrevidas, hipoteticas, vinculos, eventos, ia_custom

-- humor: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('¿Quién es más probable que se ría de su propio chiste antes de terminar de contarlo?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién sobreviviría más tiempo en un apocalipsis zombie solo porque se ha quedado encerrado en un bar?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién traería patatas de bolsa a una cena elegante y diría que son "artesanas"?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién ganaría un duelo de baile entre {member_A} y {member_B}?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién es el rey/reina del "visto" en el grupo de WhatsApp?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Con quién sería más insoportable quedarse encerrado en un ascensor 24 horas?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién se haría un podcast sobre sus trayectos en el metro/bus?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién perdería un debate sobre si la tortilla de patatas debe llevar cebolla o no?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Qué miembro del grupo tiene el Spotify Wrapped más caótico?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién se haría viral por los motivos equivocados en una boda?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿A quién echarían primero de una partida de juegos de mesa por hacer trampas?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién manda más mensajes de "jajaja" sin estar riéndose de verdad?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién es el campeón de la procrastinación en el grupo?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién sobreviviría a una bronca con un revisor del tren sin llorar?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién intentaría pagar un café con un "chócala" (high-five)?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién se uniría a una secta por error pensando que es un curso de yoga?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién se haría un tatuaje de un meme que muere a los dos días?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién discutiría con una caja de autopago porque dice "artículo inesperado en el área de embolsado"?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién se quedaría atascado en un columpio para niños?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién mandaría primero un correo de "responder a todos" que era para una sola persona?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién intentaría acariciar a un perro callejero que claramente quiere morderle?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién se llevaría el premio a "más probable que olvide por qué ha entrado en una habitación"?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién causaría un incendio intentando hervir agua?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('Si el grupo fuera una banda de atracadores, ¿quién se dejaría las llaves dentro del coche de huida?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿A quién veríamos de fondo en el telediario haciendo algo vergonzoso?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién compraría una cinta de correr para acabar usándola de perchero?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién confundiría a un desconocido con un famoso y le pediría un selfie?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién se reiría en un funeral y luego fingiría un ataque de tos?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién tiene más riesgo de comprar una "Mystery Box" en una web china turbia?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién intentaría entrar por una puerta que pone "Tirar" empujando durante 10 segundos?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién se haría un tatuaje con una falta de ortografía?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién intentaría ligar con un bot de atención al cliente?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién se convertiría en un meme viral sin saber siquiera qué es un meme?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién sobreviviría en una isla deserta pero solo si tuviera su rutina de skincare?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién se casaría con un robot antes de 2030?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿A quién llamarías para que te sacara de la cárcel pero acabaría arrestado también?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién tiene los secretos más inofensivos pero más raros?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién sería el mejor líder de una secta que adora la pizza con piña?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién tiene la risa más contagiosa y escandalosa?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién olvidaría dónde ha aparcado el coche durante más de una hora?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién es el más "Drama Queen" por un simple resfriado?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién aguantaría menos en un reto de "24 horas sin móvil"?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién se quedaría dormido en mitad de una discoteca?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién acabaría comprando una parcela en la Luna por un anuncio de Instagram?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién olvidaría el cumple de su madre pero recordaría el de un personaje de anime?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién lloraría porque se le ha roto una uña o manchado una zapatilla nueva?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién intentaría pedir un descuento en una tienda de lujo?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién llevaría calcetines con sandalias y pensaría que es un lookazo?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿Quién coleccionaría algo tan random como envoltorios de chicles?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true),
('¿A quién se la colarían primero con una broma telefónica grabada?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂']::text[], true);

-- (Adding other 7 categories below...)

-- habilidades: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('¿Quién puede montar un mueble de IKEA sin que le sobre ni un tornillo?', 'poll', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Quién tiene la mejor brújula interna y no necesita Google Maps?', 'poll', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Quién sería el mejor negociador en un rastro?', 'poll', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Quién sobreviviría mejor en el campo solo con una navaja?', 'poll', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Quién escribe más rápido en el móvil sin mirar?', 'poll', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Quién tiene más labia y convencería a cualquiera de cualquier cosa?', 'poll', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Quién sería el mejor piloto de drones del grupo?', 'poll', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Quién es un genio de las mates en secreto pero finge que no sabe nada?', 'poll', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Quién tiene más paciencia para desenredar cables?', 'poll', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Quién sería el mejor cocinero improvisado con lo que haya en la nevera?', 'poll', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Quién ganaría un concurso de deletrear palabras al revés?', 'poll', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Quién se aprende un baile de TikTok en menos de 5 minutos?', 'poll', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Quién sería el mejor detective privado (o stalker profesional)?', 'poll', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Quién tiene mejor mano para arreglar un PC que no arranca?', 'poll', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Quién ganaría una partida de ajedrez contra un pro?', 'poll', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Quién tiene el pulso más firme para el Jenga después de dos cañas?', 'poll', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Quién sobreviviría mejor a un apocalipsis por su forma física?', 'poll', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Quién imita mejor un acento extranjero?', 'poll', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Quién tiene mejor ojo para las fotos de Instagram?', 'poll', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Quién sería el mejor en un show de talentos ocultos?', 'poll', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Qué nota le das a la capacidad de ahorro de {member_A}? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('Del 1 al 10, ¿qué nivel de puntería tiene {member_A}?', 'scale', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Cómo de bien cuenta chistes {member_A}? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Cómo de "techie" es {member_A}? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('Del 1 al 10, ¿cuánta disciplina tiene {member_A} con la comida?', 'scale', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Qué nota le das a {member_A} conduciendo en hora punta? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('Del 1 al 10, ¿qué tal miente {member_A} cuando le pillan?', 'scale', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Cómo de bien organizaría una barbacoa {member_A}? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Qué nivel de "manitas" tiene {member_A} para arreglar cosas en casa? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Quién ganaría un debate político: {member_A} o {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Quién aguantaría más tiempo en un desierto: {member_A} o {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Quién es más "pro" en juegos de estrategia: {member_A} o {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Quién tiene la letra más bonita: {member_A} o {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Quién ganaría al Trivial: {member_A} o {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Quién es más creativo dibujando o creando cosas: {member_A} o {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Quién tiene más estilo vistiendo: {member_A} o {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Quién resuelve un Sudoku más rápido: {member_A} o {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Quién sería un mejor agente secreto: {member_A} o {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('¿Quién tiene mejor oído musical: {member_A} o {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'es', ARRAY['💪']::text[], true),
('Clasifica al grupo por quién tiene más papeletas para ganar un reality de talentos.', 'ranking', 'habilidades', NULL, false, 3, 'es', ARRAY['💪']::text[], true),
('Clasifica al grupo del mejor al peor cocinero.', 'ranking', 'habilidades', NULL, false, 3, 'es', ARRAY['💪']::text[], true),
('Clasifica por quién tiene más capacidad de concentración con mucho ruido.', 'ranking', 'habilidades', NULL, false, 3, 'es', ARRAY['💪']::text[], true),
('Clasifica al grupo por quién conduciría mejor un camión por la autopista.', 'ranking', 'habilidades', NULL, false, 3, 'es', ARRAY['💪']::text[], true),
('Clasifica por quién es más habilidoso con las manos (bricolaje, manualidades, etc).', 'ranking', 'habilidades', NULL, false, 3, 'es', ARRAY['💪']::text[], true),
('Clasifica al grupo por quién tiene más memoria para las caras.', 'ranking', 'habilidades', NULL, false, 3, 'es', ARRAY['💪']::text[], true),
('Clasifica por quién aprendería más rápido un deporte de riesgo.', 'ranking', 'habilidades', NULL, false, 3, 'es', ARRAY['💪']::text[], true),
('Clasifica al grupo por quién tiene más facilidad para los idiomas.', 'ranking', 'habilidades', NULL, false, 3, 'es', ARRAY['💪']::text[], true),
('Clasifica por quién gestiona mejor el tiempo bajo mucha presión.', 'ranking', 'habilidades', NULL, false, 3, 'es', ARRAY['💪']::text[], true),
('Clasifica al grupo por quién sería el mejor jugador de póker.', 'ranking', 'habilidades', NULL, false, 3, 'es', ARRAY['💪']::text[], true);

-- futuro: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('¿Quién se mudará antes a otro país por trabajo?', 'poll', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿Quién será el primero en ser abuelo/a y fardar de ello?', 'poll', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿Quién tendrá una calle con su nombre algún día?', 'poll', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿Quién será millonario pero seguirá comiendo el menú del día de 10€?', 'poll', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿Quién escribirá un libro que se hará película?', 'poll', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿Quién se casará en una boda secreta sin avisar?', 'poll', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿Quién acabará trabajando en una startup de Silicon Valley?', 'poll', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿Quién se jubilará antes de los 45?', 'poll', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿Quién ganará un premio importante en su sector?', 'poll', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿Quién será el primero en comprarse un chalet con piscina?', 'poll', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿Quién tendrá una familia muy numerosa?', 'poll', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿Quién borrará sus redes sociales para siempre primero?', 'poll', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿A quién invitarán a un evento exclusivo en Hollywood?', 'poll', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿Quién vivirá en un barrio "hípster" de moda?', 'poll', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿Quién acabará siendo un líder de opinión muy influyente?', 'poll', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿Quién se irá de mochilero por Asia primero?', 'poll', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿Quién tendrá su propia marca de vino o cerveza?', 'poll', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿Quién se pondrá súper fit y no volverá a comer pizza nunca?', 'poll', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿Quién será recordado por su gran contribución a la comunidad?', 'poll', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿Quién será el primero en adoptar un montón de gatos?', 'poll', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿Qué probabilidad hay de que {member_A} sea un influencer famoso en 3 años? (0-100%)', 'scale', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('Del 1 al 10, ¿cuánto crees que cambiará la vida de {member_A} este año?', 'scale', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿Qué nivel de éxito crees que alcanzará {member_A} en sus negocios? (1-10)', 'scale', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('Del 1 al 10, ¿cuánto crees que {member_A} cumplirá sus metas?', 'scale', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿Qué probabilidad hay de que {member_A} sea nómada digital pronto? (1-10)', 'scale', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿Qué nota le das a la futura estabilidad de {member_A}? (1-10)', 'scale', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('Del 1 al 10, ¿cuánto crees que {member_A} influirá en la vida de otros?', 'scale', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿Qué probabilidad hay de que {member_A} gane la lotería algún día? (1-10)', 'scale', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿Qué nivel de paz mental crees que tendrá {member_A} de mayor? (1-10)', 'scale', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('Del 1 al 10, ¿cuánto crees que {member_A} se arrepentirá de no haber hecho algo hoy?', 'scale', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿Quién tendrá una casa más chula en 15 años: {member_A} o {member_B}?', 'vs', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿Quién será más feliz al jubilarse: {member_A} o {member_B}?', 'vs', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿Quién tendrá un cargo más alto en el curro: {member_A} o {member_B}?', 'vs', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿Quién será más respetado en lo que hace: {member_A} o {member_B}?', 'vs', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿Quién visitará más países: {member_A} o {member_B}?', 'vs', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿Quién mantendrá más el contacto con el grupo: {member_A} o {member_B}?', 'vs', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿Quién será más sabio con la edad: {member_A} o {member_B}?', 'vs', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿Quién entenderá mejor la tecnología del futuro: {member_A} o {member_B}?', 'vs', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿Quién tendrá más nietos: {member_A} o {member_B}?', 'vs', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('¿Quién vivirá en un sitio más tranquilo: {member_A} o {member_B}?', 'vs', 'futuro', NULL, false, 2, 'es', ARRAY['🔮']::text[], true),
('Clasifica al grupo por quién tendrá mayor éxito profesional.', 'ranking', 'futuro', NULL, false, 3, 'es', ARRAY['🔮']::text[], true),
('Clasifica al grupo por quién cumplirá sus sueños primero.', 'ranking', 'futuro', NULL, false, 3, 'es', ARRAY['🔮']::text[], true),
('Clasifica por quién dejará una huella más grande en el mundo.', 'ranking', 'futuro', NULL, false, 3, 'es', ARRAY['🔮']::text[], true),
('Clasifica al grupo por quién parecerá más joven con los años.', 'ranking', 'futuro', NULL, false, 3, 'es', ARRAY['🔮']::text[], true),
('Clasifica por quién hará viajes más exóticos en los próximos 20 años.', 'ranking', 'futuro', NULL, false, 3, 'es', ARRAY['🔮']::text[], true),
('Clasifica al grupo por quién tendrá una vida más relajada.', 'ranking', 'futuro', NULL, false, 3, 'es', ARRAY['🔮']::text[], true),
('Clasifica por quién se casará antes (o de nuevo).', 'ranking', 'futuro', NULL, false, 3, 'es', ARRAY['🔮']::text[], true),
('Clasifica al grupo por quién hará más por la sociedad.', 'ranking', 'futuro', NULL, false, 3, 'es', ARRAY['🔮']::text[], true),
('Clasifica por quién estará más al día de las tendencias futuras.', 'ranking', 'futuro', NULL, false, 3, 'es', ARRAY['🔮']::text[], true),
('Clasifica al grupo por quién vivirá una vida más larga y plena.', 'ranking', 'futuro', NULL, false, 3, 'es', ARRAY['🔮']::text[], true);

-- (Adding the remaining 5 categories for es...)

-- atrevidas: 50 questions (anonymous)
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('¿Cuál ha sido la mayor mentira que has contado para no quedar con alguien?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Quién del grupo tiene los gustos más "raros" en la cama según tu opinión?', 'poll', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Has fingido alguna vez que te gustaba alguien solo por interés?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿A quién de este grupo le darías un beso si estuviéramos jugando a verdad o atrevimiento?', 'poll', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Cuál es el sitio más loco donde lo has hecho?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Has soñado alguna vez con alguien de este grupo?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Cuál es tu fantasía más "oscura" de la que nadie sabe nada?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Has hecho "ghosting" alguna vez a alguien que realmente te gustaba?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Quién del grupo es un ligón/ligona nato según tu opinión?', 'poll', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Qué es lo más audaz que has hecho por alguien que te traía loco/a?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Has mandado un "nude" y has tenido un miedo atroz justo después?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Quién del grupo liga más por apps como Tinder o Bumble según tu opinión?', 'poll', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Has salido alguna vez con dos personas a la vez?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿A quién de este grupo te llevarías a una cabaña solo para "hablar"?', 'poll', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Cuál ha sido el mensaje más explícito que has mandado a la persona equivocada por error?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Te ha gustado alguna vez la pareja de alguien del grupo?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Quién del grupo tiene los fetiches más intensos según tu opinión?', 'poll', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Cuál fue tu peor experiencia en la "primera vez"?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Te han pillado alguna vez "en faena"?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Quién del grupo es más "fiera" en privado según tu opinión?', 'poll', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Has usado juguetes sexuales y cuál es tu favorito?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Quién del grupo ha tenido más parejas sexuales según tu opinión?', 'poll', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Cuál ha sido la mayor mentira que has dicho para que alguien se acostara contigo?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿A quién de este grupo le confiarías tu móvil desbloqueado?', 'poll', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Has hecho un trío o te mueres por hacerlo?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Quién del grupo es más propenso a aceptar un lío de una noche según tu opinión?', 'poll', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Qué secreto inconfesable tienes sobre un/una ex?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Has estado alguna vez con alguien mucho mayor que tú?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Quién del grupo farda más de lo que hace en realidad según tu opinión?', 'poll', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Qué es lo más "raro" que has buscado en modo incógnito?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Te has sentido atraído/a por alguien del mismo sexo (si eres hétero)?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Quién del grupo tiene un perfil secreto en una app de citas según tu opinión?', 'poll', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Cuál ha sido el momento más vergonzoso que has vivido sin ropa?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Has hecho sexo telefónico o sexting intenso?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Quién del grupo es más "conservador" en la cama según tu opinión?', 'poll', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Qué parte de tu cuerpo es tu "botón" secreto?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Has pagado alguna vez por sexo o te han ofrecido dinero por ello?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Quién del grupo perdonaría antes una infidelidad según tu opinión?', 'poll', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿De qué fetiche te avergüenzas más admitir?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Has grabado alguna vez un vídeo íntimo?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Quién del grupo es más "curioso" por probar cosas nuevas según tu opinión?', 'poll', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿En qué sitio público te gustaría más hacerlo?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Has tenido algún lío con alguien del curro?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Quién del grupo es el más sexy según tu opinión?', 'poll', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Qué es lo más loco que has hecho estando borracho/a?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Has vuelto a ver a un/una ex mientras estabas en una relación con otra persona?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Quién del grupo es un romántico en secreto según tu opinión?', 'poll', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Cuál es la fantasía más loca que ya has cumplido?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿Has estado alguna vez en una relación abierta?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true),
('¿A quién de este grupo invitarías a un trío si te dijera que sí?', 'poll', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️']::text[], true);

-- hipoteticas: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Si pudieras tener un superpoder pero solo una vez cada 6 meses, ¿cuál elegirías?', 'mc', 'hipoteticas', ARRAY['Invisibilidad 12h', 'Viajar al pasado 30 min', 'Leer la mente 1h', 'Volar 2h'], false, 2, 'es', ARRAY['🧠']::text[], true),
('Si el grupo acaba en una isla desierta, ¿quién encendería el fuego primero?', 'poll', 'hipoteticas', NULL, false, 2, 'es', ARRAY['🧠']::text[], true),
('Si pudieras vivir en una película una semana, ¿cuál elegirías?', 'mc', 'hipoteticas', ARRAY['Harry Potter', 'Vengadores', 'El Lobo de Wall Street', 'Ocho Apellidos Vascos'], false, 2, 'es', ARRAY['🧠']::text[], true),
('Si tuvieras que elegir a alguien del grupo para defenderte en un juicio, ¿quién sería?', 'poll', 'hipoteticas', NULL, false, 2, 'es', ARRAY['🧠']::text[], true),
('Si te dieran 5 millones de euros por no volver a comer jamón serrano, ¿lo harías?', 'mc', 'hipoteticas', ARRAY['Sí, de cabeza', 'Ni de broma', 'Solo si puedo comer lomo', 'Me lo pensaría mucho'], false, 2, 'es', ARRAY['🧠']::text[], true),
('Si el grupo fuera un equipo de fútbol, ¿quién sería el capitán?', 'poll', 'hipoteticas', NULL, false, 2, 'es', ARRAY['🧠']::text[], true),
('Si supieras exactamente el día en que vas a morir, ¿querrías saberlo?', 'mc', 'hipoteticas', ARRAY['Sí, para fundírmelo todo', 'No, qué mal rollo', 'Solo si puedo cambiarlo', 'Prefiero la sorpresa'], false, 2, 'es', ARRAY['🧠']::text[], true),
('Si tuvieras que elegir a alguien del grupo para que te cuide si estuvieras muy malito, ¿quién sería?', 'poll', 'hipoteticas', NULL, false, 2, 'es', ARRAY['🧠']::text[], true),
('Si pudieras hablar cualquier idioma con fluidez ahora mismo, ¿cuál elegirías?', 'mc', 'hipoteticas', ARRAY['Japonés', 'Francés', 'Alemán', 'Ruso'], false, 2, 'es', ARRAY['🧠']::text[], true),
('Si el grupo estuviera en un apocalipsis zombie, ¿quién se sacrificaría primero por los demás?', 'poll', 'hipoteticas', NULL, false, 2, 'es', ARRAY['🧠']::text[], true),
('Si pudieras teletransportarte a cualquier sitio ahora mismo, ¿a dónde irías?', 'mc', 'hipoteticas', ARRAY['A una playa de las Maldivas', 'A Nueva York de compras', 'A la cima de la Torre Eiffel', 'A mi cama a dormir'], false, 2, 'es', ARRAY['🧠']::text[], true),
('Si tuvieras que confiarle tu código PIN a alguien del grupo, ¿quién sería?', 'poll', 'hipoteticas', NULL, false, 2, 'es', ARRAY['🧠']::text[], true),
('Si pudieras resucitar a un famoso para tomarte algo con él/ella, ¿quién sería?', 'mc', 'hipoteticas', ARRAY['Freddie Mercury', 'Frida Kahlo', 'Steve Jobs', 'Lola Flores'], false, 2, 'es', ARRAY['🧠']::text[], true),
('Si el grupo fuera un reality, ¿quién ganaría por ser el más "real"?', 'poll', 'hipoteticas', NULL, false, 2, 'es', ARRAY['🧠']::text[], true),
('Si pudieras borrar un error de tu pasado, ¿cuál elegirías?', 'free', 'hipoteticas', NULL, false, 2, 'es', ARRAY['🧠']::text[], true),
('Si tuvieras que elegir a alguien del grupo para esconder pruebas (de risas), ¿quién sería?', 'poll', 'hipoteticas', NULL, false, 2, 'es', ARRAY['🧠']::text[], true),
('Si pudieras ser inmortal, ¿aceptarías?', 'mc', 'hipoteticas', ARRAY['Sí, sin duda', 'No, qué aburrimiento', 'Solo si no envejezco', 'Solo si mis amigos también lo son'], false, 2, 'es', ARRAY['🧠']::text[], true),
('Si el grupo montara un negocio, ¿quién llevaría las cuentas?', 'poll', 'hipoteticas', NULL, false, 2, 'es', ARRAY['🧠']::text[], true),
('Si pudieras borrar un recuerdo triste de tu cabeza, ¿lo harías?', 'free', 'hipoteticas', NULL, false, 2, 'es', ARRAY['🧠']::text[], true),
('Si tuvieras que vivir en un piso compartido con alguien del grupo un año, ¿quién sería?', 'poll', 'hipoteticas', NULL, false, 2, 'es', ARRAY['🧠']::text[], true),
('¿Qué probabilidad hay de que nos visiten alienígenas pronto? (0-10)', 'scale', 'hipoteticas', NULL, false, 2, 'es', ARRAY['🧠']::text[], true),
('Del 1 al 10, ¿cuánto crees que se rebelarán las máquinas?', 'scale', 'hipoteticas', NULL, false, 2, 'es', ARRAY['🧠']::text[], true),
('¿Cómo de felices seríamos en un mundo sin internet? (1-10)', 'scale', 'hipoteticas', NULL, false, 2, 'es', ARRAY['🧠']::text[], true),
('Del 1 al 10, ¿cuánto crees en los fantasmas?', 'scale', 'hipoteticas', NULL, false, 2, 'es', ARRAY['🧠']::text[], true),
('¿Cómo de probable crees que vivimos en una simulación? (1-10)', 'scale', 'hipoteticas', NULL, false, 2, 'es', ARRAY['🧠']::text[], true),
('Del 1 al 10, ¿cuánto darías por salvar el planeta?', 'scale', 'hipoteticas', NULL, false, 2, 'es', ARRAY['🧠']::text[], true),
('¿Cómo de importante crees que es colonizar otros planetas? (1-10)', 'scale', 'hipoteticas', NULL, false, 2, 'es', ARRAY['🧠']::text[], true),
('Del 1 al 10, ¿cuánto crees que el futuro ya está escrito?', 'scale', 'hipoteticas', NULL, false, 2, 'es', ARRAY['🧠']::text[], true),
('¿Cómo de posible ves que se pueda viajar en el tiempo algún día? (1-10)', 'scale', 'hipoteticas', NULL, false, 2, 'es', ARRAY['🧠']::text[], true),
('Del 1 al 10, ¿cuánto miedo te dan los robots inteligentes?', 'scale', 'hipoteticas', NULL, false, 2, 'es', ARRAY['🧠']::text[], true),
('¿Quién sería un mejor líder en caso de crisis: {member_A} o {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'es', ARRAY['🧠']::text[], true),
('¿Quién sobreviviría mejor en el siglo XVIII: {member_A} o {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'es', ARRAY['🧠']::text[], true),
('¿Quién se haría amigo de un alien primero: {member_A} o {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'es', ARRAY['🧠']::text[], true),
('¿Quién elegiría salir de Matrix: {member_A} o {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'es', ARRAY['🧠']::text[], true),
('¿Quién sería un mejor astronauta: {member_A} o {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'es', ARRAY['🧠']::text[], true),
('¿Quién se sacrificaría por el grupo ante un marrón: {member_A} o {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'es', ARRAY['🧠']::text[], true),
('¿Quién sería el mejor representante de la Tierra: {member_A} o {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'es', ARRAY['🧠']::text[], true),
('¿Quién se adaptaría mejor a vivir bajo el agua: {member_A} o {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'es', ARRAY['🧠']::text[], true),
('¿Quién ganaría un duelo de insultos contra un pirata: {member_A} o {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'es', ARRAY['🧠']::text[], true),
('¿Quién creería antes que todo esto es un sueño: {member_A} o {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'es', ARRAY['🧠']::text[], true),
('Clasifica al grupo por quién sobreviviría más en una peli de terror.', 'ranking', 'hipoteticas', NULL, false, 3, 'es', ARRAY['🧠']::text[], true),
('Clasifica al grupo del más al menos sospechoso de ser un espía.', 'ranking', 'hipoteticas', NULL, false, 3, 'es', ARRAY['🧠']::text[], true),
('Clasifica por quién sería el mejor estratega en un juego de guerra.', 'ranking', 'hipoteticas', NULL, false, 3, 'es', ARRAY['🧠']::text[], true),
('Clasifica al grupo por quién sería más útil si el mundo se fuera al garete.', 'ranking', 'hipoteticas', NULL, false, 3, 'es', ARRAY['🧠']::text[], true),
('Clasifica por quién se ofrecería voluntario para ir a Marte.', 'ranking', 'hipoteticas', NULL, false, 3, 'es', ARRAY['🧠']::text[], true),
('Clasifica al grupo por quién inventaría la cura de una enfermedad.', 'ranking', 'hipoteticas', NULL, false, 3, 'es', ARRAY['🧠']::text[], true),
('Clasifica por quién sería el mejor negociador con una raza alien.', 'ranking', 'hipoteticas', NULL, false, 3, 'es', ARRAY['🧠']::text[], true),
('Clasifica al grupo por quién mantendría más la calma en un terremoto.', 'ranking', 'hipoteticas', NULL, false, 3, 'es', ARRAY['🧠']::text[], true),
('Clasifica por quién inventaría las reglas sociales más raras.', 'ranking', 'hipoteticas', NULL, false, 3, 'es', ARRAY['🧠']::text[], true),
('Clasifica al grupo por quién sería el mejor guía en un mundo post-apocalíptico.', 'ranking', 'hipoteticas', NULL, false, 3, 'es', ARRAY['🧠']::text[], true);

-- vinculos: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('¿Quién del grupo es el que siempre organiza las quedadas?', 'poll', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿Quién del grupo te ha dado el mejor consejo cuando estabas mal?', 'poll', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿Quién es la persona más leal que conoces en este grupo?', 'poll', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿Quién del grupo está siempre ahí cuando alguien necesita hablar?', 'poll', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿A quién de este grupo le confiarías las llaves de tu casa?', 'poll', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿Quién ha evolucionado más como persona desde que le conoces?', 'poll', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿Quién del grupo tiene el corazón más noble de todos?', 'poll', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿Con quién de este grupo te ríes hasta que te duele la tripa?', 'poll', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿A quién de este grupo llamarías si tuvieras una emergencia de verdad?', 'poll', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿Quién del grupo sabe escuchar mejor sin juzgar?', 'poll', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿Quién mantiene la unión en el grupo de WhatsApp?', 'poll', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿A quién de este grupo admiras más por su forma de ver la vida?', 'poll', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿Quién del grupo es el más honesto aunque lo que diga duela?', 'poll', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿Quién es la persona más agradable para pasar un rato tranquilo charlando?', 'poll', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿A quién de este grupo le pedirías perdón primero si tuvierais un roce?', 'poll', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿Quién del grupo se preocupa más por todos?', 'poll', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿Quién es la persona que más te motiva a ser mejor en este grupo?', 'poll', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿A quién de este grupo le contarías algo que te da mucha vergüenza?', 'poll', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿Quién del grupo presta más atención a los cumpleaños?', 'poll', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿Quién es la persona que más buenas energías aporta a tu vida?', 'poll', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('Del 1 al 10, ¿cuánta confianza tienes en {member_A}?', 'scale', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿Cómo de buena es la conexión que tienes con {member_A}? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿Qué puesto ocupa {member_A} en tu lista de personas favoritas? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[] , true),
('Del 1 al 10, ¿cuánto crees que te entiende de verdad {member_A}?', 'scale', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿Qué nota le das a la lealtad de {member_A} con el grupo? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿Cómo de bien apoya a los demás {member_A}? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('Del 1 al 10, ¿cuánto te gusta conversar sobre cosas serias con {member_A}?', 'scale', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿Cómo de importante es para ti seguir siendo amigo de {member_A} siempre? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿Qué nivel de honestidad crees que tiene {member_A} contigo? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('Del 1 al 10, ¿cuánto crees que cambiaría el grupo si {member_A} no estuviera?', 'scale', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿Quién cuida más de sus amigos: {member_A} o {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿Con quién prefieres hablar de tus problemas: {member_A} o {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿Quién tiene más paciencia con el grupo: {member_A} o {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿Quién es más atento con sus amistades: {member_A} o {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿A quién llamarías para echarte un buen llanto: {member_A} o {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿Quién te conoce mejor cuando estás de mala leche: {member_A} o {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿Quién es más honesto para decir las cosas: {member_A} o {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿Con quién te sientes más "tú mismo" sin filtros: {member_A} o {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿Quién perdonaría más fácil un error: {member_A} o {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('¿Quién es más generoso con su tiempo: {member_A} o {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'es', ARRAY['💛']::text[], true),
('Clasifica al grupo por quién sabe guardar mejor secretos.', 'ranking', 'vinculos', NULL, false, 3, 'es', ARRAY['💛']::text[], true),
('Clasifica al grupo por su nivel de empatía con los demás.', 'ranking', 'vinculos', NULL, false, 3, 'es', ARRAY['💛']::text[], true),
('Clasifica por quién te ayudaría primero en un marrón sin preguntar.', 'ranking', 'vinculos', NULL, false, 3, 'es', ARRAY['💛']::text[], true),
('Clasifica al grupo por quién es más fiel a sus amistades.', 'ranking', 'vinculos', NULL, false, 3, 'es', ARRAY['💛']::text[], true),
('Clasifica por quién es más sincero en sus consejos (aunque duela).', 'ranking', 'vinculos', NULL, false, 3, 'es', ARRAY['💛']::text[], true),
('Clasifica al grupo por quién más se preocupa por saber cómo están todos.', 'ranking', 'vinculos', NULL, false, 3, 'es', ARRAY['💛']::text[], true),
('Clasifica por quién es más divertido para un viaje.', 'ranking', 'vinculos', NULL, false, 3, 'es', ARRAY['💛']::text[], true),
('Clasifica al grupo por quién se reconcilia más fácilmente.', 'ranking', 'vinculos', NULL, false, 3, 'es', ARRAY['💛']::text[], true),
('Clasifica por quién aporta más paz y calma al grupo.', 'ranking', 'vinculos', NULL, false, 3, 'es', ARRAY['💛']::text[] , true),
('Clasifica al grupo por quién ha sido el mejor descubrimiento de amistad.', 'ranking', 'vinculos', NULL, false, 3, 'es', ARRAY['💛']::text[], true);

-- eventos: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('¿Quién del grupo es el que siempre organiza el amigo invisible?', 'poll', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿Quién es más probable que olvide que habíamos quedado hoy?', 'poll', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿A quién de este grupo le confiarías la organización de tu fiesta de cumple?', 'poll', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿Quién del grupo es el primero en decir "Vámonos de viaje" a la otra punta del mundo?', 'poll', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿Quién llega siempre tarde pero trae las bebidas?', 'poll', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿Quién del grupo es el más fiestero y nunca quiere irse a dormir?', 'poll', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿Quién prepara los mejores combinados en las quedadas?', 'poll', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿A quién de este grupo elegirías como DJ para tu fiesta?', 'poll', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿Quién del grupo hace más fotos en cada salida?', 'poll', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿Quién se encarga siempre de comprar todo lo necesario para la barbacoa?', 'poll', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿Quién del grupo acabará más probablemente bailando encima de una silla?', 'poll', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿A quién de este grupo le pedirías que se viniera contigo a un festival todo el finde?', 'poll', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿Quién del grupo encuentra siempre los vuelos más baratos?', 'poll', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿Quién es el "viejoven" del grupo y quiere irse pronto a casa?', 'poll', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿A quién de este grupo le confiarías pillar el Airbnb para todos?', 'poll', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿Quién del grupo es más divertido para un finde en una casa rural?', 'poll', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿Quién propone siempre ir a museos o cosas así?', 'poll', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿A quién de este grupo elegirías para ir al parque de atracciones y subir a lo más loco?', 'poll', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿Quién del grupo tiene más riesgo de perderse en un concierto?', 'poll', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿Quién organiza las mejores sorpresas para los demás?', 'poll', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('Del 1 al 10, ¿cuánto te gustan los planes improvisados?', 'scale', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿Qué nota le das al nivel de animación de nuestras salidas de grupo? (1-10)', 'scale', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿Cómo de importante es para ti que nos veamos en persona? (1-10)', 'scale', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('Del 1 al 10, ¿cuánto crees que nos divertiríamos en un viaje a la playa?', 'scale', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿Qué nota le das a la puntualidad del grupo en las quedadas? (1-10)', 'scale', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿Cómo de ansioso/a estás por vernos la próxima vez? (1-10)', 'scale', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('Del 1 al 10, ¿cuánto te gusta organizar planes tú mismo/a?', 'scale', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿Cómo de difícil le resulta al grupo ponerse de acuerdo en un plan? (1-10)', 'scale', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿Cómo de importante crees que es celebrar cada cumple? (1-10)', 'scale', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('Del 1 al 10, ¿cuánta morriña te da el grupo cuando no nos vemos en mucho tiempo?', 'scale', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿Quién sabe organizar mejor: {member_A} o {member_B}?', 'vs', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿Con quién prefieres viajar: {member_A} o {member_B}?', 'vs', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿Quién aguanta más en una fiesta: {member_A} o {member_B}?', 'vs', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿Quién propone los planes más locos: {member_A} o {member_B}?', 'vs', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿Quién tiene mejores gustos para restaurantes: {member_A} o {member_B}?', 'vs', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿Quién es más puntual: {member_A} o {member_B}?', 'vs', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿A quién le confiarías el dinero del viaje: {member_A} o {member_B}?', 'vs', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿Quién es más gracioso en un karaoke: {member_A} o {member_B}?', 'vs', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿Quién hace mejores fotos de recuerdo: {member_A} o {member_B}?', 'vs', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('¿Quién es más probable que se sobe en el camino de vuelta de la fiesta: {member_A} o {member_B}?', 'vs', 'eventos', NULL, false, 2, 'es', ARRAY['🎉']::text[], true),
('Clasifica al grupo por quién mete más caña en las salidas.', 'ranking', 'eventos', NULL, false, 3, 'es', ARRAY['🎉']::text[], true),
('Clasifica al grupo por quién tiene más ganas de calle.', 'ranking', 'eventos', NULL, false, 3, 'es', ARRAY['🎉']::text[], true),
('Clasifica por quién es más probable que lo resuelva todo en un viaje.', 'ranking', 'eventos', NULL, false, 3, 'es', ARRAY['🎉']::text[], true),
('Clasifica al grupo por quién es el más puntual de todos.', 'ranking', 'eventos', NULL, false, 3, 'es', ARRAY['🎉']::text[], true),
('Clasifica por quién pone la mejor música cuando estamos juntos.', 'ranking', 'eventos', NULL, false, 3, 'es', ARRAY['🎉']::text[], true),
('Clasifica al grupo por quién hace amigos más rápido en cualquier sitio.', 'ranking', 'eventos', NULL, false, 3, 'es', ARRAY['🎉']::text[], true),
('Clasifica por quién graba más todo lo que hacemos.', 'ranking', 'eventos', NULL, false, 3, 'es', ARRAY['🎉']::text[], true),
('Clasifica al grupo por quién hace más sorpresas.', 'ranking', 'eventos', NULL, false, 3, 'es', ARRAY['🎉']::text[], true),
('Clasifica por quién es más relajado cuando viajamos juntos.', 'ranking', 'eventos', NULL, false, 3, 'es', ARRAY['🎉']::text[], true),
('Clasifica al grupo por quién ha hecho el mejor plan de grupo hasta ahora.', 'ranking', 'eventos', NULL, false, 3, 'es', ARRAY['🎉']::text[], true);

-- ia_custom: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('¿Quién del grupo usará antes ChatGPT para responder en el grupo?', 'poll', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿Quién es más probable que salga con una IA en el futuro?', 'poll', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿A quién de este grupo le confiarías que una IA programada por él/ella gestione tu dinero?', 'poll', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿Quién del grupo tiene más miedo de que los robots nos dominen?', 'poll', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿Quién sabe siempre cuáles son las nuevas apps de IA que van saliendo?', 'poll', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿Quién del grupo se implantaría un chip antes para ser más inteligente?', 'poll', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿Quién aprovecha mejor la IA para no tener que currar tanto?', 'poll', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿A quién elegirías para ser el primer humano en Marte ayudado por robots?', 'poll', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿Quién del grupo odia más la IA en el arte o en la música?', 'poll', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿Quién cree siempre que todo lo que ve en internet es falso por culpa de la IA?', 'poll', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿Quién del grupo tendría antes un clon digital?', 'poll', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿A quién le pedirías ayuda para crear tu propia IA personalizada?', 'poll', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿Quién del grupo es el más optimista con el futuro de los robots?', 'poll', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿Quién trata ya a Alexa o a Google como si fuesen personas de verdad?', 'poll', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿A quién de este grupo le confiarías tus datos personales ante los algoritmos?', 'poll', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿Quién del grupo cree que una IA le quitará el trabajo muy pronto?', 'poll', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿Quién usa siempre filtros de IA para parecer diferente en sus fotos?', 'poll', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿A quién elegirías para liderar la resistencia humana contra las máquinas?', 'poll', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿Quién del grupo es más propenso a aprender a programar solo para crear su IA?', 'poll', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿Quién ya no sabe si un mensaje lo ha escrito un humano o una máquina?', 'poll', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('Del 1 al 10, ¿cuánto te fías de lo que te dice ChatGPT?', 'scale', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿Cuánto ha cambiado la IA tu día a día hasta ahora? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿Cómo de importante crees que es que la IA tenga reglas éticas? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('Del 1 al 10, ¿cómo de posible ves que perdamos el control sobre las máquinas?', 'scale', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿Qué nota le das a tu conocimiento sobre cómo funciona la IA? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿Cuánto te gustaría tener un robot que hiciera todo por ti en casa? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('Del 1 al 10, ¿cuánto crees que la IA ayuda a curar enfermedades?', 'scale', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿Cuánto miedo tienes de que la IA se quede con todos los trabajos? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿Cómo de importante crees que es que el gobierno controle la IA? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('Del 1 al 10, ¿cuánto crees que las máquinas podrán sentir algo algún día?', 'scale', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿Quién es más fan de la IA: {member_A} o {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿Quién tiene más miedo al futuro de la tecnología: {member_A} o {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿Quién usa más IA en su día a día: {member_A} o {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿Quién se haría amigo de un robot antes: {member_A} o {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿Quién es más crítico con todo lo que rodea a la IA: {member_A} o {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿Quién sobreviviría mejor si no hubiera nada de tecnología: {member_A} o {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿Quién aceptaría más ser operado por un robot: {member_A} o {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿Quién sería mejor engañando a un bot: {member_A} o {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿Quién sospecharía antes que el grupo es una simulación de IA: {member_A} o {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('¿Quién cree que la IA es lo mejor que nos ha pasado: {member_A} o {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'es', ARRAY['🤖']::text[], true),
('Clasifica al grupo por quién es más adicto al móvil.', 'ranking', 'ia_custom', NULL, false, 3, 'es', ARRAY['🤖']::text[], true),
('Clasifica al grupo por su nivel de optimismo ante la IA.', 'ranking', 'ia_custom', NULL, false, 3, 'es', ARRAY['🤖']::text[], true),
('Clasifica por quién usaría la IA para ligar primero.', 'ranking', 'ia_custom', NULL, false, 3, 'es', ARRAY['🤖']::text[], true),
('Clasifica al grupo por quién presta más atención a sus datos online.', 'ranking', 'ia_custom', NULL, false, 3, 'es', ARRAY['🤖']::text[], true),
('Clasifica por quién se compraría un coche volador primero.', 'ranking', 'ia_custom', NULL, false, 3, 'es', ARRAY['🤖']::text[], true),
('Clasifica al grupo por quién tiene más curiosidad por el futuro.', 'ranking', 'ia_custom', NULL, false, 3, 'es', ARRAY['🤖']::text[], true),
('Clasifica por quién cree que la IA arreglará el mundo.', 'ranking', 'ia_custom', NULL, false, 3, 'es', ARRAY['🤖']::text[], true),
('Clasifica al grupo por quién es más propenso a darle las gracias a Alexa.', 'ranking', 'ia_custom', NULL, false, 3, 'es', ARRAY['🤖']::text[], true),
('Clasifica por quién cree que los robots son un peligro real.', 'ranking', 'ia_custom', NULL, false, 3, 'es', ARRAY['🤖']::text[], true),
('Clasifica al grupo por quién ha usado la IA para la cosa más loca.', 'ranking', 'ia_custom', NULL, false, 3, 'es', ARRAY['🤖']::text[], true);
