-- questions_creative_es_humor_atrevidas.sql
-- 200 creative Spanish questions: 100 humor + 100 atrevidas
-- humor: poll=30, vs=25, mc=20, free=15, ranking=10
-- atrevidas: vs=30, free=70 (all anonymous)

INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
-- humor: poll questions (30)
('¿Quién sería el primero en llorar viendo una película de Disney en el grupo?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Quién del grupo tendría más éxito como vendedor ambulante en un mercadillo?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Quién sobreviviría más tiempo en un supermercado sin comprar nada?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Quién es más probable que se quede dormido en un transporte público?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Quién tardaría más en salir de un centro comercial si le prohiben comprar?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Quién sería el peor psicólogo del mundo pero aun así la gente pagaría por él?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Quién pondría la nota más baja a una paella casera solo por ser spiteful?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Quién es más propenso a enviar un audio de 5 minutos a las 3 de la mañana?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Quién sería el primero en bloquear a un familiar en WhatsApp?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Quién usaría un filtro de belleza en una videollamada con el médico?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Quién conseguiría trabajo antes como modelo de stock foto?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Quién aceptaría primero una oferta de "trabajo" que prometiera "visibilidad" en Instagram?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Quién es más probable que descubra un trending topic antes que nadie?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Quién usaría su posición en un grupo para hacer propaganda de sus negocios?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Quién llegaría más lejos con una mentira sobre conocer a un famoso?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Quién sería el último en enterarse de que el grupo tiene un grupo nuevo sin él?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Quién pondría una story de Instagram solo para抬高 su ego?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Quién sería más feliz en un mundo donde las grasas trans no existieran pero el alcohol sí?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Quién dejaría el móvil en casa solo por no tener que responder mensajes?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Quién sería el primero en hacer una fiesta de pijamas a los 35?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Quién interpretaría mejor una novela entera solo con frases de Gran Hermano?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Quién se perdería el festival de música por no haber ducha caliente?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Quién aceptaría primero un café de alguien que no lava los dientes?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Quién sería capaz de comerse un kebab a las 6 de la mañana después de fiesta?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Quién usaría "es que tengo algo raro" como excusa para no ir al médico?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Quién tendría la mayor colección de calcetines sin usar?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Quién sería el primero en cotillear en la sala de espera del médico?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Quién crearía un grupo nuevo solo para excluir a alguien?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Quién sería más popular en un reality de supervivencia solo por ser dramático?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Quién llegaría a las conclusiones más rápidas sin conocer los hechos?', 'poll', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
-- humor: vs questions (25)
('{member_A} vs {member_B}: ¿quién sobreviviría un día entero sin tocar el móvil?', 'vs', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('{member_A} vs {member_B}: ¿quién entraría primero a clase having hecho los deberes?', 'vs', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('{member_A} vs {member_B}: ¿quién conseguiría vender un artículo inútil a un turista?', 'vs', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('{member_A} vs {member_B}: ¿quién duraría más en una conversación con tu ex?', 'vs', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('{member_A} vs {member_B}: ¿quién pondría la mejor excusa para no ir a un evento familiar?', 'vs', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('{member_A} vs {member_B}: ¿quién llegaría más lejos con una sonrisa falsa?', 'vs', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('{member_A} vs {member_B}: ¿quién sería mejor conductor en Madrid centro a las 8 de la mañana?', 'vs', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('{member_A} vs {member_B}: ¿quién ganaría un debate sobre si el plátano es fruta o verdura?', 'vs', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('{member_A} vs {member_B}: ¿ quién conseguiría entrar a un concierto sin entrada?', 'vs', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('{member_A} vs {member_B}: ¿quién tendría más éxito en una cita a ciegas?', 'vs', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('{member_A} vs {member_B}: ¿quién sobreviviría a un día completo en un spa sin hablar?', 'vs', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('{member_A} vs {member_B}: ¿quién haría mejor de influencer de viajes sin haber salido de España?', 'vs', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('{member_A} vs {member_B}: ¿quién recordaría los nombres de todas las personas que conoció en una fiesta?', 'vs', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('{member_A} vs {member_B}: ¿quién conseguiría que el camarero le diese la mesa mejor?', 'vs', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('{member_A} vs {member_B}: ¿quién duraría más sin wifi antes de empezar a panic?', 'vs', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('{member_A} vs {member_B}: ¿quién sería mejor mánager de un equipo de futbito?', 'vs', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('{member_A} vs {member_B}: ¿quién daría la noticia más importante con más drama?', 'vs', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('{member_A} vs {member_B}: ¿quién sobreviviría a una prueba de resistencia en Mercadona?', 'vs', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('{member_A} vs {member_B}: ¿quién haría mejor claim de seguro para justificar unas vacaciones?', 'vs', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('{member_A} vs {member_B}: ¿quién se pondría más nervioso en un ascensor atascado?', 'vs', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('{member_A} vs {member_B}: ¿quién ganaría el concurso de contar un chiste sin hacerlo gracia?', 'vs', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('{member_A} vs {member_B}: ¿quién dejaría el plato más raro para el final de la comida familiar?', 'vs', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('{member_A} vs {member_B}: ¿quién conseguiría dormir en un sofá de un familiar por semanas?', 'vs', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('{member_A} vs {member_B}: ¿quién sería el primero en cambiar su nombre en el grupo por uno funny?', 'vs', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('{member_A} vs {member_B}: ¿quién adaptaría mejor su acento para sobrevivir en otra región de España?', 'vs', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
-- humor: mc questions (20)
('Imagina que el grupo tiene que elegir un superpoder: ¿cuál preferíais?', 'mc', 'humor', ARRAY['Leer la mente', 'Volar', 'Ser invisible', 'Hablar con animales'], false, 2, 'es', ARRAY['😂'], true),
('El grupo se pierde en la montaña. ¿Quién moriría primero?', 'mc', 'humor', ARRAY['El que lleva chanclas', 'El que solo trae el móvil', 'El que no sabe orientar sin GPS', 'El que entra en pánico sin café'], false, 2, 'es', ARRAY['😂'], true),
('¿Cuál es la forma más absurda en que te has escapado de un evento aburrido?', 'mc', 'humor', ARRAY['Fingí una llamada urgentísima', 'Hice que me necesitase el baño por horas', 'Inventé una alergia falsa', 'Desaparecí sin decir nada'], false, 2, 'es', ARRAY['😂'], true),
('¿Qué objeto de tu casa salvarías primero si hubiera un incendio?', 'mc', 'humor', ARRAY['El portátil con las fotos', 'Mi cargador de móvil', 'Los documentos importantes', 'La cartera'], false, 2, 'es', ARRAY['😂'], true),
('¿Quién del grupo tendría más éxito como protagonista de una serie turca?', 'mc', 'humor', ARRAY['El más dramático', 'El que llora con todo', 'El que tiene más secretos', 'El más intenso'], false, 2, 'es', ARRAY['😂'], true),
('¿Cuál sería tu primer tweet si volvieras a 2009?', 'mc', 'humor', ARRAY['"Acabo de crear mi primer tweet" sin ironía', 'Una frase filosófica random', 'RT a un famoso sin contexto', '"Estoy en el messenger" con emoticonos'], false, 2, 'es', ARRAY['😂'], true),
('¿Qué harías si tu madre te preguntase por qué llegaste tarde y habías estado en un festival?', 'mc', 'humor', ARRAY['Decir la verdad y rezar', 'Inventar un accidente ficticio', 'Culpar al transporte público', 'Decir que me secuestraron los aliens'], false, 2, 'es', ARRAY['😂'], true),
('¿Cuál es el peor momento para decir "ya voy" cuando alguien te espera?', 'mc', 'humor', ARRAY['Cuando lleva 1 hora esperando', 'Cuando está en la puerta ready', 'Cuando ya ha llamado 3 veces', 'Cuando tiene eluber en la puerta'], false, 2, 'es', ARRAY['😂'], true),
('¿Qué habilidad inútil sería más útil en una isla desierta?', 'mc', 'humor', ARRAY['Saber hacer macramé', 'Memorizar letras de canciones', 'Dibujar bien con los pies', 'Hablar en idiomas inventados'], false, 2, 'es', ARRAY['😂'], true),
('¿Quién del grupo sobreviviría mejor en un trabajo donde solo hablan en inglés?', 'mc', 'humor', ARRAY['El que ve series en VO', 'El que mezcla palabras en todos lados', 'El que pone subtítulos siempre', 'El que dice "no entiendo" sin parar'], false, 2, 'es', ARRAY['😂'], true),
('¿Cuál es el mejor excusa que has usado para no ir a un cumpleaños?', 'mc', 'humor', ARRAY['"Me encuentro mal" sin más', 'Fingí que tenía covid', 'Inventé una mudanza urgente', 'Dije que me olvidaba y actué surprised'], false, 2, 'es', ARRAY['😂'], true),
('¿Qué app debería existir pero no existe?', 'mc', 'humor', ARRAY['Traductor de excusas', 'Detector de baca de WhatsApp', 'Contador de tiempo perdido en redes', 'App que ligase por ti'], false, 2, 'es', ARRAY['😂'], true),
('¿Si el grupo fuera un reality show, quién sería el villano favorito del público?', 'mc', 'humor', ARRAY['El que cuenta secretos de otros', 'El que hace planes y no aparece', 'El que dice cosas nice pero piensa otra cosa', 'El que siempre llega tarde a propósito'], false, 2, 'es', ARRAY['😂'], true),
('¿Qué canción pondrías en una fiesta de personas mayores para shockearlas?', 'mc', 'humor', ARRAY['Una canción de reggaetón con baile', 'Algo de K-pop sin previo aviso', 'Un dembow a volumen suave', 'Un trap con autotune'], false, 2, 'es', ARRAY['😂'], true),
('¿Quién del grupo tendría más posibilidades de sobrevivir en la serie "El Hunde"?', 'mc', 'humor', ARRAY['El que tiene más miedo', 'El que se adapta a todo', 'El que se rinde primero', 'El que manipula a todos'], false, 2, 'es', ARRAY['😂'], true),
('¿Cuál sería la frase perfecta para un estado de WhatsApp después de un fracaso?', 'mc', 'humor', ARRAY['"Lesson learned" sin haber aprendido nada', '"Próximo capítulo" sin capítulo nuevo', '"No me arrepiento de nada" mintiendo', '"Mañana será mejor" todos los días'], false, 2, 'es', ARRAY['😂'], true),
('¿Qué harías si tuvieras que vivir un mes sin espejo?', 'mc', 'humor', ARRAY['Usar la cámara del móvil como espejo', 'Evitar todas las superficies reflectantes', 'Preguntar a desconocidos si tengo algo en la cara', 'Aceptar la incertidumbre como forma de vida'], false, 2, 'es', ARRAY['😂'], true),
('¿Cuál es la mentira más grande que has dicho y alguien se la creyó?', 'mc', 'humor', ARRAY['Que tenía una enfermedad rara', 'Que trabajaba para la NASA', 'Que conocía a un famoso', 'Que iba a mudar a otro país'], false, 2, 'es', ARRAY['😂'], true),
('¿Quién del grupo sería el primero en dejar el grupo de WhatsApp si se enfadan?', 'mc', 'humor', ARRAY['El más sensible', 'El que siempre está enfadado', 'El dramático', 'El que no puede vivir sin el grupo'], false, 2, 'es', ARRAY['😂'], true),
('¿Qué evento histórico habrías cambiado si pudieras?', 'mc', 'humor', ARRAY['La invención del WiFi con clave', 'Que los donuts no tuviesen grasa', 'La eliminación del cambio de hora', 'Que los ascensores siempre diesen al piso correcto'], false, 2, 'es', ARRAY['😂'], true),
-- humor: ranking questions (10)
('Ordena a los miembros del grupo por quién pagaría más por un café en una cafetería cara', 'ranking', 'humor', NULL, false, 4, 'es', ARRAY['😂'], true),
('Clasifica al grupo: ¿quién sería el mejor guía turístico en tu ciudad?', 'ranking', 'humor', NULL, false, 4, 'es', ARRAY['😂'], true),
('Ordena a los miembros del grupo por quién se perdería primero en un festival grande', 'ranking', 'humor', NULL, false, 4, 'es', ARRAY['😂'], true),
('¿Quién tiene más probabilidades de quedarse dormido en un cine? Ordénalos de mayor a menor riesgo', 'ranking', 'humor', NULL, false, 4, 'es', ARRAY['😂'], true),
('Clasifica al grupo por quién tardaría más en preparar una maleta para un viaje sorpresa', 'ranking', 'humor', NULL, false, 4, 'es', ARRAY['😂'], true),
('Ordena a los miembros del grupo: ¿quién montaría mejor una mentira creíble?', 'ranking', 'humor', NULL, false, 4, 'es', ARRAY['😂'], true),
('¿Quién sobreviviría más tiempo sin móvil? Ordénalos del 1 al {member_count}', 'ranking', 'humor', NULL, false, 4, 'es', ARRAY['😂'], true),
('Clasifica al grupo: ¿quién sería el primero en quejarse en un restaurante?', 'ranking', 'humor', NULL, false, 4, 'es', ARRAY['😂'], true),
('Ordena a los miembros por quién tiene más costumbre de decir "ya lo hago" y nunca lo hace', 'ranking', 'humor', NULL, false, 4, 'es', ARRAY['😂'], true),
('¿Quién sería el mejor chef del grupo? Clasifícalos del mejor al peor', 'ranking', 'humor', NULL, false, 4, 'es', ARRAY['😂'], true),
-- humor: free questions (15)
('¿Cuál es la mentira más absurda que le has dicho a tu madre y ella se la creyó?', 'free', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('Describe el peor mensaje que has enviado por error y cómo lo resolviste', 'free', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Alguna vez has fingido no conocer a alguien en público? Cuenta la historia completa', 'free', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Cuál es el objeto más extraño que has usado como truco para evitar algo?', 'free', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Qué canción te pone en modo bipolar emocional sin razón aparente?', 'free', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Has alguna vez entrado en un grupo equivocado y has hablado como si llevases años?', 'free', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Cuál es la situación más ridícula en la que te has puesto celoso/a?', 'free', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Qué famosa persona te ha dicho alguien que te pareces y cómo lo llevaste?', 'free', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Has alguna vez hablado en un idioma inventado para que alguien pensara que eras fluido?', 'free', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Cuál es la moda más absurda que has seguido sin dar explicaciones?', 'free', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Qué cosa te da pudor reconocer que haces en privado pero lo haces igual?', 'free', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Has creado alguna vez un personaje falso para impresionar a alguien del grupo? Cuenta su historia', 'free', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Cuál es el mejor descubrimiento que has hecho gracias a un error?', 'free', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Qué situación te ha hecho sospechar que el universo conspira contra ti?', 'free', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
('¿Cuál es el consejo más inútil que has dado y la persona lo siguió de verdad?', 'free', 'humor', NULL, false, 2, 'es', ARRAY['😂'], true),
-- atrevidas: vs questions (30, all anonymous)
('{member_A} vs {member_B}: ¿quién haría algo immoral por conseguir entradas para un concerto?', 'vs', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('{member_A} vs {member_B}: ¿quién besaría a alguien del grupo por dinero?', 'vs', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('{member_A} vs {member_B}: ¿quién contaría un secreto de los demás por sobrevivir?', 'vs', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('{member_A} vs {member_B}: ¿quién abandonaría a un amigo en una fiesta si implica ganar algo?', 'vs', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('{member_A} vs {member_B}: ¿quién sería capaz de destruir una amistad de 10 años por una noche?', 'vs', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('{member_A} vs {member_B}: ¿quién daría información falsa sobre sí mismo por encajar mejor?', 'vs', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('{member_A} vs {member_B}: ¿quién haría trampas en un juego solo para ganar contra {member_B}?', 'vs', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('{member_A} vs {member_B}: ¿quién criticaría a {member_B} a sus espaldas pero nunca cara a cara?', 'vs', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('{member_A} vs {member_B}: ¿quién aceptaría un trabajo que odia solo por la aprobación de alguien?', 'vs', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('{member_A} vs {member_B}: ¿quién fingiría un accidente para evitar una cena familiar?', 'vs', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('{member_A} vs {member_B}: ¿quién sería la primera persona en vender su privacidad por trending?', 'vs', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('{member_A} vs {member_B}: ¿quién miente mejor cuando le preguntan "¿estás bien?"?', 'vs', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('{member_A} vs {member_B}: ¿quién usaría el grupo para hacer daño a alguien que no está?', 'vs', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('{member_A} vs {member_B}: ¿quién haría algo que no quiere solo por no decepcionar a alguien?', 'vs', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('{member_A} vs {member_B}: ¿quién traicionaría la confianza de {member_B} por un secreto?', 'vs', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('{member_A} vs {member_B}: ¿quién se quedaría en una relación porque le da miedo estar solo?', 'vs', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('{member_A} vs {member_B}: ¿quién haría el papel de más feliz cuando en realidad está hundido?', 'vs', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('{member_A} vs {member_B}: ¿quién actuaría diferente en presencia de alguien que le atrae?', 'vs', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('{member_A} vs {member_B}: ¿quién tiene más fantasías que nunca compartiría con nadie?', 'vs', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('{member_A} vs {member_B}: ¿quién usaría el alcohol como excusa para hacer algo que no haría sobrio?', 'vs', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('{member_A} vs {member_B}: ¿quién elegiría la versión mejor de sí mismo en lugar de la real cada día?', 'vs', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('{member_A} vs {member_B}: ¿quién cambia de opinión sobre alguien dependiendo de lo que piense la gente?', 'vs', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('{member_A} vs {member_B}: ¿quién actúa como si no le importara cuando realmente le destruye?', 'vs', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('{member_A} vs {member_B}: ¿quién tiene una parte de su vida que oculta a todos en el grupo?', 'vs', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('{member_A} vs {member_B}: ¿quién diría "te quiero" solo para conseguir algo?', 'vs', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('{member_A} vs {member_B}: ¿quién pasaría la noche con alguien sabiendo que tiene pareja?', 'vs', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('{member_A} vs {member_B}: ¿quién roba comida del plato de otro cuando nadie mira?', 'vs', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('{member_A} vs {member_B}: ¿quién haría algo inapropiado en el trabajo solo por un ascenso?', 'vs', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('{member_A} vs {member_B}: ¿quién se aprovecha de la amabilidad de otra persona?', 'vs', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('{member_A} vs {member_B}: ¿quién ha sentido alivio cuando alguien del grupo se fue del lugar?', 'vs', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
-- atrevidas: free questions (70, all anonymous)
('¿Cuál es la cosa más cochina que has hecho en casa de otra persona?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Qué harías si encontraras el móvil de tu mejor amig@ con mensajes comprometidos?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Alguna vez has sentido atracción por el chico/chica de tu mejor amigo? Cuenta la historia completa', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Cuál es el secreto de tu pasado que nunca contarías en una primera cita?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Alguna vez has mentido sobre tu número de parejas para impresionar? ¿Cuál fue la mentira?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Qué es lo más infantil que sigues haciendo en secreto?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Alguna vez has sido infiel y nunca te han descubierto? ¿Cuentas cómo fue?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Cuál es la opinión más controversial que guardas sobre alguien del grupo?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Alguna vez has sentido que tu pareja te ve como un obstáculo y no como una persona?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Qué cosa te excita que nunca admitirías públicamente?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Has alguna vez disfrutado haciendo daño emocional a alguien aunque merecieseis estar juntos?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Cuál es la mayor incongruencia entre lo que dices y lo que realmente piensas?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Alguna vez has sentido que quieres dañar a alguien que te ha hecho daño?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Qué fantasía has tenido que nunca has podido cumplir y por qué?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Alguna vez has fingido un orgasmo para no hurt feelings?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Qué harías si tu pareja te confiesa que besó a otra persona pero no人造 nada?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Cuál es el nivel más bajo al que has llegado por atención?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Alguna vez has gozado observando el sufrimiento de alguien que te hizo daño?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Qué cosa guardas en tu móvil que sería devastador si alguien viese?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Has mentido en tu cv para conseguir un trabajo? ¿Sobre qué?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Cuál es el momento en que te sentiste más ashamed de ti mismo/a?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Alguna vez has sentido alivio cuando alguien close to you enfermó o tuvo un problema?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Qué es lo más raro que te excita y por qué?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Alguna vez has manipulado a alguien para conseguir algo que querías?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Qué frase has dicho en la cama que nunca admitirías en voz alta?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Alguna vez has stalkeado a alguien en redes y qué descubriste?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Cuál es tu más oscuro secreto que si se supiera arruinaría tu reputación?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Alguna vez has sido la persona que destruyó una amistad por intereses propios?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Qué harías si tu mejor amig@ se casa con alguien que tú también quieres?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Alguna vez has sentido que eres la causa de algo malo que le pasó a alguien?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Cuál es la versión de ti que nadie conoce y por qué la ocultas?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Alguna vez has disfrutado viendo a alguien fail después de que te tratase mal?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Qué cosa harías que nunca harías público si supieras que no te van a descubrir?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Cuál es la persona del grupo por la que serías capaz de destruirte a ti mismo?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Alguna vez has sido fake con alguien solo porque tenía poder o conexiones?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Qué cosa te ha hecho la persona que más querías que nunca has superado?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Alguna vez has sentido deseo por alguien de tu familia política?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Cuál es la verdad que nunca le has dicho a tu mejor amig@?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Alguna vez has hecho algo que te ashame y has cambiado tu forma de ser por ello?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Qué es lo más loco que has hecho por escapar de la realidad?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Alguna vez has sentido envidia de alguien del grupo por algo que no admitirías?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Cuál es tu forma de actuar cuando estás con alguien que no te atrae pero quieres mantener la paz?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Qué pasaría si alguien supiera la razón real por la que terminaste con tu ex?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Alguna vez has sido la persona que abandonó sin dar explicaciones?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Cuál es el pervert más grande que has tenido en un momento inapropiado?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Alguna vez has sentido que alguien del grupo te ve como inferior y aun así sigues ahí?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Qué cosa sobre ti misma/mismo te gustaría poder cambiar pero nunca lo admites?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Alguna vez has llorado por algo que no debería importarte pero te importaba?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Cuál es el favor más raro que alguien te ha pedido y tú has aceptado?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Alguna vez has hecho daño a alguien solo porque podías?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Qué es lo más embaucador que has hecho para evitar una discusión?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Alguna vez has sentido que alguien te utiliza y aun así sigues disponible?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Cuál es la experiencia más oscura que has vivido y nunca has compartido?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Alguna vez has tenido un crush en alguien que no deberías y cómo lo manejaste?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Qué harías si tu mejor amig@ te confiesa que ha estado durmiendo con tu pareja?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Cuál es la mentira que sigues contando aunque ya nadie se la cree?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Alguna vez has sido cruel con alguien que no lo merecía porque tenías un mal día?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Qué cosa te da miedo admitir que necesitas?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Alguna vez has sentido que tu éxito es una farsa y que no te lo mereces?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Cuál es el secreto mejor guardado de tu vida sexual que nunca has contado?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Alguna vez has tenido que fingir estar muerto por dentro para proteger a alguien?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Qué harías si supieras que alguien del grupo ha hecho algo truly terrible?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Alguna vez has sido la persona que destruyó la confianza de otra?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Cuál es la parte de ti que odias pero que no puedes cambiar?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Alguna vez has hecho algo que va contra tus valores solo por encajar?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Qué es lo más inconfesable que has hecho por amor?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Alguna vez has sentido que eres un impostor esperando a ser descubierto?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Cuál es tu forma de esconder lo que realmente sientes?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Alguna vez has utilizado tus lágrimas como arma para manipular?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true),
('¿Qué secreto guardarías para siempre aunque te destruyera por dentro?', 'free', 'atrevidas', NULL, true, 2, 'es', ARRAY['🌶️'], true);