-- questions_creative_en-UK.sql
-- 400 creative UK English questions for AuditUs
-- Categories: humor, habilidades, futuro, atrevidas, hipoteticas, vinculos, eventos, ia_custom

-- humor: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Who is most likely to try and pay for a pint with a cheeky wink?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who would survive the longest in a zombie apocalypse but only because they were hiding in the local pub?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who in the group is most likely to accidentally join a Morris dancing troupe while looking for the chippy?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who would be the first to get a tattoo of a Greggs sausage roll?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who is most likely to apologize to a mannequin after bumping into it?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who in the group is most likely to get their head stuck in some historic railings?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who would be the first to complain about the weather even if it was a perfect 22 degrees?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who is most likely to try and pet a fox while walking home from the pub?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who would win an award for "Most Likely to Forget Where They Left Their Tea"?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who in the group is most likely to start a fire while trying to make a proper fry-up?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('If the group was a heist crew, who would be the one that accidentally leaves the getaway car in a bus lane?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who is most likely to be seen on the news in the background of a rainy report holding a broken umbrella?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who would be the first to buy an air fryer and then talk about nothing else for a month?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who in the group is most likely to mistake a random person for a minor character from EastEnders?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who is most likely to say "sorry" to a self-checkout machine when it shouts at them?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who in the group has the highest risk of ordering a "mystery box" from a bloke they met at the pub?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who would be the first to try and enter a "Pull" door by pushing it until they look genuinely distressed?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who in the group is most likely to get a tattoo of a "Live, Laugh, Love" sign but in Comic Sans?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who would be the first to try and flirt with a contactless card reader?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who is most likely to become a viral meme for their "proper British" reaction to a slight inconvenience?', 'poll', 'humor', NULL, true, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who from {group_name} is most likely to end up on "LadBible" for a legendary fail?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who would survive on a desert island but only if they had a lifetime supply of Yorkshire Tea?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who is most likely to marry an AI that sounds like David Attenborough?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who would you call to bail you out of the nick, but they''d end up getting nicked too?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who from {group_name} has the most harmless but absolutely mental secrets?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who would be the best cult leader for a group that worships the Sunday Roast?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who has the most infectious and proper loud laugh in the group?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who is most likely to forget which bus they need to take and end up in a different county?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who from {group_name} is the biggest "drama queen" when they get a bit of "man flu"?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who would be the first to give up on a "no tea for 24 hours" challenge?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who would fall asleep in the middle of a loud Wetherspoons?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who would end up buying a "Lord" title from a dodgy Instagram ad?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who would forget their mum''s birthday but remember the exact date England won the World Cup?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who from {group_name} would cry because they dropped their kebab after a night out?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who would try to ask for a discount at Harrods?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who would wear a "I Love London" shirt in the middle of Manchester and wonder why people are staring?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who would collect something as random as Nando''s receipts?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who would be the first to fall for a "U OK M8?" prank call?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who from {group_name} would order a fancy salad at a pub and then steal everyone''s chips?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who would be the first to get lost in a small village despite having a phone?', 'poll', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Proper clumsy battle: {member_A} or {member_B}?', 'vs', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who has the most questionable "guilty pleasure" music taste: {member_A} or {member_B}?', 'vs', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who would take longer to notice they are wearing two different socks: {member_A} or {member_B}?', 'vs', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who is the group''s "grandad" when it comes to technology: {member_A} or {member_B}?', 'vs', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who would win a pie-eating contest: {member_A} or {member_B}?', 'vs', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who would be more embarrassing dancing at a local fete: {member_A} or {member_B}?', 'vs', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who would be the first to get scared by a pigeon: {member_A} or {member_B}?', 'vs', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who is more likely to talk to themselves while looking for a "lost" item in their own pocket: {member_A} or {member_B}?', 'vs', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who is more dangerous with a pint in their hand: {member_A} or {member_B}?', 'vs', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true),
('Who would be the best at a "proper" British accent from another region: {member_A} or {member_B}?', 'vs', 'humor', NULL, false, 2, 'en-UK', ARRAY['😂']::text[], true);

-- (I will generate the rest of the categories for en-UK now...)

-- habilidades: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Who in the group can assemble IKEA furniture without losing their rag or having leftover bits?', 'poll', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('Who has the best internal compass and could find their way home from London after a night out?', 'poll', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('Who would be the best at haggling for a bargain at a car boot sale?', 'poll', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('Who in the group would survive best in the Peak District with only a tin of beans?', 'poll', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('Who is the fastest at texting without even looking at their phone?', 'poll', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('Who in the group has the gift of the gab and could talk their way out of a parking fine?', 'poll', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('Who would be the best drone pilot in the group?', 'poll', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('Who in the group is a secret math whiz but lets everyone else work out the bill?', 'poll', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('Who has the most patience for untangling a knotty mess of Christmas lights?', 'poll', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('Who would be the best "MasterChef" with whatever random bits are in the cupboard?', 'poll', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('Who in the group could win a spelling bee after three pints?', 'poll', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('Who can learn a TikTok dance before the kettle has boiled?', 'poll', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('Who in the group would be the best private investigator (or just a proper nosy parker)?', 'poll', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('Who has the best knack for fixing a telly that''s on the blink?', 'poll', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('Who in the group would win a chess match against a computer?', 'poll', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('Who has the steadiest hand for playing Jenga after a few bevvy''s?', 'poll', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('Who in the group would be the best "hardman" in a scrap?', 'poll', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('Who can do a proper good "Brummie" or "Scouse" accent?', 'poll', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('Who in the group has the best eye for a "proper" Instagram snap?', 'poll', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('Who would be the best in a secret talent show?', 'poll', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('What grade would you give {member_A}''s ability to save a few quid? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('From 1 to 10, how good is {member_A}''s aim at darts?', 'scale', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('How well does {member_A} tell stories at the pub? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('How tech-savvy is {member_A}? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('From 1 to 10, how much discipline does {member_A} have when it comes to biscuits?', 'scale', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('How fast do you think {member_A} could learn to play the drums? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('What grade would you give {member_A} for driving a manual car? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('From 1 to 10, how well does {member_A} bluff during a game?', 'scale', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('How well would {member_A} organize a Sunday Roast for 10 people? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('What level of "DIY expert" is {member_A}? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('Who would win in a political debate: {member_A} or {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('Who would last longer on a rainy hike: {member_A} or {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('Who is more pro at pub quizzes: {member_A} or {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('Who has more "character" in their handwriting: {member_A} or {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('Who would win at a game of Pool: {member_A} or {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('Who is more creative at "making do" with what they have: {member_A} or {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('Who has more "street cred" when dressing up: {member_A} or {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('Who solves a Crossword faster: {member_A} or {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('Who would be a better MI5 agent: {member_A} or {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('Who has a better ear for a "banger" of a tune: {member_A} or {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'en-UK', ARRAY['💪']::text[], true),
('Rank the group by who is most likely to win a reality show.', 'ranking', 'habilidades', NULL, false, 3, 'en-UK', ARRAY['💪']::text[], true),
('Classify the group from best to worst at making a "proper" brew.', 'ranking', 'habilidades', NULL, false, 3, 'en-UK', ARRAY['💪']::text[], true),
('Rank by who has the most ability to focus when the pub is rammed.', 'ranking', 'habilidades', NULL, false, 3, 'en-UK', ARRAY['💪']::text[], true),
('Classify the group according to who would drive a Mini better in London.', 'ranking', 'habilidades', NULL, false, 3, 'en-UK', ARRAY['💪']::text[], true),
('Rank by who is most skilled at fixing things with just a bit of tape.', 'ranking', 'habilidades', NULL, false, 3, 'en-UK', ARRAY['💪']::text[], true),
('Classify the group by who has more memory for useless facts.', 'ranking', 'habilidades', NULL, false, 3, 'en-UK', ARRAY['💪']::text[], true),
('Rank by who is fastest at learning a new board game.', 'ranking', 'habilidades', NULL, false, 3, 'en-UK', ARRAY['💪']::text[], true),
('Classify the group by who has more ease for learning "Cockney Rhyming Slang".', 'ranking', 'habilidades', NULL, false, 3, 'en-UK', ARRAY['💪']::text[], true),
('Rank by who is better at keeping their cool in a queue.', 'ranking', 'habilidades', NULL, false, 3, 'en-UK', ARRAY['💪']::text[], true),
('Classify the group according to who would be the best at Poker.', 'ranking', 'habilidades', NULL, false, 3, 'en-UK', ARRAY['💪']::text[], true);

-- futuro: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Who in the group will be the first to move to the countryside and start a farm?', 'poll', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('Who will be the first to be featured on a "Where are they now?" show?', 'poll', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('Who in the group will have a plaque on a park bench one day?', 'poll', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('Who will be the first to become a self-made millionaire but still shops at Aldi?', 'poll', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('Who in the group will end up being a regular on a daytime talk show?', 'poll', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('Who will be the first to move to Spain and open a bar?', 'poll', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('Who in the group will end up being the CEO of a "proper" British company?', 'poll', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('Who will be the first to "cash in" and retire in the Cotswolds?', 'poll', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('Who in the group will get an OBE for something absolutely random?', 'poll', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('Who will be the first to live in a house with its own library?', 'poll', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('Who in the group will have enough kids to start their own football team?', 'poll', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('Who will be the first to go "off-grid" and live in a yurt?', 'poll', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('Who in the group will be invited to a Garden Party at the Palace?', 'poll', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('Who will be the first to live in a "posh" part of London?', 'poll', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('Who in the group will end up being a "National Treasure"?', 'poll', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('Who will be the first to do a "mid-life crisis" trip around the world?', 'poll', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('Who in the group will have their own brand of "artisan" gin?', 'poll', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('Who will be the first to give up alcohol and become a "wellness" guru?', 'poll', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('Who in the group will be remembered for their "legendary" status in the local?', 'poll', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('Who will be the first to own a fleet of classic British cars?', 'poll', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('How likely is {member_A} to be a famous presenter on the BBC? (0-100%)', 'scale', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('From 1 to 10, how much do you think {member_A}''s accent will change in 10 years?', 'scale', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('What level of success do you think {member_A} will achieve in the city? (1-10)', 'scale', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('From 1 to 10, how much do you think {member_A} will stick to their British roots?', 'scale', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('How likely is {member_A} to become a local councillor? (1-10)', 'scale', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('What grade would you give the future success of {member_A}''s "side hustle"? (1-10)', 'scale', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('From 1 to 10, how much do you think {member_A} will stay the same person?', 'scale', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('How likely is {member_A} to win a massive accumulator on the football? (1-10)', 'scale', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('What level of "peace and quiet" do you think {member_A} will want in their 60s? (1-10)', 'scale', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('From 1 to 10, how much do you think {member_A} will miss these days?', 'scale', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('Who will have a better car in 10 years: {member_A} or {member_B}?', 'vs', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('Who will be more "chilled out" when they retire: {member_A} or {member_B}?', 'vs', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('Who will have a more "senior" role in their firm: {member_A} or {member_B}?', 'vs', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('Who will be more "in the know" about current affairs: {member_A} or {member_B}?', 'vs', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('Who will visit more "exotic" places: {member_A} or {member_B}?', 'vs', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('Who will be the first to host the group for a big dinner: {member_A} or {member_B}?', 'vs', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('Who will become a better cook with age: {member_A} or {member_B}?', 'vs', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('Who will understand "future slang" better: {member_A} or {member_B}?', 'vs', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('Who will have a bigger garden: {member_A} or {member_B}?', 'vs', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('Who will live in a "proper" quiet village: {member_A} or {member_B}?', 'vs', 'futuro', NULL, false, 2, 'en-UK', ARRAY['🔮']::text[], true),
('Rank the group by who will be the most "successful" in the city.', 'ranking', 'futuro', NULL, false, 3, 'en-UK', ARRAY['🔮']::text[], true),
('Classify the group by who will achieve their life goals first.', 'ranking', 'futuro', NULL, false, 3, 'en-UK', ARRAY['🔮']::text[], true),
('Rank according to who will have a more "eventful" life.', 'ranking', 'futuro', NULL, false, 3, 'en-UK', ARRAY['🔮']::text[], true),
('Classify the group according to who will stay more "fit" as they age.', 'ranking', 'futuro', NULL, false, 3, 'en-UK', ARRAY['🔮']::text[], true),
('Rank by who will make more trips to the seaside in the next 10 years.', 'ranking', 'futuro', NULL, false, 3, 'en-UK', ARRAY['🔮']::text[], true),
('Classify the group according to who will have a more "laid back" retirement.', 'ranking', 'futuro', NULL, false, 3, 'en-UK', ARRAY['🔮']::text[], true),
('Rank by who will be the first to settle down properly.', 'ranking', 'futuro', NULL, false, 3, 'en-UK', ARRAY['🔮']::text[], true),
('Classify the group by who will contribute more to their local community.', 'ranking', 'futuro', NULL, false, 3, 'en-UK', ARRAY['🔮']::text[], true),
('Rank according to who will keep their British "wit" the longest.', 'ranking', 'futuro', NULL, false, 3, 'en-UK', ARRAY['🔮']::text[], true),
('Classify the group according to who will live the most "proper" British life.', 'ranking', 'futuro', NULL, false, 3, 'en-UK', ARRAY['🔮']::text[], true);

-- (Adding the remaining 5 categories for en-UK...)

-- atrevidas: 50 questions (anonymous)
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('What is the biggest lie you''ve ever told to avoid a date with a proper "dodgy" character?', 'free', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Who in the group do you think has the "weirdest" kinks behind closed doors?', 'poll', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Have you ever pretended to like someone just to get a free drink at the pub?', 'free', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Who in this group would you give a cheeky snog to if we were playing Spin the Bottle?', 'poll', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('What is the most "out there" place where you''ve had a bit of action?', 'free', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Have you had a "not-so-innocent" dream about someone in this group?', 'free', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('What is your "darkest" fantasy that you''d never tell your nan?', 'free', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Have you ever "ghosted" someone you actually found quite fit?', 'free', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Who in the group do you think is a proper "player" by nature?', 'poll', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('What is the boldest thing you''ve done for someone who was a "10" in your eyes?', 'free', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Have you ever sent a "cheeky" photo and then felt proper "mortified" about it?', 'free', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Who in the group do you think spends the most time swiping on Tinder after a few pints?', 'poll', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Have you ever dated two people at the same time and managed not to get caught?', 'free', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Who in this group would you take for a "quiet weekend" in a remote cottage?', 'poll', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('What is the most explicit message you''ve ever accidentally sent to your family WhatsApp?', 'free', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Have you ever fancied the partner of someone in the group?', 'free', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Who in the group do you think has the most "experimental" side?', 'poll', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('What was your most "cringe" moment in the bedroom?', 'free', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Have you ever been caught "in the act" by your parents or housemates?', 'free', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Who in the group do you think is a proper "beast" in private?', 'poll', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Have you ever used "toys" and what''s the most random thing you''ve used?', 'free', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Who in the group do you think has had the most "pullan"?', 'poll', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('What is the biggest lie you''ve told to get someone home with you?', 'free', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Who in this group would you trust with your unlocked phone for an hour?', 'poll', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Have you ever had a threesome or is it on your "bucket list"?', 'free', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Who in the group do you think is most likely to have a "one-night stand" on holiday?', 'poll', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('What''s a secret you have about an ex that would make us all go "mental"?', 'free', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Have you ever dated someone old enough to be your parent?', 'free', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Who in the group do you think "bigs themselves up" more than they actually do?', 'poll', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('What is the "weirdest" thing you''ve searched for on the internet after midnight?', 'free', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Have you ever felt a "spark" for someone of the same sex (if you are straight)?', 'free', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Who in the group do you think has a "secret" second life online?', 'poll', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('What is the most embarrassing thing that happened when you were "starkers"?', 'free', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Have you ever had "phone sex" or sent proper "filthy" messages?', 'free', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Who in the group do you think is the most "repressed" in bed?', 'poll', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('What part of your body is your secret "weak spot"?', 'free', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Have you ever paid for a "bit of fun" or been offered money for it?', 'free', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Who in the group do you think would forgive an "affair" the fastest?', 'poll', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('What is the "thing" you like that you are most embarrassed to admit?', 'free', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Have you ever recorded a "home video" and where is it now?', 'free', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Who in the group do you think is most "up for anything" in bed?', 'poll', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('What public place in the UK would you most like to "do the deed" in?', 'free', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Have you ever had a "workplace romance" that ended in disaster?', 'free', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Who in the group do you think is the "hottest" right now?', 'poll', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('What was the "craziest" thing you did when you were proper "pissed"?', 'free', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Have you ever met an ex for a "quick catch up" that turned into more?', 'free', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Who in the group do you think is a "secret romantic" who loves rom-coms?', 'poll', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('What is the "wildest" thing you''ve ever done on a night out?', 'free', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Have you ever been in an "open" relationship or "friends with benefits"?', 'free', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true),
('Who in this group would you invite for a "bit of a session" if you were both single?', 'poll', 'atrevidas', NULL, true, 2, 'en-UK', ARRAY['🌶️']::text[], true);

-- hipoteticas: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('If you could have a superpower, but only once every 6 months, what would it be?', 'mc', 'hipoteticas', ARRAY['Invisibility 12h', 'Travel to past 30 min', 'Know thoughts 1h', 'Fly for 2h'], false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('If the group got stranded on a remote Scottish island, who would be the one to start the fire?', 'poll', 'hipoteticas', NULL, false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('If you could live in a British sitcom for a week, which one would you choose?', 'mc', 'hipoteticas', ARRAY['Peep Show', 'The Inbetweeners', 'Gavin & Stacey', 'The IT Crowd'], false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('If you had to choose someone from the group to defend you in a "proper" legal battle, who would it be?', 'poll', 'hipoteticas', NULL, false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('If you were given £5 million to never eat a Sunday Roast again in your life, would you do it?', 'mc', 'hipoteticas', ARRAY['Yes, obviously', 'No way', 'Only if I can eat Nando''s', 'I''d think about it a lot'], false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('If the group was a cricket team, who would be the captain?', 'poll', 'hipoteticas', NULL, false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('If you could know exactly when you were going to kick the bucket, would you want to know?', 'mc', 'hipoteticas', ARRAY['Yes, to spend every penny', 'No, how scary', 'Only if I can change it', 'I prefer the surprise'], false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('If you had to choose someone from the group to take care of you if you had a proper "man flu", who would it be?', 'poll', 'hipoteticas', NULL, false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('If you could speak any language fluently right now, which one would you want?', 'mc', 'hipoteticas', ARRAY['Japanese', 'French', 'German', 'Russian'], false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('If the group was in a zombie apocalypse, who would be the first to sacrifice themselves so the rest could get to the pub?', 'poll', 'hipoteticas', NULL, false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('If you could teleport to anywhere you wanted right now, where would you go?', 'mc', 'hipoteticas', ARRAY['A beach in Maldives', 'London for a shopping spree', 'Top of the Shard', 'My bed to sleep'], false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('If you had to trust your bank PIN to someone in the group, who would it be?', 'poll', 'hipoteticas', NULL, false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('If you could bring back someone famous for a "proper" night out, who would it be?', 'mc', 'hipoteticas', ARRAY['Amy Winehouse', 'Princess Diana', 'David Bowie', 'Freddie Mercury'], false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('If the group was a reality show, who would win for being the most "genuine"?', 'poll', 'hipoteticas', NULL, false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('If you could erase a proper "cringe" moment from your past, which one would it be?', 'free', 'hipoteticas', NULL, false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('If you had to choose someone from the group to hide a "body" (hypothetically!), who would it be?', 'poll', 'hipoteticas', NULL, false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('If you could be immortal but had to stay in the UK forever, would you accept?', 'mc', 'hipoteticas', ARRAY['Yes, for sure', 'No, how boring', 'Only if I don''t age', 'Only if my mates are too'], false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('If the group started a business, who would be the one "minding the shop"?', 'poll', 'hipoteticas', NULL, false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('If you could erase a sad memory from your head, would you do it?', 'free', 'hipoteticas', NULL, false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('If you had to live in a shared flat with someone from the group for a year, who would it be?', 'poll', 'hipoteticas', NULL, false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('What is the probability that aliens visit the UK soon? (0-10)', 'scale', 'hipoteticas', NULL, false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('From 1 to 10, how much do you think robots will take over our jobs?', 'scale', 'hipoteticas', NULL, false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('How happy would we be in a world without social media? (1-10)', 'scale', 'hipoteticas', NULL, false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('From 1 to 10, how much do you believe in ghosts in old British pubs?', 'scale', 'hipoteticas', NULL, false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('How likely do you think it is that we live in a simulation? (1-10)', 'scale', 'hipoteticas', NULL, false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('From 1 to 10, how much would you give to save the planet?', 'scale', 'hipoteticas', NULL, false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('How important do you think it is to colonize Mars? (1-10)', 'scale', 'hipoteticas', NULL, false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('From 1 to 10, how much do you think the future is already "sorted"?', 'scale', 'hipoteticas', NULL, false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('How possible do you see time travel some day? (1-10)', 'scale', 'hipoteticas', NULL, false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('From 1 to 10, how much does AI scare you?', 'scale', 'hipoteticas', NULL, false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('Who would be a better leader in a crisis: {member_A} or {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('Who would survive better living in Victorian London: {member_A} or {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('Who would make friends with an alien first: {member_A} or {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('Who would choose to leave the Matrix: {member_A} or {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('Who would be a better astronaut: {member_A} or {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('Who would stand up for the group in a "situation": {member_A} or {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('Who would be the best representative of the UK to the world: {member_A} or {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('Who would adapt better to living in the middle of nowhere: {member_A} or {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('Who would win in a "slanging match" with a taxi driver: {member_A} or {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('Who would believe first that all this is a dream: {member_A} or {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'en-UK', ARRAY['🧠']::text[], true),
('Rank the group according to who would survive more in a "slasher" flick.', 'ranking', 'hipoteticas', NULL, false, 3, 'en-UK', ARRAY['🧠']::text[], true),
('Classify the group from more to less suspicious of being a secret agent.', 'ranking', 'hipoteticas', NULL, false, 3, 'en-UK', ARRAY['🧠']::text[], true),
('Rank according to who would be the best strategist in a "crisis".', 'ranking', 'hipoteticas', NULL, false, 3, 'en-UK', ARRAY['🧠']::text[], true),
('Classify the group according to who would be most useful if the grid goes down.', 'ranking', 'hipoteticas', NULL, false, 3, 'en-UK', ARRAY['🧠']::text[], true),
('Rank by who would volunteer to go to Mars first.', 'ranking', 'hipoteticas', NULL, false, 3, 'en-UK', ARRAY['🧠']::text[], true),
('Classify the group according to who would invent the cure for a new "bug".', 'ranking', 'hipoteticas', NULL, false, 3, 'en-UK', ARRAY['🧠']::text[], true),
('Rank by who would be the best negotiator with an alien race.', 'ranking', 'hipoteticas', NULL, false, 3, 'en-UK', ARRAY['🧠']::text[], true),
('Classify the group according to who would keep calm in a "panic".', 'ranking', 'hipoteticas', NULL, false, 3, 'en-UK', ARRAY['🧠']::text[], true),
('Rank by who would be most creative inventing new rules for the group.', 'ranking', 'hipoteticas', NULL, false, 3, 'en-UK', ARRAY['🧠']::text[], true),
('Classify the group according to who would be the best guide in a post-apocalyptic UK.', 'ranking', 'hipoteticas', NULL, false, 3, 'en-UK', ARRAY['🧠']::text[], true);

-- vinculos: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Who in the group is the one who always organizes the "proper" get-togethers?', 'poll', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('Who in the group gave you the best advice when you were proper "gutted"?', 'poll', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('Who is the most loyal mate you know in this group?', 'poll', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('Who in the group is always there when you need a "proper" heart-to-heart?', 'poll', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('Who in this group would you trust with your house keys for a month?', 'poll', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('Who is the one who has grown the most since we first met?', 'poll', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('Who in the group has the "purest" heart of all?', 'poll', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('Who in this group do you laugh with until you can''t breathe?', 'poll', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('Who in this group would you call if you were in proper "shtook"?', 'poll', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('Who in the group knows how to listen better without being "judgy"?', 'poll', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('Who is the one who keeps the group chat from dying?', 'poll', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('Who in this group do you admire most for their "vibe"?', 'poll', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('Who in the group is the most "blunt", even if it hurts?', 'poll', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('Who is the coolest person to spend a quiet afternoon with?', 'poll', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('Who in this group would you apologize to first if you had a proper "falling out"?', 'poll', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('Who in the group is the one who "mothers" everyone else?', 'poll', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('Who is the person who motivates you most to "get your act together"?', 'poll', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('Who in this group would you tell something proper "embarrassing" to?', 'poll', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('Who in the group is the most attentive with birthday cards?', 'poll', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('Who is the person who brings the most "positive energy" to the group?', 'poll', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('From 1 to 10, how much do you trust {member_A}?', 'scale', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('How good is the connection you have with {member_A}? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('What place does {member_A} occupy in your list of "besties"? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('From 1 to 10, how much do you think {member_A} truly "gets" you?', 'scale', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('What grade would you give the loyalty of {member_A} to the group? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('How good is {member_A} at being a "proper" mate? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('From 1 to 10, how much do you enjoy a proper "natter" with {member_A}?', 'scale', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('How important is it for you to stay mates with {member_A} forever? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('What level of honesty do you think {member_A} has with you? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('From 1 to 10, how much do you think the group would change if {member_A} wasn''t around?', 'scale', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('Who takes care of their mates more: {member_A} or {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('Who do you prefer to talk to when you''re "down in the dumps": {member_A} or {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('Who has more patience with the group''s "antics": {member_A} or {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('Who is more thoughtful with their friendships: {member_A} or {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('Who would you call to have a "proper" cry: {member_A} or {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('Who knows you better when you are proper "mardy": {member_A} or {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('Who is more "real" with you: {member_A} or {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('Who do you feel more "yourself" with: {member_A} or {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('Who would forgive a "blunder" easier: {member_A} or {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('Who is more "there" for people: {member_A} or {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'en-UK', ARRAY['💛']::text[], true),
('Rank the group according to who is the best at keeping a secret.', 'ranking', 'vinculos', NULL, false, 3, 'en-UK', ARRAY['💛']::text[], true),
('Classify the group by their level of "mate-ship".', 'ranking', 'vinculos', NULL, false, 3, 'en-UK', ARRAY['💛']::text[], true),
('Rank according to who would help you out of a "scrape" first.', 'ranking', 'vinculos', NULL, false, 3, 'en-UK', ARRAY['💛']::text[], true),
('Classify the group according to who is the most loyal.', 'ranking', 'vinculos', NULL, false, 3, 'en-UK', ARRAY['💛']::text[], true),
('Rank by who gives the most "no-nonsense" advice.', 'ranking', 'vinculos', NULL, false, 3, 'en-UK', ARRAY['💛']::text[], true),
('Classify the group according to who cares most about everyone else.', 'ranking', 'vinculos', NULL, false, 3, 'en-UK', ARRAY['💛']::text[], true),
('Rank by who is the most fun for a "weekend away".', 'ranking', 'vinculos', NULL, false, 3, 'en-UK', ARRAY['💛']::text[], true),
('Classify the group by who is easiest to "make up" with.', 'ranking', 'vinculos', NULL, false, 3, 'en-UK', ARRAY['💛']::text[], true),
('Rank according to who brings the most "calm" to the group.', 'ranking', 'vinculos', NULL, false, 3, 'en-UK', ARRAY['💛']::text[], true),
('Classify the group by who has been the best "find" as a mate.', 'ranking', 'vinculos', NULL, false, 3, 'en-UK', ARRAY['💛']::text[], true);

-- eventos: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Who in the group is the one who always organizes the Christmas "do"?', 'poll', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('Who is more likely to "no-show" because they fell asleep on the sofa?', 'poll', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('Who in this group would you trust to plan a "proper" bender?', 'poll', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('Who in the group is the first to say "let''s go to Magaluf" (or somewhere mental)?', 'poll', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('Who is the one who always arrives "fashionably late" with a bag of ice?', 'poll', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('Who in the group is the most "hardcore" party-goer?', 'poll', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('Who is the one who makes the best "proper" cocktails at a house party?', 'poll', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('Who in the group would you choose to be the DJ at your wedding?', 'poll', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('Who in the group is always taking "proper" selfies at every occasion?', 'poll', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('Who is the one who always takes charge of the "barbecue" (even if it''s raining)?', 'poll', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('Who in the group is the most likely to end up singing karaoke at 3am?', 'poll', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('Who in this group would you ask to go to Glastonbury with?', 'poll', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('Who in the group is the one who always finds the "secret" bars?', 'poll', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('Who is the "early bird" who always wants to leave the club at midnight?', 'poll', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('Who in this group would you trust to book the "group holiday"?', 'poll', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('Who in the group is the most fun for a "city break"?', 'poll', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('Who is the one who always proposes going to a "proper" old man''s pub?', 'poll', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('Who in this group would you choose to go to a theme park with?', 'poll', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('Who in the group is the most likely to get "properly" lost at a festival?', 'poll', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('Who is the one who organizes the most "thoughtful" surprises?', 'poll', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('From 1 to 10, how much do you like a "spontaneous" night out?', 'scale', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('How "hyped" would you rate our group outings? (1-10)', 'scale', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('How much do you value meeting up for a "proper" catch-up? (1-10)', 'scale', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('From 1 to 10, how well do you think we''d do on a "lads/girls" holiday?', 'scale', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('How would you rate the group''s "time-keeping"? (1-10)', 'scale', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('How much are you looking forward to the next "big night out"? (1-10)', 'scale', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('From 1 to 10, how much do you like being the "organizer"?', 'scale', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('How "nightmare" is it to get everyone to agree on a date? (1-10)', 'scale', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('How important is it to you to celebrate "every" occasion? (1-10)', 'scale', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('From 1 to 10, how much do you miss the "banter" when we haven''t met?', 'scale', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('Who is a better "event planner": {member_A} or {member_B}?', 'vs', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('Who do you prefer to go on a "day trip" with: {member_A} or {member_B}?', 'vs', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('Who lasts longer on a "night on the tiles": {member_A} or {member_B}?', 'vs', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('Who comes up with the most "mental" plans: {member_A} or {member_B}?', 'vs', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('Who has better taste for a "proper" gastropub: {member_A} or {member_B}?', 'vs', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('Who is more "on the ball" with time: {member_A} or {member_B}?', 'vs', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('Who would you trust with the "kitty" for the night: {member_A} or {member_B}?', 'vs', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('Who is more fun at a "proper" Karaoke: {member_A} or {member_B}?', 'vs', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('Who takes the best "unfiltered" photos: {member_A} or {member_B}?', 'vs', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('Who is more likely to be the "designated driver" (happily): {member_A} or {member_B}?', 'vs', 'eventos', NULL, false, 2, 'en-UK', ARRAY['🎉']::text[], true),
('Rank the group according to who brings the most "banter".', 'ranking', 'eventos', NULL, false, 3, 'en-UK', ARRAY['🎉']::text[], true),
('Classify the group by who is most "up for it".', 'ranking', 'eventos', NULL, false, 3, 'en-UK', ARRAY['🎉']::text[], true),
('Rank according to who is more likely to handle the "bookings".', 'ranking', 'eventos', NULL, false, 3, 'en-UK', ARRAY['🎉']::text[], true),
('Classify the group according to who is the most "punctual".', 'ranking', 'eventos', NULL, false, 3, 'en-UK', ARRAY['🎉']::text[], true),
('Rank by who has the best "party playlist".', 'ranking', 'eventos', NULL, false, 3, 'en-UK', ARRAY['🎉']::text[], true),
('Classify the group according to who makes friends fastest at the bar.', 'ranking', 'eventos', NULL, false, 3, 'en-UK', ARRAY['🎉']::text[], true),
('Rank by who is the "paparazzi" of the group.', 'ranking', 'eventos', NULL, false, 3, 'en-UK', ARRAY['🎉']::text[], true),
('Classify the group by who is more "thoughtful" with gifts.', 'ranking', 'eventos', NULL, false, 3, 'en-UK', ARRAY['🎉']::text[], true),
('Rank according to who is more "easy-going" on a trip.', 'ranking', 'eventos', NULL, false, 3, 'en-UK', ARRAY['🎉']::text[], true),
('Classify the group by who has organized the "best" night ever.', 'ranking', 'eventos', NULL, false, 3, 'en-UK', ARRAY['🎉']::text[], true);

-- ia_custom: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Who in the group is the first to use AI to write a birthday card?', 'poll', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('Who is more likely to end up "dating" a robot?', 'poll', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('Who in this group would you trust to build you a "smart home"?', 'poll', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('Who in the group is proper "paranoid" about robots taking over?', 'poll', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('Who is the one who always knows about the latest tech "gimmicks"?', 'poll', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('Who in the group would be the first to get a brain chip to "boost" their memory?', 'poll', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('Who is the one who uses AI to "skive off" work?', 'poll', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('Who would you choose to be the first Brit on Mars?', 'poll', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('Who in the group is proper "old school" and hates AI art?', 'poll', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('Who is the one who thinks everything on the internet is a "Deepfake"?', 'poll', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('Who in the group would be the first to have a "digital twin"?', 'poll', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('Who would you ask for help to "tech-up" your life?', 'poll', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('Who in the group is most "chilled" about the future of AI?', 'poll', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('Who already talks to Siri like she''s a "proper" mate?', 'poll', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('Who in this group would you trust with your "digital privacy"?', 'poll', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('Who in the group is "gutted" because they think AI will take their job?', 'poll', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('Who is the one who uses AI to "fix up" their social media photos?', 'poll', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('Who would you choose to lead the "Resistance" against the machines?', 'poll', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('Who in the group is more likely to "code" their own robot helper?', 'poll', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('Who can''t tell if a "DM" was written by a human or a bot anymore?', 'poll', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('From 1 to 10, how much do you trust a "ChatBot"?', 'scale', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('How much has AI "sorted" your life out so far? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('How important is it to have "proper" rules for AI? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('From 1 to 10, how likely is a "Terminator" scenario?', 'scale', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('What grade would you give your "tech-savviness"? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('How much do you want a robot to do the "chores" for you? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('From 1 to 10, how much do you think AI will "save" the NHS?', 'scale', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('How much fear do you have about the "algorithm"? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('How important is it that the government "gets a grip" on AI? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('From 1 to 10, how much do you think robots can "feel"?', 'scale', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('Who is more of a "tech-head": {member_A} or {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('Who is more "freaked out" by the future: {member_A} or {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('Who uses AI more in their "daily grind": {member_A} or {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('Who would "befriend" a robot first: {member_A} or {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('Who is more "skeptical" of all this tech: {member_A} or {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('Who would survive better without a "Smartphone": {member_A} or {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('Who would trust an AI "surgeon" more: {member_A} or {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('Who would be better at "outsmarting" a bot: {member_A} or {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('Who would suspect first that we''re in a "Matrix": {member_A} or {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('Who thinks AI is the "best thing since sliced bread": {member_A} or {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'en-UK', ARRAY['🤖']::text[], true),
('Rank the group by who is most "glued" to their phone.', 'ranking', 'ia_custom', NULL, false, 3, 'en-UK', ARRAY['🤖']::text[], true),
('Classify the group by their level of "tech-optimism".', 'ranking', 'ia_custom', NULL, false, 3, 'en-UK', ARRAY['🤖']::text[], true),
('Rank according to who would use AI to "pull" first.', 'ranking', 'ia_custom', NULL, false, 3, 'en-UK', ARRAY['🤖']::text[], true),
('Classify the group according to who is most "private" online.', 'ranking', 'ia_custom', NULL, false, 3, 'en-UK', ARRAY['🤖']::text[], true),
('Rank by who would buy the first "flying car".', 'ranking', 'ia_custom', NULL, false, 3, 'en-UK', ARRAY['🤖']::text[], true),
('Classify the group according to who has more "curiosity" about the future.', 'ranking', 'ia_custom', NULL, false, 3, 'en-UK', ARRAY['🤖']::text[], true),
('Rank by who thinks AI will "sort out" the world.', 'ranking', 'ia_custom', NULL, false, 3, 'en-UK', ARRAY['🤖']::text[], true),
('Classify the group by who is most likely to "thank" Alexa.', 'ranking', 'ia_custom', NULL, false, 3, 'en-UK', ARRAY['🤖']::text[], true),
('Rank according to who thinks robots are a "proper" threat.', 'ranking', 'ia_custom', NULL, false, 3, 'en-UK', ARRAY['🤖']::text[], true),
('Classify the group by who has used AI for the most "mental" thing.', 'ranking', 'ia_custom', NULL, false, 3, 'en-UK', ARRAY['🤖']::text[], true);
