-- questions_creative_pt.sql
-- 400 creative Portuguese questions for AuditUs
-- Categories: humor, habilidades, futuro, atrevidas, hipoteticas, vinculos, eventos, ia_custom

-- humor: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Quem no grupo ri mais provavelmente da própria piada antes que qualquer pessoa entenda?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem sobreviveria mais tempo a um apocalipse zumbi, só porque se escondeu no boteco mais próximo?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem no grupo levaria mais provavelmente salgadinho de supermercado para um jantar e diria que é "artesanal"?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem ganharia uma batalha de dança entre {member_A} e {member_B}?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem é o culpado oficial do "respondo depois" no grupo?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Com quem do grupo seria mais terrível ficar preso em um elevador por 24 horas?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem lançaria mais provavelmente um podcast sobre o seu trajeto diário no ônibus/metrô?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem perderia um debate sobre se pizza com ketchup é crime ou não?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Qual membro do grupo tem o Spotify Wrapped mais caótico?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Who would most likely go viral for the wrong reasons at a wedding?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem seria expulso primeiro em uma noite de jogos de tabuleiro?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem manda mais mensagens "kkk" sem estar rindo de verdade?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem é o campeão da procrastinação no grupo?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem sobreviveria a um encontro com uma "Karen" sem chorar?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem tentaria pagar um café com um "toca aqui" (high-five)?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem no grupo entraria mais provavelmente em uma seita por acidente ao procurar uma aula de yoga?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem faria primeiro uma tatuagem de um meme que morre dois dias depois?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem brigaria mais provavelmente com um caixa eletrônico porque ele diz "operação cancelada"?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem no grupo ficaria mais provavelmente preso em um balanço infantil?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem enviaria primeiro um e-mail "responder a todos" que era apenas para uma pessoa?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem tentaria mais provavelmente acariciar um animal selvagem que claramente quer mordê-lo?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem ganharia o prêmio de "Mais propenso a esquecer por que entrou em um cômodo"?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem no grupo causaria mais provavelmente um incêndio tentando ferver água?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Se o grupo fosse uma equipe de assaltantes, quem esqueceria as chaves do carro de fuga dentro do carro?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem seria mais provavelmente visto ao fundo de uma reportagem de TV fazendo algo vergonhoso?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem compraria primeiro uma esteira para usá-la depois como cabide?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem no grupo confundiria mais provavelmente um estranho com uma celebridade e pediria uma selfie?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem riria mais provavelmente em um velório e depois tentaria disfarçar com uma tosse falsa?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem no grupo corre o maior risco de comprar uma "Mystery Box" em um site suspeito?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem tentaria entrar por uma porta escrita "Puxe" empurrando por pelo menos 10 segundos?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem no grupo faria mais provavelmente uma tatuagem com erro de português?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem tentaria primeiro paquerar um bot de IA do atendimento ao cliente?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem se tornaria mais provavelmente um meme viral sem nem saber o que é um meme?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem sobreviveria em uma ilha deserta, mas só se tivesse sua rotina de skin care com ele?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem casaria mais provavelmente com um robô antes de 2030?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem você ligaria para te tirar da prisão, mas acabaria sendo preso também?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem no grupo tem os segredos mais inofensivos, mas mais estranhos?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem seria o melhor líder de seita para um grupo que venera pizza de brócolis?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem tem a risada mais contagiante e alta do grupo?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem esqueceria mais provavelmente por mais de uma hora onde estacionou o carro?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem é a maior "Drama Queen" em um simples resfriado?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem desistiria primeiro em um desafio de "24 horas sem celular"?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem dormiria no meio de uma balada barulhenta?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem acabaria comprando um terreno na Lua por causa de um anúncio no Instagram?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem esqueceria o aniversário da mãe, mas lembraria o de um personagem de anime aleatório?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem choraria porque quebrou uma unha ou sujou um tênis novo?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem tentaria pedir desconto em uma loja de grife?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem usaria meia com chinelo e pensaria seriamente que é um estilo incrível?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem colecionaria algo tão aleatório quanto papéis de chiclete?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true),
('Quem cairia primeiro em um trote telefônico gravado?', 'poll', 'humor', NULL, false, 2, 'pt', ARRAY['😂']::text[], true);

-- (Adding other 7 categories below...)

-- habilidades: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Quem no grupo consegue montar um móvel da IKEA sem sobrar nenhum parafuso?', 'poll', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Quem tem a melhor bússola interna e nunca precisa de Google Maps?', 'poll', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Quem seria o melhor negociador em uma feira de antiguidades?', 'poll', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Quem no grupo sobreviveria melhor na mata apenas com um canivete suíço?', 'poll', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Quem é o mais rápido para digitar mensagens no celular sem olhar?', 'poll', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Quem no grupo tem a lábia melhor e convenceria qualquer um de qualquer coisa?', 'poll', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Quem seria o melhor piloto de drone no grupo?', 'poll', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Quem no grupo é um gênio da matemática em segredo, mas finge que não sabe de nada?', 'poll', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Quem tem mais paciência para desenredar um emaranhado de fios de fone de ouvido?', 'poll', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Quem seria o melhor cozinheiro improvisado com o que tem na geladeira?', 'poll', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Quem no grupo ganharia um concurso de soletrar palavras ao contrário?', 'poll', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Quem consegue aprender uma dancinha do TikTok em menos de 5 minutos?', 'poll', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Quem no grupo seria o melhor detetive particular (ou stalker profissional)?', 'poll', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Quem tem o melhor jeito para consertar um computador que não liga?', 'poll', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Quem no grupo ganharia uma partida de xadrez contra um profissional?', 'poll', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Quem tem a mão mais firme para jogar Jenga depois de dois drinks?', 'poll', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Quem no grupo seria o melhor sobrevivente em um apocalipse zumbi pela sua forma física?', 'poll', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Quem consegue imitar perfeitamente um sotaque de outro país?', 'poll', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Quem no grupo tem o melhor olho para fotos de Instagram?', 'poll', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Quem seria o melhor em um show de talentos secretos?', 'poll', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Que nota você daria para a capacidade do {member_A} de economizar dinheiro? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('De 1 a 10, qual o nível de pontaria do {member_A}?', 'scale', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Quão bem o {member_A} conta piadas? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Quão "tech" é o {member_A}? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('De 1 a 10, quanta disciplina o {member_A} tem com a sua alimentação?', 'scale', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Quão rápido você acha que o {member_A} aprenderia a tocar violão? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Que nota você daria para o {member_A} dirigindo no trânsito pesado? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('De 1 a 10, quão bem o {member_A} mente quando é pego no flagra?', 'scale', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Quão bem o {member_A} organizaria um churrasco? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Qual o nível de "marido de aluguel" do {member_A} para consertar coisas em casa? (1-10)', 'scale', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Quem ganharia um debate político: {member_A} ou {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Quem aguentaria mais tempo em um deserto: {member_A} ou {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Quem é mais "pro" em jogos de estratégia: {member_A} ou {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Quem tem a caligrafia mais bonita: {member_A} ou {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Quem ganharia uma partida de Perfil/Trivia: {member_A} ou {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Quem é mais criativo para desenhar ou criar coisas: {member_A} ou {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Quem tem mais estilo para se vestir: {member_A} ou {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Quem resolve um Sudoku mais rápido: {member_A} ou {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Quem seria um melhor agente secreto: {member_A} ou {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Quem tem melhor ouvido musical: {member_A} ou {member_B}?', 'vs', 'habilidades', NULL, false, 2, 'pt', ARRAY['💪']::text[], true),
('Classifique o grupo por quem tem mais chance de ganhar um reality show de talentos.', 'ranking', 'habilidades', NULL, false, 3, 'pt', ARRAY['💪']::text[], true),
('Classifique o grupo do melhor para o pior cozinheiro.', 'ranking', 'habilidades', NULL, false, 3, 'pt', ARRAY['💪']::text[], true),
('Classifique por quem tem mais capacidade de concentração quando há muito barulho.', 'ranking', 'habilidades', NULL, false, 3, 'pt', ARRAY['💪']::text[], true),
('Classifique o grupo por quem dirigiria melhor um caminhão na estrada.', 'ranking', 'habilidades', NULL, false, 3, 'pt', ARRAY['💪']::text[], true),
('Classifique por quem é mais habilidoso com as mãos (marcenaria, artesanato, etc).', 'ranking', 'habilidades', NULL, false, 3, 'pt', ARRAY['💪']::text[], true),
('Classifique o grupo por quem tem mais memória para rostos.', 'ranking', 'habilidades', NULL, false, 3, 'pt', ARRAY['💪']::text[], true),
('Classifique por quem aprenderia mais rápido um esporte radical.', 'ranking', 'habilidades', NULL, false, 3, 'pt', ARRAY['💪']::text[], true),
('Classifique o grupo por quem tem mais facilidade para línguas estrange.', 'ranking', 'habilidades', NULL, false, 3, 'pt', ARRAY['💪']::text[], true),
('Classifique por quem gerencia melhor o tempo sob muita pressão.', 'ranking', 'habilidades', NULL, false, 3, 'pt', ARRAY['💪']::text[], true),
('Classifique o grupo por quem seria o melhor jogador de poker.', 'ranking', 'habilidades', NULL, false, 3, 'pt', ARRAY['💪']::text[], true);

-- futuro: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Quem no grupo será o primeiro a ir morar em outro continente por trabalho?', 'poll', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Quem será o primeiro a ser avô/avó e ficar contando vantagem no grupo?', 'poll', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Quem no grupo terá uma rua com o seu nome algum dia?', 'poll', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Quem será o primeiro a ficar milionário, mas continuar comendo no "podrão" da esquina?', 'poll', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Quem no grupo escreverá um livro que vai virar filme?', 'poll', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Quem será o primeiro a casar em uma cerimônia secreta sem avisar ninguém?', 'poll', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Quem no grupo acabará trabalhando em uma startup de tecnologia super bem-sucedida?', 'poll', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Quem será o primeiro a se aposentar antes dos 45 anos?', 'poll', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Quem no grupo ganhará um prêmio importante na sua área?', 'poll', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Quem será o primeiro a comprar uma casa com piscina?', 'poll', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Quem no grupo terá uma família bem grande?', 'poll', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Quem será o primeiro a deletar todas as suas redes sociais permanentemente?', 'poll', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Quem no grupo será convidado para um evento super exclusivo em Hollywood?', 'poll', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Quem será o primeiro a morar em um bairro super "hipster" da cidade?', 'poll', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Quem no grupo acabará sendo um líder de opinião super influente?', 'poll', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Quem será o primeiro a fazer um mochilão pela Ásia?', 'poll', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Quem no grupo terá sua própria marca de cachaça ou vinho?', 'poll', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Quem será o primeiro a ficar super "fitness" e nunca mais comer tranqueira?', 'poll', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Quem no grupo será lembrado por sua grande contribuição para a comunidade?', 'poll', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Quem será o primeiro a adotar um monte de gatos?', 'poll', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Qual a probabilidade do {member_A} ser um influenciador famoso em 3 anos? (0-100%)', 'scale', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('De 1 a 10, quanto você acha que a vida do {member_A} vai mudar este ano?', 'scale', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Que nível de sucesso você acha que o {member_A} alcançará nos seus negócios? (1-10)', 'scale', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('De 1 a 10, quanto você acha que o {member_A} vai cumprir as suas metas este ano?', 'scale', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Qual a probabilidade do {member_A} virar um nômade digital logo logo? (1-10)', 'scale', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Que nota você daria para a estabilidade futura do relacionamento do {member_A}? (1-10)', 'scale', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('De 1 a 10, quanto você acha que o {member_A} vai impactar a vida de outras pessoas?', 'scale', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Qual a probabilidade do {member_A} ganhar na loteria algum dia? (1-10)', 'scale', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Que nível de paz de espírito você acha que o {member_A} terá na velhice? (1-10)', 'scale', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('De 1 a 10, quanto você acha que o {member_A} vai se arrepender de não ter feito algo hoje?', 'scale', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Quem terá uma casa mais legal em 15 anos: {member_A} ou {member_B}?', 'vs', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Quem será mais feliz na hora de se aposentar: {member_A} ou {member_B}?', 'vs', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Quem terá um cargo mais alto no trabalho: {member_A} ou {member_B}?', 'vs', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Quem será mais respeitado no que faz: {member_A} ou {member_B}?', 'vs', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Quem visitará mais países: {member_A} ou {member_B}?', 'vs', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Quem manterá mais contato com o grupo no futuro: {member_A} ou {member_B}?', 'vs', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Quem ficará mais sábio com a idade: {member_A} ou {member_B}?', 'vs', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Quem entenderá melhor a tecnologia do futuro: {member_A} ou {member_B}?', 'vs', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Quem terá mais netos: {member_A} ou {member_B}?', 'vs', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Quem viverá em um lugar mais tranquilo: {member_A} ou {member_B}?', 'vs', 'futuro', NULL, false, 2, 'pt', ARRAY['🔮']::text[], true),
('Classifique o grupo por quem terá o maior sucesso na carreira.', 'ranking', 'futuro', NULL, false, 3, 'pt', ARRAY['🔮']::text[], true),
('Classifique o grupo por quem realizará os seus sonhos primeiro.', 'ranking', 'futuro', NULL, false, 3, 'pt', ARRAY['🔮']::text[], true),
('Classifique por quem deixará uma marca maior no mundo.', 'ranking', 'futuro', NULL, false, 3, 'pt', ARRAY['🔮']::text[], true),
('Classifique o grupo por quem parecerá mais jovem com o passar do tempo.', 'ranking', 'futuro', NULL, false, 3, 'pt', ARRAY['🔮']::text[], true),
('Classifique por quem fará viagens mais exóticas nos próximos 20 anos.', 'ranking', 'futuro', NULL, false, 3, 'pt', ARRAY['🔮']::text[], true),
('Classifique o grupo por quem terá uma vida mais relaxada.', 'ranking', 'futuro', NULL, false, 3, 'pt', ARRAY['🔮']::text[], true),
('Classifique por quem vai casar primeiro (ou de novo).', 'ranking', 'futuro', NULL, false, 3, 'pt', ARRAY['🔮']::text[], true),
('Classifique o grupo por quem fará mais pela sociedade.', 'ranking', 'futuro', NULL, false, 3, 'pt', ARRAY['🔮']::text[], true),
('Classifique por quem estará mais por dentro das tendências futuras.', 'ranking', 'futuro', NULL, false, 3, 'pt', ARRAY['🔮']::text[], true),
('Classifique o grupo por quem viverá uma vida mais longa e realizada.', 'ranking', 'futuro', NULL, false, 3, 'pt', ARRAY['🔮']::text[], true);

-- (Adding the remaining 5 categories for pt...)

-- atrevidas: 50 questions (anonymous)
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Qual foi a maior mentira que você já contou para evitar sair com alguém?', 'free', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Quem no grupo tem os gostos mais "estranhos" na cama, na sua opinião?', 'poll', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Você já fingiu gostar de alguém só por interesse?', 'free', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Em quem deste grupo você daria um beijo se estivéssemos jogando verdade ou desafio?', 'poll', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Qual foi o lugar mais louco onde você já teve relações?', 'free', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Você já sonhou com alguém deste grupo?', 'free', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Qual é a sua fantasia mais "sombria" que ninguém sabe?', 'free', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Você já deu "ghosting" em alguém que você realmente gostava?', 'free', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Quem no grupo é um "pegador" nato, na sua opinião?', 'poll', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Qual foi a coisa mais ousada que você já fez por alguém por quem estava louco(a)?', 'free', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Você já mandou um "nude" e teve um medo absurdo logo depois?', 'free', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Quem no grupo paquera mais por apps como Tinder ou Bumble, na sua opinião?', 'poll', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Você já saiu com duas pessoas ao mesmo tempo?', 'free', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Quem deste grupo você levaria para um chalé só para "conversar"?', 'poll', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Qual foi a mensagem mais explícita que você já mandou para a pessoa errada por engano?', 'free', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Você já sentiu atração pelo(a) parceiro(a) de alguém do grupo?', 'free', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Quem no grupo tem os fetiches mais intensos, na sua opinião?', 'poll', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Qual foi a sua pior experiência na "primeira vez"?', 'free', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Você já foi pego "no flagra"?', 'free', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Quem no grupo é mais "selvagem" na intimidade, na sua opinião?', 'poll', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Você já usou brinquedos e qual é o seu favorito?', 'free', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Quem no grupo já teve mais parceiros sexuais, na sua opinião?', 'poll', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Qual foi a maior mentira que você contou para alguém ir para a cama com você?', 'free', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Para quem deste grupo você confiaria seu celular desbloqueado?', 'poll', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Você já fez um ménage ou morre de vontade de fazer?', 'free', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Quem no grupo é mais provável de aceitar um lance de uma noite só, na sua opinião?', 'poll', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Qual segredo inconfessável você tem sobre um(a) ex?', 'free', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Você já esteve com alguém muito mais velho que você?', 'free', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Quem no grupo conta mais vantagem do que faz na realidade, na sua opinião?', 'poll', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Qual foi a coisa mais "estranha" que você já pesquisou em modo anônimo?', 'free', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Você já se sentiu atraído(a) por alguém do mesmo sexo (se você for hétero)?', 'free', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Quem no grupo tem um perfil secreto em um app de relacionamento, na sua opinião?', 'poll', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Qual foi o momento mais vergonhoso que você já viveu sem roupa?', 'free', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Você já fez sexo por telefone ou sexting intenso?', 'free', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Quem no grupo é mais "conservador" na cama, na sua opinião?', 'poll', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Qual parte do seu corpo é o seu "botão" secreto?', 'free', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Você já pagou por sexo ou te ofereceram dinheiro para isso?', 'free', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Quem no grupo perdoaria mais rápido uma traição, na sua opinião?', 'poll', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Qual fetiche você tem mais vergonha de admitir?', 'free', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Você já gravou um vídeo íntimo?', 'free', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Quem no grupo é mais "curioso" para testar coisas novas, na sua opinião?', 'poll', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Em qual lugar público você mais gostaria de ter relações?', 'free', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Você já teve um caso com alguém do trabalho?', 'free', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Quem no grupo é o mais sexy, na sua opinião?', 'poll', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Qual foi a coisa mais louca que você já fez estando bêbado(a)?', 'free', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Você já reviu um(a) ex enquanto estava em um relacionamento com outra pessoa?', 'free', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Quem no grupo é um romântico secreto, na sua opinión?', 'poll', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Qual é a fantasia mais louca que você já realizou?', 'free', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Você já esteve em um relacionamento aberto?', 'free', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true),
('Quem deste grupo você convidaria para um ménage se ele/ela dissesse sim?', 'poll', 'atrevidas', NULL, true, 2, 'pt', ARRAY['🌶️']::text[], true);

-- hipoteticas: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Se você pudesse ter um superpoder, mas apenas uma vez a cada 6 meses, qual seria?', 'mc', 'hipoteticas', ARRAY['Invisibilidade 12h', 'Viajar no passado 30 min', 'Ler mentes 1h', 'Voar 2h'], false, 2, 'pt', ARRAY['🧠']::text[], true),
('Se o grupo for parar em uma ilha deserta, quem acenderia o fogo primeiro?', 'poll', 'hipoteticas', NULL, false, 2, 'pt', ARRAY['🧠']::text[], true),
('Se você pudesse viver em um filme por uma semana, qual escolheria?', 'mc', 'hipoteticas', ARRAY['Harry Potter', 'Avengers', 'O Lobo de Wall Street', 'Cidade de Deus'], false, 2, 'pt', ARRAY['🧠']::text[], true),
('Se você tivesse que escolher alguém do grupo para te defender em um tribunal, quem seria?', 'poll', 'hipoteticas', NULL, false, 2, 'pt', ARRAY['🧠']::text[], true),
('Se te dessem 5 milhões de euros para nunca mais comer pizza, você aceitaria?', 'mc', 'hipoteticas', ARRAY['Sim, com certeza', 'Jamais', 'Só se eu puder comer hambúrguer', 'Pensaria muito a respeito'], false, 2, 'pt', ARRAY['🧠']::text[], true),
('Se o grupo fosse um time de futebol, quem seria o capitão?', 'poll', 'hipoteticas', NULL, false, 2, 'pt', ARRAY['🧠']::text[], true),
('Se você soubesse exatamente o dia em que ia morrer, você ia querer saber?', 'mc', 'hipoteticas', ARRAY['Sim, para gastar tudo', 'Não, que horror', 'Só se eu puder mudar', 'Prefiro a surpresa'], false, 2, 'pt', ARRAY['🧠']::text[], true),
('Se você tivesse que escolher alguém do grupo para cuidar de você se estivesse muito doente, quem seria?', 'poll', 'hipoteticas', NULL, false, 2, 'pt', ARRAY['🧠']::text[], true),
('Se você pudesse falar qualquer língua fluentemente agora mesmo, qual escolheria?', 'mc', 'hipoteticas', ARRAY['Japonês', 'Francês', 'Espanhol', 'Russo'], false, 2, 'pt', ARRAY['🧠']::text[], true),
('Se o grupo estivesse em um apocalipse zumbi, quem se sacrificaria primeiro pelos outros?', 'poll', 'hipoteticas', NULL, false, 2, 'pt', ARRAY['🧠']::text[], true),
('Se você pudesse se teletransportar para qualquer lugar agora mesmo, para onde iria?', 'mc', 'hipoteticas', ARRAY['Para uma praia nas Maldivas', 'Para Nova York fazer compras', 'Para o topo da Torre Eiffel', 'Para a minha cama dormir'], false, 2, 'pt', ARRAY['🧠']::text[], true),
('Se você tivesse que confiar sua senha do banco para alguém do grupo, quem seria?', 'poll', 'hipoteticas', NULL, false, 2, 'pt', ARRAY['🧠']::text[], true),
('Se você pudesse ressuscitar uma pessoa famosa para tomar um drink, quem seria?', 'mc', 'hipoteticas', ARRAY['Freddie Mercury', 'Frida Kahlo', 'Steve Jobs', 'Pelé'], false, 2, 'pt', ARRAY['🧠']::text[], true),
('Se o grupo fosse um reality show, quem ganharia por ser o mais "real"?', 'poll', 'hipoteticas', NULL, false, 2, 'pt', ARRAY['🧠']::text[], true),
('Se você pudesse apagar um erro do seu passado, qual escolheria?', 'free', 'hipoteticas', NULL, false, 2, 'pt', ARRAY['🧠']::text[], true),
('Se você tivesse que escolher alguém do grupo para esconder evidências (só por diversão), quem seria?', 'poll', 'hipoteticas', NULL, false, 2, 'pt', ARRAY['🧠']::text[], true),
('Se você pudesse ser imortal, você aceitaria?', 'mc', 'hipoteticas', ARRAY['Sim, sem dúvida', 'Não, que tédio', 'Só se eu não envelhecer', 'Só se meus amigos também forem'], false, 2, 'pt', ARRAY['🧠']::text[], true),
('Se o grupo montasse um negócio, quem cuidaria do dinheiro?', 'poll', 'hipoteticas', NULL, false, 2, 'pt', ARRAY['🧠']::text[], true),
('Se você pudesse apagar uma lembrança triste da sua cabeça, você faria?', 'free', 'hipoteticas', NULL, false, 2, 'pt', ARRAY['🧠']::text[], true),
('Se você tivesse que morar em uma república com alguém do grupo por um ano, quem seria?', 'poll', 'hipoteticas', NULL, false, 2, 'pt', ARRAY['🧠']::text[], true),
('Qual a probabilidade de extraterrestres nos visitarem em breve? (0-10)', 'scale', 'hipoteticas', NULL, false, 2, 'pt', ARRAY['🧠']::text[], true),
('De 1 a 10, quanto você acha que as máquinas vão se rebelar?', 'scale', 'hipoteticas', NULL, false, 2, 'pt', ARRAY['🧠']::text[], true),
('Quão felizes seríamos em um mundo sem internet? (1-10)', 'scale', 'hipoteticas', NULL, false, 2, 'pt', ARRAY['🧠']::text[], true),
('De 1 a 10, quanto você acredita em fantasmas?', 'scale', 'hipoteticas', NULL, false, 2, 'pt', ARRAY['🧠']::text[], true),
('Quão provável você acha que vivemos em uma simulação? (1-10)', 'scale', 'hipoteticas', NULL, false, 2, 'pt', ARRAY['🧠']::text[], true),
('De 1 a 10, quanto você daria para salvar o planeta?', 'scale', 'hipoteticas', NULL, false, 2, 'pt', ARRAY['🧠']::text[], true),
('Quão importante você acha que é colonizar outros planetas? (1-10)', 'scale', 'hipoteticas', NULL, false, 2, 'pt', ARRAY['🧠']::text[], true),
('De 1 a 10, quanto você acha que o futuro já está escrito?', 'scale', 'hipoteticas', NULL, false, 2, 'pt', ARRAY['🧠']::text[], true),
('Quão possível você acha que viajar no tempo será um dia? (1-10)', 'scale', 'hipoteticas', NULL, false, 2, 'pt', ARRAY['🧠']::text[], true),
('De 1 a 10, quanto robôs inteligentes te dão medo?', 'scale', 'hipoteticas', NULL, false, 2, 'pt', ARRAY['🧠']::text[], true),
('Quem seria um líder melhor em caso de crise: {member_A} ou {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'pt', ARRAY['🧠']::text[], true),
('Quem sobreviveria melhor no século XVIII: {member_A} ou {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'pt', ARRAY['🧠']::text[], true),
('Quem faria amizade com um alien primeiro: {member_A} ou {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'pt', ARRAY['🧠']::text[], true),
('Quem escolheria sair da Matrix: {member_A} ou {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'pt', ARRAY['🧠']::text[], true),
('Quem seria um astronauta melhor: {member_A} ou {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'pt', ARRAY['🧠']::text[], true),
('Quem se sacrificaria pelo grupo em caso de problema: {member_A} ou {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'pt', ARRAY['🧠']::text[], true),
('Quem seria o melhor representante da Terra: {member_A} ou {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'pt', ARRAY['🧠']::text[], true),
('Quem se adaptaria melhor a uma vida debaixo d''água: {member_A} ou {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'pt', ARRAY['🧠']::text[], true),
('Quem ganharia um duelo de insultos contra um pirata: {member_A} ou {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'pt', ARRAY['🧠']::text[], true),
('Quem acreditaria primeiro que tudo isso é um sonho: {member_A} ou {member_B}?', 'vs', 'hipoteticas', NULL, false, 2, 'pt', ARRAY['🧠']::text[], true),
('Classifique o grupo por quem sobreviveria mais tempo em um filme de terror.', 'ranking', 'hipoteticas', NULL, false, 3, 'pt', ARRAY['🧠']::text[], true),
('Classifique o grupo do mais ao menos suspeito de ser um espião.', 'ranking', 'hipoteticas', NULL, false, 3, 'pt', ARRAY['🧠']::text[], true),
('Classifique por quem seria o melhor estrategista em um jogo de guerra.', 'ranking', 'hipoteticas', NULL, false, 3, 'pt', ARRAY['🧠']::text[], true),
('Classifique o grupo por quem seria mais útil se o mundo acabasse.', 'ranking', 'hipoteticas', NULL, false, 3, 'pt', ARRAY['🧠']::text[], true),
('Classifique por quem se voluntariaria primeiro para ir a Marte.', 'ranking', 'hipoteticas', NULL, false, 3, 'pt', ARRAY['🧠']::text[], true),
('Classifique o grupo por quem inventaria a cura para uma doença.', 'ranking', 'hipoteticas', NULL, false, 3, 'pt', ARRAY['🧠']::text[], true),
('Classifique por quem seria o melhor negociador com uma raça alienígena.', 'ranking', 'hipoteticas', NULL, false, 3, 'pt', ARRAY['🧠']::text[], true),
('Classifique o grupo por quem ficaria mais calmo em um terremoto.', 'ranking', 'hipoteticas', NULL, false, 3, 'pt', ARRAY['🧠']::text[], true),
('Classifique por quem inventaria as regras de sociedade mais criativas.', 'ranking', 'hipoteticas', NULL, false, 3, 'pt', ARRAY['🧠']::text[], true),
('Classifique o grupo por quem seria o melhor guia em um mundo pós-apocalíptico.', 'ranking', 'hipoteticas', NULL, false, 3, 'pt', ARRAY['🧠']::text[], true);

-- vinculos: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Quem no grupo é aquele que sempre organiza os rolês?', 'poll', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Quem no grupo te deu o melhor conselho quando você estava mal?', 'poll', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Quem é a pessoa mais leal que você conhece neste grupo?', 'poll', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Quem no grupo está sempre lá quando alguém precisa conversar?', 'poll', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Para quem neste grupo você confiaria as chaves da sua casa?', 'poll', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Quem mais evoluiu como pessoa desde que você o/a conhece?', 'poll', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Quem no grupo tem o coração mais nobre de todos?', 'poll', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Com quem neste grupo você ri até a barriga doer?', 'poll', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Quem neste grupo você ligaria se tivesse uma emergência de verdade?', 'poll', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Quem no grupo sabe ouvir melhor sem julgar?', 'poll', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Quem mantém a união do grupo de WhatsApp?', 'poll', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Quem neste grupo você mais admira pela sua forma de ver a vida?', 'poll', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Quem no grupo é o mais honesto, mesmo quando o que diz dói?', 'poll', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Quem é a pessoa mais legal para passar um tempo calmo conversando?', 'poll', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Para quem neste grupo você pediria perdão primeiro se tivessem uma treta?', 'poll', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Quem no grupo se preocupa mais com todo mundo?', 'poll', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Quem é a pessoa que mais te motiva a ser melhor neste grupo?', 'poll', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Para quem neste grupo você contaria algo que te dá muita vergonha?', 'poll', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Quem no grupo presta mais atenção aos aniversários?', 'poll', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Quem é a pessoa que traz as melhores energias para a sua vida?', 'poll', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('De 1 a 10, quanto você confia no {member_A}?', 'scale', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Quão boa é a conexão que você tem com o {member_A}? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Que lugar o {member_A} ocupa na sua lista de pessoas favoritas? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('De 1 a 10, quanto você acha que o {member_A} te entende de verdade?', 'scale', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Que nota você daria para a lealdade do {member_A} com o grupo? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Quão bem o {member_A} apoia os outros? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('De 1 a 10, quanto você gosta de conversar sobre coisas sérias com o {member_A}?', 'scale', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Quão importante é para você continuar sendo amigo(a) do {member_A} para sempre? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Que nível de honestidade você acha que o {member_A} tem com você? (1-10)', 'scale', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('De 1 a 10, quanto você acha que o grupo mudaria se o {member_A} não estivesse?', 'scale', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Quem cuida mais dos amigos: {member_A} ou {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Com quem você prefere falar sobre seus problemas: {member_A} ou {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Quem tem mais paciência com o grupo: {member_A} ou {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Quem é mais atento às suas amizades: {member_A} ou {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Quem você ligaria para chorar um pouco: {member_A} ou {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Quem te conhece melhor quando você está de mau humor: {member_A} ou {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Quem é mais honesto para falar as coisas: {member_A} ou {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Com quem você se sente mais "você mesmo(a)" sem filtro: {member_A} ou {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Quem perdoaria mais facilmente um erro: {member_A} ou {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Quem é mais generoso com o seu tempo: {member_A} ou {member_B}?', 'vs', 'vinculos', NULL, false, 2, 'pt', ARRAY['💛']::text[], true),
('Classifique o grupo por quem sabe guardar melhor segredos.', 'ranking', 'vinculos', NULL, false, 3, 'pt', ARRAY['💛']::text[], true),
('Classifique o grupo pelo seu nível de empatia com os outros.', 'ranking', 'vinculos', NULL, false, 3, 'pt', ARRAY['💛']::text[], true),
('Classifique por quem te ajudaria primeiro em uma enrascada sem pedir nada.', 'ranking', 'vinculos', NULL, false, 3, 'pt', ARRAY['💛']::text[], true),
('Classifique o grupo por quem é mais fiel às suas amizades.', 'ranking', 'vinculos', NULL, false, 3, 'pt', ARRAY['💛']::text[], true),
('Classifique por quem é mais sincero nos seus conselhos (mesmo que doa).', 'ranking', 'vinculos', NULL, false, 3, 'pt', ARRAY['💛']::text[], true),
('Classifique o grupo por quem mais se preocupa em saber como todos estão.', 'ranking', 'vinculos', NULL, false, 3, 'pt', ARRAY['💛']::text[], true),
('Classifique por quem é mais engraçado para uma viagem.', 'ranking', 'vinculos', NULL, false, 3, 'pt', ARRAY['💛']::text[], true),
('Classifique o grupo por quem se reconcilia mais facilmente.', 'ranking', 'vinculos', NULL, false, 3, 'pt', ARRAY['💛']::text[], true),
('Classifique por quem traz mais paz e calma ao grupo.', 'ranking', 'vinculos', NULL, false, 3, 'pt', ARRAY['💛']::text[], true),
('Classifique o grupo por quem foi a melhor descoberta de amizade.', 'ranking', 'vinculos', NULL, false, 3, 'pt', ARRAY['💛']::text[], true);

-- eventos: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Quem no grupo é aquele que sempre organiza o amigo secreto?', 'poll', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Quem é mais provável de esquecer que tínhamos marcado hoje?', 'poll', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Para quem neste grupo você confiaria a organização da sua festa de aniversário?', 'poll', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Quem no grupo é o primeiro a dizer "Vamos viajar" para o outro lado do mundo?', 'poll', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Quem chega sempre atrasado, mas traz as bebidas?', 'poll', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Quem no grupo é o maior festeiro e nunca quer ir dormir?', 'poll', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Quem prepara os melhores drinks nos encontros?', 'poll', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Quem deste grupo você escolheria como DJ para a sua festa?', 'poll', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Quem no grupo tira mais fotos em cada passeio?', 'poll', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Quem sempre cuida de comprar tudo o que precisa para o churrasco?', 'poll', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Quem no grupo acabará mais provavelmente dançando em cima de uma cadeira?', 'poll', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Para quem neste grupo você pediria para ir com você a um festival de música o fim de semana todo?', 'poll', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Quem no grupo sempre encontra as passagens mais baratas?', 'poll', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Quem é a "alma velha" do grupo e quer ir embora cedo?', 'poll', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Para quem neste grupo você confiaria para reservar o Airbnb para todo mundo?', 'poll', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Quem no grupo é mais engraçado para um fim de semana em uma pousada bacana?', 'poll', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Quem propõe sempre ir em museus ou coisas do tipo?', 'poll', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Quem neste grupo você escolheria para ir ao parque de diversões e entrar nos brinquedos mais loucos?', 'poll', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Quem no grupo tem mais risco de se perder em um show?', 'poll', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Quem organiza as melhores surpresas para os outros?', 'poll', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('De 1 a 10, quanto você gosta de planos improvisados?', 'scale', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Que nota você daria para o nível de animação dos nossos rolês? (1-10)', 'scale', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Quão importante é para você a gente se encontrar pessoalmente? (1-10)', 'scale', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('De 1 a 10, quanto você acha que a gente se divertiria em uma viagem para a praia?', 'scale', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Que nota você daria para a pontualidade do grupo nos encontros? (1-10)', 'scale', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Quão ansioso(a) você está para a gente se ver na próxima vez? (1-10)', 'scale', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('De 1 a 10, quanto você gosta de organizar planos você mesmo(a)?', 'scale', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Quão difícil é para o grupo entrar em acordo sobre um plano? (1-10)', 'scale', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Quão importante você acha que é comemorar cada aniversário? (1-10)', 'scale', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('De 1 a 10, quanta saudade você sente do grupo quando não nos vemos por muito tempo?', 'scale', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Quem sabe organizar melhor: {member_A} ou {member_B}?', 'vs', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Com quem você prefere viajar: {member_A} ou {member_B}?', 'vs', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Quem aguenta mais tempo em um rolê: {member_A} ou {member_B}?', 'vs', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Quem propõe os planos mais loucos: {member_A} ou {member_B}?', 'vs', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Quem tem gostos melhores para restaurantes: {member_A} ou {member_B}?', 'vs', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Quem é mais pontual: {member_A} ou {member_B}?', 'vs', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Para quem você confiaria o dinheiro da viagem: {member_A} ou {member_B}?', 'vs', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Quem é mais engraçado no karaokê: {member_A} ou {member_B}?', 'vs', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Quem tira fotos melhores de recordação: {member_A} ou {member_B}?', 'vs', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Quem é mais provável de dormir no caminho de volta do rolê: {member_A} ou {member_B}?', 'vs', 'eventos', NULL, false, 2, 'pt', ARRAY['🎉']::text[], true),
('Classifique o grupo por quem coloca mais pilha nos rolês.', 'ranking', 'eventos', NULL, false, 3, 'pt', ARRAY['🎉']::text[], true),
('Classifique o grupo por quem tem mais vontade de estar na rua.', 'ranking', 'eventos', NULL, false, 3, 'pt', ARRAY['🎉']::text[], true),
('Classifique por quem é mais provável de resolver tudo em uma viagem.', 'ranking', 'eventos', NULL, false, 3, 'pt', ARRAY['🎉']::text[], true),
('Classifique o grupo por quem é o mais pontual de todos.', 'ranking', 'eventos', NULL, false, 3, 'pt', ARRAY['🎉']::text[], true),
('Classifique por quem coloca a melhor música quando estamos juntos.', 'ranking', 'eventos', NULL, false, 3, 'pt', ARRAY['🎉']::text[], true),
('Classifique o grupo por quem faz amigos mais rápido em qualquer lugar.', 'ranking', 'eventos', NULL, false, 3, 'pt', ARRAY['🎉']::text[], true),
('Classifique por quem filma mais tudo o que a gente faz.', 'ranking', 'eventos', NULL, false, 3, 'pt', ARRAY['🎉']::text[], true),
('Classifique o grupo por quem faz mais surpresas.', 'ranking', 'eventos', NULL, false, 3, 'pt', ARRAY['🎉']::text[], true),
('Classifique por quem é mais relaxado quando viajamos juntos.', 'ranking', 'eventos', NULL, false, 3, 'pt', ARRAY['🎉']::text[], true),
('Classifique o grupo por quem fez o melhor plano de grupo até agora.', 'ranking', 'eventos', NULL, false, 3, 'pt', ARRAY['🎉']::text[], true);

-- ia_custom: 50 questions
INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, language, tags, is_active) VALUES
('Quem no grupo usará primeiro o ChatGPT para responder no grupo?', 'poll', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Quem é mais provável de namorar uma IA no futuro?', 'poll', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Para quem neste grupo você confiaria para deixar uma IA programada por ele/ela gerir o seu dinheiro?', 'poll', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Quem no grupo tem mais medo de que os robôs nos dominem?', 'poll', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Quem sabe sempre quais são os novos apps de IA que estão saindo?', 'poll', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Quem no grupo implantaria um chip primeiro para ser mais inteligente?', 'poll', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Quem aproveita melhor a IA para não ter que trabalhar tanto?', 'poll', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Quem você escolheria para ser o primeiro humano em Marte ajudado por robôs?', 'poll', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Quem no grupo odeia mais a IA na arte ou na música?', 'poll', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Quem acha sempre que tudo o que vê na internet é falso por causa da IA?', 'poll', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Quem no grupo teria primeiro um clone digital?', 'poll', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Para quem você pediria ajuda para criar a sua própria IA personalizada?', 'poll', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Quem no grupo é o mais otimista quanto ao futuro dos robôs?', 'poll', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Quem já trata a Alexa ou o Google como se fossem pessoas de verdade?', 'poll', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Para quem neste grupo você confiaria os seus dados pessoais perante os algoritmos?', 'poll', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Quem no grupo acha que uma IA vai tomar o seu emprego logo logo?', 'poll', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Quem usa sempre filtros de IA para parecer diferente nas suas fotos?', 'poll', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Quem você escolheria para liderar a resistência humana contra as máquinas?', 'poll', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Quem no grupo é mais provável de aprender a programar só para criar a sua IA?', 'poll', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Quem já nem sabe se uma mensagem foi escrita por um humano ou por uma máquina?', 'poll', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('De 1 a 10, quanto você confia no que o ChatGPT te diz?', 'scale', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Quanto a IA mudou o seu dia a dia até agora? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Quão importante você acha que é a IA ter regras éticas? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('De 1 a 10, quão possível você acha que a gente perca o controle sobre as máquinas?', 'scale', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Que nota você daria para o seu conhecimento sobre como a IA funciona? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Quanto você gostaria de ter um robô que fizesse tudo para você em casa? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('De 1 a 10, quanto você acha que a IA ajuda a curar doenças?', 'scale', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Quanto medo você tem que a IA tome todos os empregos? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Quão importante você acha que o governo controle a IA? (1-10)', 'scale', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('De 1 a 10, quanto você acha que as máquinas poderão sentir algo algum dia?', 'scale', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Quem é mais fã de IA: {member_A} ou {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Quem tem mais medo do futuro da tecnologia: {member_A} ou {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Quem usa mais IA no seu dia a dia: {member_A} ou {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Quem faria amizade com um robô primeiro: {member_A} ou {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Quem é mais crítico com tudo o que envolve IA: {member_A} ou {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Quem sobreviveria melhor se não houvesse mais tecnologia nenhuma: {member_A} ou {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Quem aceitaria mais ser operado por um robô: {member_A} ou {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Quem seria melhor em enganar um bot: {member_A} ou {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Quem suspeitaria primeiro que o grupo é uma simulação de IA: {member_A} ou {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Quem acha que a IA é a melhor coisa que nos aconteceu: {member_A} ou {member_B}?', 'vs', 'ia_custom', NULL, false, 2, 'pt', ARRAY['🤖']::text[], true),
('Classifique o grupo por quem é mais viciado no celular.', 'ranking', 'ia_custom', NULL, false, 3, 'pt', ARRAY['🤖']::text[], true),
('Classifique o grupo pelo seu nível de otimismo perante a IA.', 'ranking', 'ia_custom', NULL, false, 3, 'pt', ARRAY['🤖']::text[], true),
('Classifique por quem usaria a IA para paquerar primeiro.', 'ranking', 'ia_custom', NULL, false, 3, 'pt', ARRAY['🤖']::text[], true),
('Classifique o grupo por quem presta mais atenção aos seus dados online.', 'ranking', 'ia_custom', NULL, false, 3, 'pt', ARRAY['🤖']::text[], true),
('Classifique por quem compraria um carro voador primeiro.', 'ranking', 'ia_custom', NULL, false, 3, 'pt', ARRAY['🤖']::text[], true),
('Classifique o grupo por quem tem mais curiosidade pelo futuro.', 'ranking', 'ia_custom', NULL, false, 3, 'pt', ARRAY['🤖']::text[], true),
('Classifique por quem acha que a IA vai consertar o mundo.', 'ranking', 'ia_custom', NULL, false, 3, 'pt', ARRAY['🤖']::text[], true),
('Classifique o grupo por quem é mais propenso a dizer obrigado à Alexa.', 'ranking', 'ia_custom', NULL, false, 3, 'pt', ARRAY['🤖']::text[], true),
('Classifique por quem acha que os robôs são um perigo real.', 'ranking', 'ia_custom', NULL, false, 3, 'pt', ARRAY['🤖']::text[], true),
('Classifique o grupo por quem usou a IA para a coisa mais louca.', 'ranking', 'ia_custom', NULL, false, 3, 'pt', ARRAY['🤖']::text[], true);
