-- BATCH FINAL - 100 PREGUNTAS STRICT SPEC (ENERO 2026)
-- Categorías: humor, habilidades, futuro, atrevidas, hipoteticas, vinculos, eventos, ia_custom
-- Modos: vs, poll, mc, scale, free, ranking

INSERT INTO public.questions (text, mode, category, options, is_anonymous, min_members, tags) VALUES
-- 😂 Humor (vs, poll, mc)
('{member_A} vs {member_B}: ¿Quién intentaría pagar el café con una tarjeta del gimnasio?', 'vs', 'humor', NULL, false, 2, ARRAY['😂']),
('¿Quién del grupo es más probable que se ría en el momento más inoportuno?', 'poll', 'humor', NULL, false, 2, ARRAY['😂']),
('¿Cuál es la excusa más ridícula de {member_A} para llegar tarde?', 'mc', 'humor', ARRAY['El despertador no sonó', 'Un gato me cortó el paso', 'Pensé que hoy era domingo', 'Me quedé atrapado en el ascensor'], false, 2, ARRAY['😂']),
('{member_A} vs {member_B}: ¿Quién sobreviviría menos tiempo en una isla desierta solo con un tenedor?', 'vs', 'humor', NULL, false, 2, ARRAY['😂']),
('Si {member_A} fuera un supervillano, ¿cuál sería su debilidad más absurda?', 'mc', 'humor', ARRAY['El olor a queso fuerte', 'Los peluches de pingüinos', 'La música de ascensor', 'El color fucsia chillón'], false, 2, ARRAY['😂']),
('¿Quién se comería algo que lleva caducado una semana solo para no tirarlo?', 'poll', 'humor', NULL, false, 2, ARRAY['😂']),
('{member_A} vs {member_B}: ¿Quién tiene un historial de Google más vergonzoso?', 'vs', 'humor', NULL, false, 2, ARRAY['😂']),
('¿Cuál sería el nombre de la biografía no autorizada de {member_A}?', 'mc', 'humor', ARRAY['Siesta y Fiesta', 'El arte de no hacer nada', 'Un desastre con encanto', 'Confesiones de un trasnochador'], false, 2, ARRAY['😂']),
('¿Quién es capaz de perderse en un centro comercial siguiendo a un desconocido?', 'poll', 'humor', NULL, false, 2, ARRAY['😂']),
('{member_A} vs {member_B}: ¿Quién entraría en pánico antes al ver una araña de plástico?', 'vs', 'humor', NULL, false, 2, ARRAY['😂']),
('¿Qué haría {member_A} si le tocara la lotería hoy mismo?', 'mc', 'humor', ARRAY['Comprar una colección de calcetines', 'Desaparecer a una isla tropical', 'Montar una granja de alpacas', 'Pagar sus deudas y dormir un mes'], false, 2, ARRAY['😂']),
('¿Quién del grupo se haría un tatuaje del que se arrepentiría a los 5 minutos?', 'poll', 'humor', NULL, false, 2, ARRAY['😂']),
('{member_A} vs {member_B}: ¿Quién es más probable que envíe un mensaje al grupo equivocado?', 'vs', 'humor', NULL, false, 2, ARRAY['😂']),

-- 💪 Habilidades (vs, ranking, scale)
('{member_A} vs {member_B}: ¿Quién ganaría un concurso de cocina con solo 3 ingredientes?', 'vs', 'habilidades', NULL, false, 2, ARRAY['💪']),
('Ordena de MEJOR a PEOR conductor en este grupo.', 'ranking', 'habilidades', NULL, false, 4, ARRAY['💪']),
('¿Qué tan bueno es {member_A} guardando secretos importantes?', 'scale', 'habilidades', NULL, false, 2, ARRAY['💪']),
('{member_A} vs {member_B}: ¿Quién sería el mejor líder en un apocalipsis zombie?', 'vs', 'habilidades', NULL, false, 2, ARRAY['💪']),
('Del 1 al 10, ¿qué tan "manitas" es {member_A} arreglando cosas en casa?', 'scale', 'habilidades', NULL, false, 2, ARRAY['💪']),
('Ordena al grupo según su capacidad para sobrevivir 24h sin móvil.', 'ranking', 'habilidades', NULL, false, 4, ARRAY['💪']),
('{member_A} vs {member_B}: ¿Quién terminaría antes un maratón de una serie de 8 temporadas?', 'vs', 'habilidades', NULL, false, 2, ARRAY['💪']),
('¿Qué nivel de paciencia tiene {member_A} cuando la tecnología falla?', 'scale', 'habilidades', NULL, false, 2, ARRAY['💪']),
('Ordena de MAYOR a MENOR capacidad para negociar una multa de tráfico.', 'ranking', 'habilidades', NULL, false, 4, ARRAY['💪']),
('{member_A} vs {member_B}: ¿Quién ganaría en un debate sobre un tema que no conoce?', 'vs', 'habilidades', NULL, false, 2, ARRAY['💪']),
('Del 1 al 10, ¿qué tan bueno es {member_A} detectando cuando alguien miente?', 'scale', 'habilidades', NULL, false, 2, ARRAY['💪']),
('Ordena al grupo según su habilidad para organizar el viaje perfecto.', 'ranking', 'habilidades', NULL, false, 4, ARRAY['💪']),
('{member_A} vs {member_B}: ¿Quién tiene más sentido de la orientación en una ciudad nueva?', 'vs', 'habilidades', NULL, false, 2, ARRAY['💪']),

-- 🔮 Futuro (poll, vs)
('¿Quién del grupo se hará rico con una idea de negocio absurda?', 'poll', 'futuro', NULL, false, 2, ARRAY['🔮']),
('{member_A} vs {member_B}: ¿Quién se mudará antes al extranjero?', 'vs', 'futuro', NULL, false, 2, ARRAY['🔮']),
('¿Quién será el primero en casarse (o volver a hacerlo)?', 'poll', 'futuro', NULL, false, 2, ARRAY['🔮']),
('{member_A} vs {member_B}: ¿Quién publicará un libro antes de los 50?', 'vs', 'futuro', NULL, false, 2, ARRAY['🔮']),
('Si alguien de aquí acaba en una isla desierta en 10 años, ¿quién sería?', 'poll', 'futuro', NULL, false, 2, ARRAY['🔮']),
('{member_A} vs {member_B}: ¿Quién tendrá una mansión con piscina antes?', 'vs', 'futuro', NULL, false, 2, ARRAY['🔮']),
('¿Quién del grupo adoptará 5 gatos y se volverá un ermitaño?', 'poll', 'futuro', NULL, false, 2, ARRAY['🔮']),
('{member_A} vs {member_B}: ¿Quién llegará a los 80 años con más energía?', 'vs', 'futuro', NULL, false, 2, ARRAY['🔮']),
('¿Quién será el primero en tener su propio podcast de éxito?', 'poll', 'futuro', NULL, false, 2, ARRAY['🔮']),
('{member_A} vs {member_B}: ¿Quién cambiará de carrera profesional radicalmente?', 'vs', 'futuro', NULL, false, 2, ARRAY['🔮']),
('¿Quién del grupo ganará un premio por su labor solidaria?', 'poll', 'futuro', NULL, false, 2, ARRAY['🔮']),
('{member_A} vs {member_B}: ¿Quién acabará viviendo en una casa rural autosuficiente?', 'vs', 'futuro', NULL, false, 2, ARRAY['🔮']),
('¿Quién de aquí será el amigo que organice las reuniones de viejitos?', 'poll', 'futuro', NULL, false, 2, ARRAY['🔮']),

-- 🌶️ Atrevidas (vs, free - ANONYMOUS)
('{member_A} vs {member_B}: ¿A quién llamarías si necesitases ayuda para ocultar un "error" grave?', 'vs', 'atrevidas', NULL, true, 2, ARRAY['🌶️']),
('¿Cuál es la mentira más grande que has contado para evitar una cita?', 'free', 'atrevidas', NULL, true, 2, ARRAY['🌶️']),
('{member_A} vs {member_B}: ¿Quién es más probable que haya espiado el móvil de su pareja?', 'vs', 'atrevidas', NULL, true, 2, ARRAY['🌶️']),
('Confiesa algo que el grupo no sepa de ti y les dejaría en shock.', 'free', 'atrevidas', NULL, true, 2, ARRAY['🌶️']),
('{member_A} vs {member_B}: ¿Quién ha tenido un "crush" secreto con alguien de este grupo?', 'vs', 'atrevidas', NULL, true, 2, ARRAY['🌶️']),
('¿Qué es lo más atrevido que has hecho en un lugar público?', 'free', 'atrevidas', NULL, true, 2, ARRAY['🌶️']),
('{member_A} vs {member_B}: ¿Quién perdonaría antes una traición amorosa?', 'vs', 'atrevidas', NULL, true, 2, ARRAY['🌶️']),
('¿Alguna vez te has sentido atraído/a por un/a ex de alguien de este grupo?', 'free', 'atrevidas', NULL, true, 2, ARRAY['🌶️']),
('{member_A} vs {member_B}: ¿Quién miente más a menudo para quedar bien?', 'vs', 'atrevidas', NULL, true, 2, ARRAY['🌶️']),
('¿Cuál ha sido tu peor experiencia en una primera cita?', 'free', 'atrevidas', NULL, true, 2, ARRAY['🌶️']),
('{member_A} vs {member_B}: ¿Quién es más celoso en una relación?', 'vs', 'atrevidas', NULL, true, 2, ARRAY['🌶️']),
('Si pudieras borrar un momento vergonzoso de tu vida, ¿cuál sería?', 'free', 'atrevidas', NULL, true, 2, ARRAY['🌶️']),
('{member_A} vs {member_B}: ¿Quién es más propenso a tener una crisis existencial nocturna?', 'vs', 'atrevidas', NULL, true, 2, ARRAY['🌶️']),
('¿Qué es lo más raro que has buscado en modo incógnito últimamente?', 'free', 'atrevidas', NULL, true, 2, ARRAY['🌶️']),

-- 🧠 Hipotéticas (mc, vs, free)
('Si fueras un animal, ¿cuál encajaría mejor con la personalidad de {member_A}?', 'mc', 'hipoteticas', ARRAY['León perezoso', 'Gato aristocrático', 'Suricata hiperactiva', 'Búho intelectual'], false, 2, ARRAY['🧠']),
('{member_A} vs {member_B}: ¿Quién sobreviviría si fueran transportados al año 1500?', 'vs', 'hipoteticas', NULL, false, 2, ARRAY['🧠']),
('Si pudieras tener un superpoder, pero solo uno absurdo, ¿cuál elegirías?', 'free', 'hipoteticas', NULL, false, 2, ARRAY['🧠']),
('¿Qué haría {member_A} si se despertara siendo el presidente del gobierno?', 'mc', 'hipoteticas', ARRAY['Legalizar la siesta obligatoria', 'Huir del país de inmediato', 'Declarar la guerra al madrugón', 'Organizar una fiesta en la Moncloa'], false, 2, ARRAY['🧠']),
('{member_A} vs {member_B}: ¿Quién sería el primero en ser abducido por extraterrestres?', 'vs', 'hipoteticas', NULL, false, 2, ARRAY['🧠']),
('Si mañana descubrieras que el mundo es una simulación, ¿qué es lo primero que harías?', 'free', 'hipoteticas', NULL, false, 2, ARRAY['🧠']),
('En un futuro donde la comida es solo pastillas, ¿qué echaría más de menos {member_A}?', 'mc', 'hipoteticas', ARRAY['La pizza grasienta', 'El ritual de cocinar', 'La textura del pan', 'La sobremesa infinita'], false, 2, ARRAY['🧠']),
('{member_A} vs {member_B}: ¿Quién ganaría en una pelea contra un clon de sí mismo?', 'vs', 'hipoteticas', NULL, false, 2, ARRAY['🧠']),
('Si pudieras viajar al pasado solo para darte un consejo a ti mismo de 10 años, ¿qué sería?', 'free', 'hipoteticas', NULL, false, 2, ARRAY['🧠']),
('¿Cómo reaccionaría {member_A} ante un apocalipsis de payasos asesinos?', 'mc', 'hipoteticas', ARRAY['Los intentaría hacer reír', 'Se escondería debajo de la cama', 'Combatiría con globos de agua', 'Se uniría a ellos'], false, 2, ARRAY['🧠']),
('{member_A} vs {member_B}: ¿Quién sería el mejor embajador de la Tierra en un concilio galáctico?', 'vs', 'hipoteticas', NULL, false, 2, ARRAY['🧠']),
('Si pudieras vivir en cualquier mundo de ficción, ¿cuál elegirías y por qué?', 'free', 'hipoteticas', NULL, false, 2, ARRAY['🧠']),
('{member_A} vs {member_B}: ¿Quién se haría amigo de un fantasma que habita su casa?', 'vs', 'hipoteticas', NULL, false, 2, ARRAY['🧠']),

-- 💛 Vínculos (poll, scale, free)
('¿Quién es la persona a la que todos llamarían a las 3 AM si tuviesen un problema?', 'poll', 'vinculos', NULL, false, 2, ARRAY['💛']),
('¿Qué tanto confías en el criterio de {member_A} para dar consejos amorosos?', 'scale', 'vinculos', NULL, false, 2, ARRAY['💛']),
('Describe un momento en el que este grupo te hizo sentir realmente apoyado/a.', 'free', 'vinculos', NULL, false, 2, ARRAY['💛']),
('¿Quién del grupo es más probable que sepa qué te pasa sin que digas nada?', 'poll', 'vinculos', NULL, false, 2, ARRAY['💛']),
('Del 1 al 10, ¿qué tan unido crees que está este grupo actualmente?', 'scale', 'vinculos', NULL, false, 2, ARRAY['💛']),
('¿Qué es lo que más valoras de tu amistad con la persona que tienes a tu derecha (metafóricamente)?', 'free', 'vinculos', NULL, false, 2, ARRAY['💛']),
('¿Quién es el pegamento que mantiene unido al grupo en los momentos difíciles?', 'poll', 'vinculos', NULL, false, 2, ARRAY['💛']),
('¿Qué nota le das a la capacidad de {member_A} para escuchar sin juzgar?', 'scale', 'vinculos', NULL, false, 2, ARRAY['💛']),
('Si tuvieras que definir este grupo en una sola palabra, ¿cuál sería?', 'free', 'vinculos', NULL, false, 2, ARRAY['💛']),
('¿Quién del grupo siempre tiene las palabras adecuadas para animarte?', 'poll', 'vinculos', NULL, false, 2, ARRAY['💛']),
('Del 1 al 10, ¿qué tan seguro te sientes expresando tus vulnerabilidades aquí?', 'scale', 'vinculos', NULL, false, 2, ARRAY['💛']),
('Cuéntanos una anécdota que defina perfectamente la esencia de este grupo.', 'free', 'vinculos', NULL, false, 2, ARRAY['💛']),
('¿Quién es el más detallista cuando alguien del grupo tiene un logro o cumpleaños?', 'poll', 'vinculos', NULL, false, 2, ARRAY['💛']),
('¿Qué importancia tiene este grupo en tu día a día (del 1 al 10)?', 'scale', 'vinculos', NULL, false, 2, ARRAY['💛']),

-- 🎉 Eventos (vs, poll, ranking)
('{member_A} vs {member_B}: ¿Quién organizaría la fiesta de cumpleaños más épica?', 'vs', 'eventos', NULL, false, 2, ARRAY['🎉']),
('¿Quién es el primero en abandonar el barco en una noche de fiesta intensa?', 'poll', 'eventos', NULL, false, 2, ARRAY['🎉']),
('Ordena de MEJOR a PEOR organizador de viajes grupales.', 'ranking', 'eventos', NULL, false, 4, ARRAY['🎉']),
('{member_A} vs {member_B}: ¿Quién es más probable que pierda el vuelo/tren en un viaje?', 'vs', 'eventos', NULL, false, 2, ARRAY['🎉']),
('¿Quién es el que siempre propone el plan pero nunca llega a tiempo?', 'poll', 'eventos', NULL, false, 2, ARRAY['🎉']),
('Ordena al grupo según quién se queda dormido antes en una cena de Año Nuevo.', 'ranking', 'eventos', NULL, false, 4, ARRAY['🎉']),
('{member_A} vs {member_B}: ¿Quién elegiría el destino de vacaciones más extraño?', 'vs', 'eventos', NULL, false, 2, ARRAY['🎉']),
('¿Quién del grupo es el responsable de hacer las fotos en todos los eventos?', 'poll', 'eventos', NULL, false, 2, ARRAY['🎉']),
('Ordena al grupo según su aguante en la pista de baile.', 'ranking', 'eventos', NULL, false, 4, ARRAY['🎉']),
('{member_A} vs {member_B}: ¿Quién sería el invitado más "showsero" en una boda?', 'vs', 'eventos', NULL, false, 2, ARRAY['🎉']),

-- 🤖 IA personalizada (Mixed)
('{member_A} vs {member_B}: ¿Quién se adaptaría primero a vivir con un robot asistente?', 'vs', 'ia_custom', NULL, false, 2, ARRAY['🤖']),
('¿Qué es lo que la IA nunca podría replicar de la personalidad de {member_A}?', 'free', 'ia_custom', NULL, false, 2, ARRAY['🤖']),
('Si una IA tuviera que elegir al líder emocional del grupo, ¿quién sería?', 'poll', 'ia_custom', NULL, false, 2, ARRAY['🤖']),
('¿Qué tanto crees que {member_A} depende de su móvil para vivir (1-10)?', 'scale', 'ia_custom', NULL, false, 2, ARRAY['🤖']),
('Ordena al grupo de MÁS a MENOS probable que sea reemplazado por un algoritmo.', 'ranking', 'ia_custom', NULL, false, 4, ARRAY['🤖']),
('{member_A} vs {member_B}: ¿Quién discutirá con una IA por no darle la razón?', 'vs', 'ia_custom', NULL, false, 2, ARRAY['🤖']),
('¿Cuál sería el primer comando que {member_A} le daría a un asistente holográfico?', 'mc', 'ia_custom', ARRAY['Hazme un café perfecto', 'Limpia toda la casa ya', 'Búscame un chiste bueno', 'Tradúceme el sentido de la vida'], false, 2, ARRAY['🤖']),
('¿Quién del grupo acabará casándose con un avatar virtual?', 'poll', 'ia_custom', NULL, false, 2, ARRAY['🤖']),
('Del 1 al 10, ¿qué tan asustado está {member_A} por el avance de la tecnología?', 'scale', 'ia_custom', NULL, false, 2, ARRAY['🤖']),
('¿Qué consejo le darías a una IA que quiere aprender a ser tan buen amigo como vosotros?', 'free', 'ia_custom', NULL, false, 2, ARRAY['🤖']);
